### ISSUE TITLE
OSRM does not recognize 'areas'

### ISSUE THREAD

**Issue by joovel** [Project-OSRM/osrm-backend#4294] opened 2017-07-14 15:40 UTC
When requesting foot directions, OSRM doesn't seem to recognize traversable plazas. 

I was able to get a similar result to OSRM by going through OSM, so here's an example of what we see. If necessary, I can build a script that uses OSRM and the Portland Oregon USA Mapzen extract.
https://www.openstreetmap.org/directions?engine=mapzen_foot&route=45.43826%2C-122.73097%3B45.43997%2C-122.73176#map=19/45.43913/-122.73167

The pedestrian paths are discontinuous, so the origin snaps to the nearest path. However, in reality, the pedestrian plaza means that all the paths that touch the plaza connect to all others via a straight line. Then, the search is essentially abandoned.

I noticed that the same problem occurs even if origin and destination are swapped.

Is there a way to tag these plazas on OSM so that OSRM will see them?

Alternately: I don't quite understand OSRM enough to know this: Why isn't OSRM trying both directions? If you snap one location, you get a short walk that leaves you far from both points. If you snap the other location and start there, you should get a much more sensible walk that leaves you much closer to one of the points.

**Comment by daniel-j-h** [comment] 2017-07-14 16:03
Closing as duplicate of https://github.com/Project-OSRM/osrm-backend/issues/64.

Note that we don't provide foot directions on openstreetmap.org only car directions (it"s basically the demo server http://map.project-osrm.org/ on the osm website). The ticket linked above has some interesting discussions; please read them and add to the ticket to keep the discussion there. Thanks!

**Closed by daniel-j-h** 2017-07-14 16:03 UTC
