### ISSUE TITLE
Not routable segment

### ISSUE THREAD

**Issue by dominguezgf** [Project-OSRM/osrm-backend#2637] opened 2016-07-07 15:59 UTC
Dear,
I have found that at some point, routing does not work properly.
I checked the mapping, and the same is generated correctly.
For better compresicón, access to these two links.

http://map.project-osrm.org/?z=13&center=22.380238%2C-102.260914&loc=22.353251%2C-102.293959&loc=22.396983%2C-102.308292&hl=en&alt=0

https://www.google.com.ar/maps/dir/22.36332,-102.2959055/22.4014971,-102.3109946/@22.3763056,-102.3047045,14.5z

**Comment by daniel-j-h** [comment] 2016-07-07 16:27
Thanks for reaching out! Indeed it seems like this is the problematic way:

http://map.project-osrm.org/?z=18&center=22.371743%2C-102.298298&loc=22.371830%2C-102.298293&loc=22.373655%2C-102.298170&hl=en&alt=0

Here's the way we should route you over:
https://www.openstreetmap.org/way/302371148#map=18/22.37442/-102.29740&layers=D

It's a oneway but the direction is correct from what I can see.

This is the link onto the way:
https://www.openstreetmap.org/way/302370824

and here is the node at the end of it:
https://www.openstreetmap.org/node/1226798260

**Comment by utack** [comment] 2016-07-07 16:30
https://www.openstreetmap.org/node/2294905064#map=15/22.3802/-102.3008

**Comment by daniel-j-h** [comment] 2016-07-07 16:34
Ha good catch, thanks @utack! Closing here as not actionable for us. Feel free to comment though.

**Closed by daniel-j-h** 2016-07-07 16:34 UTC

**Comment by danpat** [comment] 2016-07-07 16:39
http://map.project-osrm.org/debug/#15.33/22.3796/-102.3002

The pink highlighted area indicates roads that aren't externally routable in both directions, in the OSRM code, this is called a "small component", a road group that's isolated from the rest of the network.

As @utack found, this is being caused by the barrier node on the highway.  `barrier=yes` means no traffic can pass, and this basically cuts the road network at this point.  Because of its placement, this is isolating several other roads in the area.

**Comment by dominguezgf** [comment] 2016-07-07 18:32
Dear,
Thank you for all the info.
