### ISSUE TITLE
Speed bug related to…bearing? End segment?

### ISSUE THREAD

**Issue by lbud** [Project-OSRM/osrm-backend#2162] opened 2016-03-29 19:28 UTC
@MoKob @TheMarex  — I would have suspected this related to #2155, but that is fixed and this is not:

features/car/advisory.feature has a test as follows:
```
    Scenario: Car - Advisory speed overwrites backwards maxspeed
        Given the node map
            | a | b | c |

        And the ways
            | nodes | highway       | maxspeed:backward | maxspeed:advisory:backward |
            | ab    | residential   | 90                | 45                         |
            | bc    | residential   |                   | 45                         |

        When I route I should get
            | from | to | route | speed        |
            | b    | a  | ab    | 47 km/h +- 1 |
            | c    | b  | bc    | 47 km/h +- 1 |
```

b-a fails with `19 km/h`; c-b succeeds.
Now, if I add an additional segment to the left side of the requested segment, i.e.
```
    Scenario: Car - Advisory speed overwrites backwards maxspeed
        Given the node map
            | a | b | c | d |

        And the ways
            | nodes | highway       | maxspeed:backward | maxspeed:advisory:backward |
            | ab    | residential   |                   | 45                         |
            | bc    | residential   | 90                | 45                         |
            | cd    | residential   |                   | 45                         |

        When I route I should get
            | from | to | route | speed        |
            | c    | b  | bc    | 47 km/h +- 1 |
            | d    | c  | cd    | 47 km/h +- 1 |
```

this succeeds.

The difference between these routes is that on the failing test, where `ab` is the leftmost segment, the departure and arrival are both on `ab`, and the departure has no bearing before or after. On the passing test, where we instead test the middle segment with the same attributes, the departure and arrival are on different segments, and the departure has a bearing_before of 0 and a bearing_after of 270:

*FAILS:* 
```
[ { distance: 999.8,
    duration: 192.7,
    name: 'ab',
    maneuver: 
     { type: 'depart',
       location: [Object],
       bearing_before: 0,
       bearing_after: 0 },
    geometry: '_ibEeadE???dw@',
    mode: 'driving' },
  { distance: 0,
    duration: 0,
    name: 'ab',
    maneuver: 
     { type: 'arrive',
       location: [Object],
       bearing_before: 270,
       bearing_after: 0 },
    geometry: '',
    mode: 'driving' } ]
[ { distance: 999.9,
    duration: 76.6,
    name: 'bc',
    maneuver: 
     { type: 'depart',
       location: [Object],
       bearing_before: 0,
       bearing_after: 270 },
    geometry: '_ibEkyeE?dw@',
    mode: 'driving' },
  { distance: 0,
    duration: 0,
    name: 'ab',
    maneuver: 
     { type: 'arrive',
       location: [Object],
       bearing_before: 270,
       bearing_after: 0 },
    geometry: '_ibEeadE??',
    mode: 'driving' } ]
```

```
[ { distance: 999.9,
    duration: 76.6,
    name: 'bc',
    maneuver: 
     { type: 'depart',
       location: [Object],
       bearing_before: 0,
       bearing_after: 270 },
    geometry: '_ibEkyeE?dw@',
    mode: 'driving' },
  { distance: 0,
    duration: 0,
    name: 'ab',
    maneuver: 
     { type: 'arrive',
       location: [Object],
       bearing_before: 270,
       bearing_after: 0 },
    geometry: '_ibEeadE??',
    mode: 'driving' } ]
[ { distance: 999.9,
    duration: 76.6,
    name: 'cd',
    maneuver: 
     { type: 'depart',
       location: [Object],
       bearing_before: 0,
       bearing_after: 270 },
    geometry: '_ibEqqgE?dw@',
    mode: 'driving' },
  { distance: 0,
    duration: 0,
    name: 'bc',
    maneuver: 
     { type: 'arrive',
       location: [Object],
       bearing_before: 270,
       bearing_after: 0 },
    geometry: '_ibEkyeE??',
    mode: 'driving' } ]
```

**Comment by MoKob** [comment] 2016-03-30 11:38
the pull request I have could bring us to solve this problem instantly if we change https://github.com/Project-OSRM/osrm-backend/pull/2170/files#diff-ffa2e7ac24f3bebb547c6fe24552431bR428 to directly set the value to `0`. This would only handle the symptoms and not fix the full problem.

@danpat the issue is with the weight-vector offsets being inconsistent with the phantom nodes in this case (and also with the found route length). Could you take over #2170 to see if whats going with the weight-vector?

**Comment by MoKob** [comment] 2016-03-30 13:33
Have to take this back first, since there are some other issues in that part of the code that I am looking into right now.

**Comment by MoKob** [comment] 2016-04-05 10:29
Should be fixed with all tests passing now

**Closed by MoKob** 2016-04-05 10:29 UTC
Labels: Guidance, Refactor
