### ISSUE TITLE
osrm-contract crashes with core factor 1.0

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3175] opened 2016-10-25 20:38 UTC
When running some experiments with traffic data, level-cache and core-factor 1.0 I encountered the problem that `osrm-contract` will crash with crash when specifying a core core factor of `1.0`.

Trying to reproduce this on master.

**Comment by daniel-j-h** [comment] 2016-11-11 17:07
Ping - any update here?

**Comment by TheMarex** [comment] 2016-11-12 13:55
Haven't been able to re-produce this locally. However I saw this behavior on `5.4.2` with a planet datasets using the pre-compiled binaries from `node-osrm`. If you could lend me a hand for launching a stack to verify this doesn't happen on `5.5.0-rc.1` anymore I would be glad to walk you through it.

**Comment by daniel-j-h** [comment] 2016-11-23 16:55
I looked into this - ran a stack on the planet with a core factor of 1 and updating weights. Couldn't reproduce the issue so far with latest master. If you're seeing this again with the latest release please re-open or create a new ticket. Closing this as not actionable.

**Closed by daniel-j-h** 2016-11-23 16:55 UTC
Labels: Bug Report
