### ISSUE TITLE
Route sends traffic up a one-way street

### ISSUE THREAD

**Issue by scottybo** [Project-OSRM/osrm-backend#5899] opened 2020-11-29 17:59 UTC
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/11498904/100549753-c8b39080-326c-11eb-8c92-0f8f327169a3.png">

Friar's Street, as mentioned in the image, is a one-way street. Delivery drivers come up it regularly the wrong way, and as you can see, the route planner is sending drivers up the wrong way.

Demo starting point: Greyfriars, Bridgnorth, Shropshire, West Midlands, England, WV16 4JX, United Kingdom

Demo ending point: Friar's Street, Bridgnorth, Shropshire, West Midlands, England, WV16 4BJ, United Kingdom

**Comment by danpat** [comment] 2020-11-29 19:36
Looks like Friar's Street is not marked as oneway: https://www.openstreetmap.org/way/145736225

This is a data issue, not a bug with OSRM.  Someone with local knowledge should correct the mapping in OSM here.  The route results will be fixed once the roads are properly tagged, and the demoserver has imported a fresh dataset.

**Closed by danpat** 2020-11-29 19:36 UTC
