### ISSUE TITLE
GCC/ LTO: Internal Compiler Error (lto_varpool_replace_node), different optimization flags

### ISSUE THREAD

**Issue by julienfr112** [Project-OSRM/osrm-backend#2951] opened 2016-09-26 18:17 UTC
after compilation of all lib and programs without problem:

cd example;mkdir build;cd build;cmake ..;make

[ 50%] Linking CXX executable osrm-example
lto1: internal compiler error: in lto_varpool_replace_node, at lto/lto-symtab.c:143
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-5/README.Bugs for instructions.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed

ubuntu 16.04, gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)

**Comment by daniel-j-h** [comment] 2016-09-27 12:22
Looks like [a bug in GCC's LTO implementation due to using different optimization flag](https://gcc.gnu.org/ml/gcc-bugs/2016-01/msg00667.html).

If I can remember correctly @springmeyer adapted the build system a couple of month ago to now use the same optimization flags everywhere, not sure what's the state of this though.

Here's a workaround for now: build both `libosrm` as well as the example without LTO:

    cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=OFF
    cmake --build .

**Comment by TheMarex** [comment] 2016-11-16 22:03
Problem is caused by the fact that we export `CMAKE_CXX_FLAGS` as cflags in our `libosrm.pc` file. This includes a ton of internal flags that make GCC crash when used on binaries and not on libraries apparently.

**Comment by TheMarex** [comment] 2016-11-19 16:02
Fixed by #3330.

**Closed by TheMarex** 2016-11-19 16:02 UTC
Labels: Bug Report, Compilation
