### ISSUE TITLE
osrm data update

### ISSUE THREAD

**Issue by swordOfMiracle** [Project-OSRM/osrm-backend#2378] opened 2016-05-05 17:24 UTC
Can I update a little part of osrm data(I mean a set of files, such as `.osrm`, `.edges`, `.hsgr` etc) without calling `osrm-extract`/`osrm-contract` again ?

For example - setting a barrier to the highway and it is becoming not-drivable way.

**Comment by danpat** [comment] 2016-05-05 17:54
@swordOfMiracle as a general rule, no, not without creating the potential for invalid routes.

OSRM uses the `.hsgr` for routing.  Unfortunately, because of the way Contraction Hierarchies work, if you update something in the original graph, you probably need to re-generate the contracted graph - small changes in the original can lead to large changes in the `.hsgr` file.

Just today I've opened a separate ticket https://github.com/Project-OSRM/osrm-backend/issues/2377 to discuss one possible way of supporting a limited set of modifyable edges within the CH without requiring a full re-processing run.

**Comment by TheMarex** [comment] 2016-05-26 21:11
Closing as duplicate of #2377.

**Closed by TheMarex** 2016-05-26 21:11 UTC
