### ISSUE TITLE
Trip plugin should return a route that begins at the first coordinate unless otherwise specified

### ISSUE THREAD

**Issue by ghoshkaj** [Project-OSRM/osrm-backend#3650] opened 2017-02-03 20:30 UTC

**Comment by chaupow** [comment] 2017-02-06 10:23
Is this a duplicate of #1939 ?
If so, let's close one :)

**Comment by danpat** [comment] 2017-02-06 13:28
Yup, dupe, good catch @chaupow :-)

**Closed by danpat** 2017-02-06 13:28 UTC
