### ISSUE TITLE
Increased Memory Consumption: 5.4 RCs vs 5.3

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2926] opened 2016-09-16 11:32 UTC
We're seeing a roughly 20% increase in memory utilization with the 5.4 RCs compared to 5.3 which we can not explain. Here's what we found so far.

---------------------------------------------------------------------------------------------------------------------------

From logs we see this happening during [extraction, parsing](https://github.com/Project-OSRM/osrm-backend/blob/70ee624e5c269052f04f3ffbdf61b6672888c245/src/extractor/extractor.cpp#L109).

It happens not only on bike but also on car (bike profile does not include lanes or turn restrictions but (!) the restriction parser is still getting called always returning [an empty optional](https://github.com/Project-OSRM/osrm-backend/blob/70ee624e5c269052f04f3ffbdf61b6672888c245/src/extractor/restriction_parser.cpp#L61-L64)).

It seems to happen on larger datasets only, e.g. on the planet. But not on smaller ones.

https://github.com/Project-OSRM/osrm-backend/issues/2704 => [String deduplication map](https://github.com/Project-OSRM/osrm-backend/blob/70ee624e5c269052f04f3ffbdf61b6672888c245/include/extractor/extractor_callbacks.hpp#L57-L61) size looks reasonable; dumping some stats about the map did not reveal anything (e.g. a lot of hash collisions).

Extractor allbacks are explicitly getting [allocated](https://github.com/Project-OSRM/osrm-backend/blob/70ee624e5c269052f04f3ffbdf61b6672888c245/src/extractor/extractor.cpp#L128) and [destroyed](https://github.com/Project-OSRM/osrm-backend/blob/70ee624e5c269052f04f3ffbdf61b6672888c245/src/extractor/extractor.cpp#L221) again.

Extraction containers are [scoped](https://github.com/Project-OSRM/osrm-backend/blob/70ee624e5c269052f04f3ffbdf61b6672888c245/src/extractor/extractor.cpp#L127) to the extractor and are cleaned up once we serialized the data out.

-----------------------------------------------------------------------------------------------------------------------------

Other possibilities we need to investigate:

Touching the restriction parser code: https://github.com/Project-OSRM/osrm-backend/pull/2829

Changing the scripting environment: https://github.com/Project-OSRM/osrm-backend/commit/1309dd2a0f5b58360b0fd82cbc9dca36740d5852 - currently running a staging stack changeset reverted. Restriction parser only need the scripting environment in the ctor for [getting turn restrictions from profiles](https://github.com/Project-OSRM/osrm-backend/blob/70ee624e5c269052f04f3ffbdf61b6672888c245/src/extractor/restriction_parser.cpp#L32).

Attach heap profiler (e.g. GPerfTools) and run on planet: we only see this behavior on larger datasets.

**Comment by MoKob** [comment] 2016-09-27 07:01
From our experiments, the memory issue seems to be an interaction between lua 5.3 and osrm 5.4, introduced with https://github.com/Project-OSRM/osrm-backend/commit/1309dd2a0f5b58360b0fd82cbc9dca36740d5852. We are going with lua 5.2.1 right now, but we need to figure out where the issues are coming from.

**Comment by springmeyer** [comment] 2016-09-28 05:06
I've been investigating this further. I've confirmed a second time that downgrading from lua 5.3 to 5.2 solves the problem as encountered in node-osrm were lua 5.3.0 had been in use as the default for building binaries. That fix landed in https://github.com/Project-OSRM/node-osrm/pull/251.

In testing it does not appear that https://github.com/Project-OSRM/osrm-backend/commit/1309dd2a0f5b58360b0fd82cbc9dca36740d5852 introduced the problem. Rather my current guess (and line of investigation) is that lua 5.3 has been slow and using greater memory all along than lua 5.2.4 would. And no single commit in osrm-backend 5.4 triggered the problem. Rather the cumulative, slightly greater usage of lua processing in 5.4 made an existing problem reach a tipping point.

**Comment by daniel-j-h** [comment] 2016-09-28 12:37
Next actions:
- [ ] detect only Lua51 or Lua52 with CMake
- [ ] error out if installed version is different

**Comment by springmeyer** [comment] 2016-10-04 05:51
> Rather my current guess (and line of investigation) is that lua 5.3 has been slow and using greater memory all along than lua 5.2.4 would. And no single commit in osrm-backend 5.4 triggered the problem. Rather the cumulative, slightly greater usage of lua processing in 5.4 made an existing problem reach a tipping point.

Further testing points to this as being the case as a response on the users list indicated the difference could be explained by changes in garbage collection (http://lua-users.org/lists/lua-l/2016-09/msg00388.html) and I can confirm that major changes to gc code happened (based on diffing the codebases) between 52 and 53. I played around with various garbage collection settings, and was able to drastically shrink the peak memory needs with lua 5.3, but not as much as needed to get 5.2 parity without killing performance. So, I think this can be closed with @daniel-j-h's next actions. At some point others may wish to profile a future lua 5.3 release to see if osrm-backends usage can be sped up - but please create new issues if you have this interest. For now I think sticking to and requiring lua 5.2 is the best approach.

**Closed** 2016-10-04 08:34 UTC
Labels: Bug Report
