### ISSUE TITLE
Benchmark boost CSV parsing

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#3974] opened 2017-04-25 22:59 UTC
Working on another internal project, we noticed that using `boost::spirit` to parse CSV data was not super performant.  Ripping out the `boost::spirit` code and replacing it with https://github.com/ben-strasser/fast-cpp-csv-parser gave a huge speedup.

We should re-visit the CSV parsing for traffic updates - `fast-cpp-csv-parser` was about 10x faster for linear parsing.

**Comment by TheMarex** [comment] 2017-04-28 12:32
We had this originally https://github.com/Project-OSRM/osrm-backend/pull/1764/files and ripped it out because it was slower then just using `boost::spirit`. So one of these benchmarks must have been wrong.

**Comment by oxidase** [comment] 2017-04-28 12:37
@TheMarex there is a possible performance regression in using `boost::spirit::istream_iterator` that is visible on >1GB files. It should be checked and reverted.

**Comment by oxidase** [comment] 2017-05-08 15:37
Closed via #4010

**Closed by oxidase** 2017-05-08 15:37 UTC
