### ISSUE TITLE
Assertion hit on demo server in post-processing

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3135] opened 2016-10-20 20:58 UTC
```
assert] /mnt/ebs/osrm/2016-10-13-224444/src/engine/guidance/post_processing.cpp:265
in: void osrm::engine::guidance::{anonymous}::closeOffRoundabout(bool, std::vector<osrm::engine::guidance::RouteStep>&, std::size_t): leavesRoundabout(steps[1].maneuver.instruction) || steps[1].maneuver.instruction.type == TurnType::StayOnRoundabout || steps[1].maneuver.instruction.type == TurnType::Suppressed || steps[1].maneuver.instruction.type == TurnType::NoTurn
terminate called without an active exception
/usr/local/src/app/bin/run: line 16: 70948 Aborted                 "${OSRMDir}/current/build/osrm-routed" -p ${port:-80} "${DataDir}/current/latest.osrm"
placeholder-webserver start/running, process 118312
```

There are a few requests before this assertion, didn't dig through them yet.

/cc @MoKob

**Comment by daniel-j-h** [comment] 2016-10-20 21:23
Closing as duplicate of https://github.com/Project-OSRM/osrm-backend/issues/3085.

**Closed by daniel-j-h** 2016-10-20 21:23 UTC
Labels: Bug Report, Guidance
