### ISSUE TITLE
Strange error in route with intermediate point and one-way street

### ISSUE THREAD

**Issue by fpacheco** [Project-OSRM/osrm-backend#1424] opened 2015-03-26 18:51 UTC
One-way street with an intermediate point located in the same block as the destination. 

http://osrm.at/bys

How can it be avoided?

**Comment by TheMarex** [comment] 2015-03-26 20:47
Sorry, I don't understand what is wrong with that route. Can you elaborate a bit more? Thanks!

**Comment by fpacheco** [comment] 2015-03-26 20:53
Sorry, I sent the wrong link!.

This is one that correctly describes the problem: http://osrm.at/byx
Or this other: http://osrm.at/byy

Thank you. Fernando.

**Comment by fpacheco** [comment] 2015-03-26 21:00
For the first link I expect something like this ...  
![osrm_test_3](https://cloud.githubusercontent.com/assets/89121/6856915/dc36f8f8-d3e1-11e4-9ede-412349b08d47.png)

**Comment by DennisOSRM** [comment] 2015-03-27 08:23
Interesting bug. We'll look into that.

**Comment by DennisOSRM** [comment] 2015-03-27 09:20
I have found a (minor) issue that caused this odd behavior. I am working on a fix for this now. With that fix, routes will look like this

![screenshot from 2015-03-27 10 18 13](https://cloud.githubusercontent.com/assets/1067895/6865102/c5e1eff2-d46a-11e4-967c-0c305414cef9.png)

instead of this

![screenshot from 2015-03-27 10 18 30](https://cloud.githubusercontent.com/assets/1067895/6865101/c14b0a78-d46a-11e4-93e3-1c5b6439f12e.png)

I'll push the fix later today to develop branch but will also take some extra care to make sure that the fix doesnt have any unexpected side effects.

**Comment by DennisOSRM** [comment] 2015-03-27 17:01
Fix has been published. Will close when the next full update cycle completes and the fix is live on the demo site. 

Thanks again for reporting @fpacheco

**Comment by DennisOSRM** [comment] 2015-03-30 07:21
All good now:

![screenshot 2015-03-30 09 20 10](https://cloud.githubusercontent.com/assets/1067895/6891752/12446410-d6be-11e4-9f48-b688932e6d57.png)
![screenshot 2015-03-30 09 20 20](https://cloud.githubusercontent.com/assets/1067895/6891753/1269c71e-d6be-11e4-9fcf-59d27e99e639.png)

**Comment by danpat** [comment] 2015-04-14 23:28
Looks like this change created #1429.

**Comment by DennisOSRM** [comment] 2015-04-15 19:09
@danpat thanks for the pointer. Will investigate.

**Comment by TheMarex** [comment] 2015-05-18 16:22
Has to revert the fix because it caused regression.

**Comment by woodbri** [comment] 2015-05-22 14:26
This issue is cause us major problems. It would be great if someone could investigate this again. We can throw a lot of resources into testing any changes if that helps. I looked at the source code, but I don't have enough expertise to understand how this works yet.

**Comment by danpat** [comment] 2015-05-22 18:31
It looks like the detail here is that if the via point and the destination are on the same way, then routing is ignoring one-way indicators on that way.  @woodbri - does this match the error situations you're seeing?

**Comment by danpat** [comment] 2015-05-22 18:55
Another test scenario - two vias on same way are visited incorrectly:
http://osrm.at/cwm
![screen shot 2015-05-22 at 11 50 07 am](https://cloud.githubusercontent.com/assets/1892250/7777537/d696c52c-0078-11e5-968c-ddfaec2bf1b1.png)

But when "1" is moved onto a different way, routing becomes correct:
http://osrm.at/cwn
![screen shot 2015-05-22 at 11 50 25 am](https://cloud.githubusercontent.com/assets/1892250/7777540/db5a3c6a-0078-11e5-84ea-31a808d32d68.png)

**Comment by woodbri** [comment] 2015-05-22 19:17
I don't think this is related to one-way here is another:
http://osrm.at/cws
![capture](https://cloud.githubusercontent.com/assets/805250/7778021/958d958e-0095-11e5-9e1e-a111b49f922e.PNG)
where the cross with 1 and 2 is two way.

**Comment by woodbri** [comment] 2015-05-22 19:21
And another with all streets two-way, but is is clearly an issue with the multiple nodes on the same segment are appear to be seen as equivalent, rather than costed based on their %age along the segment.
http://osrm.at/cwt
![capture](https://cloud.githubusercontent.com/assets/805250/7778087/30b85f12-0096-11e5-912e-80be204d6e40.PNG)

**Comment by danpat** [comment] 2015-05-23 01:31
Ok, I've been looking at this for a few hours now.  Dennis' original fix for this looks like the right approach (this issue is caused by failing to recognize offsets properly when intermediate points are on the same edge), but introduces #1429.  I'm stepping through why 11c671354be8c791ef107e6ce6c4a38435417edb isn't working right.

**Comment by woodbri** [comment] 2015-05-23 03:51
@danpat Thank you for looking into this. we really appreciate you making time for this.

**Comment by danpat** [comment] 2015-05-25 05:21
Looks like there has been a test case lingering for this scenario for a while:

https://github.com/Project-OSRM/osrm-backend/blob/master/features/testbot/via.feature#L80

It's tagged with `@bug`, so it's not run as part of the default test suite.

**Comment by danpat** [comment] 2015-05-26 19:47
@woodbri - I've come up with a partial fix.  It's not perfect, but it does seem to generate the correct routes.  Grab the changes at #1497 and see if it works for you.

**Comment by woodbri** [comment] 2015-05-27 01:41
@danpat wow, thanks for all the work on this. I was out most of today, but I will take a look tomorrow at the change. Follow in the later discussion on this sounds like there is still some discussion on how best to fix this issue, but I can certainly try this change and see how it impacts things.

**Comment by ZupoLlask** [comment] 2015-06-09 13:46
Hi guys!

It seems to me this issue is also fixed by #1503, right?

**Comment by TheMarex** [comment] 2015-06-09 13:48
Yes this is fixed.

**Closed by TheMarex** 2015-06-09 13:48 UTC

**Comment by etorrano** [comment] 2015-06-09 15:29
It seems to be fixed, but in the following case mentioned above appears a loop instead of the U-turn :
![30b85f12-0096-11e5-912e-80be204d6e40](https://cloud.githubusercontent.com/assets/9082428/8060539/586a4ea8-0e9c-11e5-9458-ef58cdbbd4b8.PNG)

http://osrm.at/cQt

When I put an intermediate point in order to get a better route I get this:

http://osrm.at/cQu

I think this is the right route.
