### ISSUE TITLE
Unexpected end of file 

### ISSUE THREAD

**Issue by tweemaalj1988** [Project-OSRM/osrm-backend#4727] opened 2017-12-07 11:18 UTC
Hello,

I have succesfully installed OSRM:
extract succesfull.
contract succesfull. 

Now i'm using the last command:
osrm-routed netherlands-latest.osrm 

But i'm getting this Error: 

[info] starting up engines, v5.15.0
[info] Threads: 8
[info] IP address: 0.0.0.0
[info] IP port: 5000
[info] load names from: "netherlands-latest.osrm.names"
[error] Unexpected end of file: netherlands-latest.osrm.core (at include/storage/io.hpp:116)

Any ideas how to fix this unexpected end of file error. What did i do wrong? The machine did work for a couple of months. And now, after reboot, and restart i cannot start the process.

**Comment by TheMarex** [comment] 2017-12-07 13:31
Thanks for reporting this. I think this is caused by an old `.core` file. As quick fix for you just delete `netherlands-latest.osrm.core`. There is a bug in OSRM here, because we don't actually need that file anymore, but still error when its corrupted.

**Comment by TheMarex** [comment] 2017-12-08 12:13
This was fixed by #4728 and will be part of the next release.

**Closed by TheMarex** 2017-12-08 12:13 UTC
Labels: Bug Report
