### ISSUE TITLE
endcoordinate geometry not the same as the arrive maneuvre location

### ISSUE THREAD

**Issue by bvbever** [Project-OSRM/osrm-backend#2651] opened 2016-07-12 09:41 UTC
When I run a call for example `https://router.project-osrm.org/route/v1/driving/3.325939178466797,50.995904557496196;3.3414745330810547,51.00462793029727?overview=full&steps=true` and I look at the end coordinate of the full geometry (ex. 3.34146,51.00468) its not the same as the location of the latest steps (3.339556,51.004421) while this maneurertype says 'arrive'. It looks like the latest step returns the second last location.
Is this a bug of do I interpreter it wrongly ?

**Comment by oxidase** [comment] 2016-07-13 05:02
Hi, looks like a duplicate of #2546. Last three points with the recent master are
```
                    [
                        3.33912, 
                        51.004325
                    ], 
                    [
                        3.339556, 
                        51.004421
                    ], 
                    [
                        3.341457, 
                        51.004676
                    ]
                ],
```

**Closed** 2016-07-13 07:51 UTC
