### ISSUE TITLE
Distance Matrix bug

### ISSUE THREAD

**Issue by nsimeonov** [Project-OSRM/osrm-backend#1597] opened 2015-08-13 19:15 UTC
We noticed, that the following list of coordinates returns really weird results:

```js
[
    [34.0009393,-118.4825607],
    [34.146612,-118.4246],
    [34.1360331,-118.352791],
    [34.03668,-118.443158]
    [34.163331,-118.391366]
    [34.1380849,-118.398403]
]
```

http://router.project-osrm.org/table?loc=34.0009393,-118.4825607&loc=34.146612,-118.4246&loc=34.1360331,-118.352791&loc=34.03668,-118.443158&loc=34.163331,-118.391366&loc=34.1380849,-118.398403

Note the results:

```js
{
	distance_table: [
		[
			0,
			13609,
			2147483647,
			4615,
			15862,
			15706
		],
		[
			13703,
			0,
			2147483647,
			9561,
			3561,
			2304
		],
		[
			15917,
			4862,
			0,
			11771,
			3602,
			4031
		],
		[
			4684,
			9545,
			2147483647,
			0,
			11798,
			11642
		],
		[
			16020,
			3561,
			2147483647,
			11878,
			0,
			2966
		],
		[
			15800,
			2304,
			2147483647,
			11653,
			2966,
			0
		]
	]
}
```

Note how routes calculated to ```34.1360331,-118.352791``` return 2147483647, however all routes from that point are OK. 

I know the coordinates may be a bit off (nearest street segment for this coordinate is http://router.project-osrm.org/locate?loc=34.1369016,-118.3560596 :  ```mapped_coordinate: [ 34.136791, -118.356354 ],status: 0 }``` however it is odd to receive these results. If address is off I should receive:

```js
{
	distance_table: [
		[
			0,
			13609,
			2147483647,
			4615,
			15862,
			15706
		],
		[
			13703,
			0,
			2147483647,
			9561,
			3561,
			2304
		],
		[
			2147483647,
			2147483647,
			0,
			2147483647,
			2147483647,
			2147483647
		],
		[
			4684,
			9545,
			2147483647,
			0,
			11798,
			11642
		],
		[
			16020,
			3561,
			2147483647,
			11878,
			0,
			2966
		],
		[
			15800,
			2304,
			2147483647,
			11653,
			2966,
			0
		]
	]
}
```

**Comment by TheMarex** [comment] 2015-08-14 21:44
The problem is that it finds a way in the one directions but not in the other one. You can see [here](http://map.project-osrm.org/?hl=en&loc=34.135603,-118.357065&loc=34.135905,-118.352655&z=18&center=34.135847,-118.355171&alt=0&df=0&re=0&ly=-1171809665) that it does not find routes outgoing from the given coordinate. The cause of this is a difference in snapping behavior if you reverse source and target.

OSRM takes some best guess as to which roads it should snap to - and sometimes fails. The only good fix for problems like this have been making sure your coordinates are actually located near the streets you want to route on. General POI data (usually the centroid of buildings)  is rarely good for this.

**Comment by TheMarex** [comment] 2015-08-29 10:22
No next actions here. Closing.

**Closed by TheMarex** 2015-08-29 10:22 UTC
