### ISSUE TITLE
Get OSM_IDs Along Route

### ISSUE THREAD

**Issue by sbryfcz** [Project-OSRM/osrm-backend#2138] opened 2016-03-23 20:50 UTC
Is it possible to get the OSM_IDs for the points/roads along a route? I'd love to be able to get a route and then enrich that data with more OSM tags. Does anyone have advice on good approaches for this type of functionality?

Thanks for the incredible application.

**Comment by danpat** [comment] 2016-03-23 20:53
@sbryfcz At this stage, no, but we've been thinking about it.

Duplicate of https://github.com/Project-OSRM/osrm-backend/issues/2054, which has a few more details on the implications (it'll increase memory usage).

**Closed by danpat** 2016-03-23 20:53 UTC

**Comment by sbryfcz** [comment] 2016-03-23 20:57
Ah. Sorry. I couldn't find it when I searched. This is a perfect answer.

Just my 2 cents. Maybe, it would be nice to have an optional flag to include that data. I (personally) don't need to include the entire world. So a (relatively) little bit of extra space/memory is ok (for my project).

If I'm feeling extra ambitious, maybe I'll start peaking through the actual code.

Thanks again for the great work.

**Comment by systemed** [comment] 2016-03-24 13:14
In theory you can access the way ID from your Lua profile (with `way:id()`) and then encode it into `result.name`, so that it's returned as part of the output JSON. There does seem to be some flakiness around it, though (see #1375).

**Comment by amolskh** [comment] 2018-09-09 18:17
Can you elaborate how to do it?
