### ISSUE TITLE
Need on the fly filtering functionality

### ISSUE THREAD

**Issue by boooch** [Project-OSRM/osrm-backend#5155] opened 2018-07-30 12:36 UTC
I have case that I cannot resolve without one feature.
I need to pass one or several polygons to API and get route excluding all ways in this polygons. 
For example I need to avoid some vehicles to cross central district of city without special pass.
I think that all ways in OSRM have coordinates and it is not hard to implement filtering by coordinates on the fly. 
I need somebody who can implement this and I'm ready to discuss conditions.
I need this for route and table plugins

**Comment by danpat** [comment] 2018-07-30 14:55
@boooch The way OSRM currently works, this isn't possible.  You can't claim "it is not hard to implement" if you don't understand the implications :-)

One of OSRM's core features are the "acceleration overlays" - routing graphs that are pre-computed (with `osrm-contract`, `osrm-partition`, and `osrm-customzie`).  The acceleration graphs take some time go generate (hours for the OSM planet), but enable OSRM's very fast queries.

If you make changes to the base road network, like changing road speeds, removing roads, etc - the acceleration overlays need to be re-computed.  This cannot be done on a per-query basis with the current code - each query would take hours.

@TheMarex has an experimental branch over at https://github.com/Project-OSRM/osrm-backend/tree/algorihm/astar where he was toying with what it would look like to run the un-accelerated A* algorithm over OSRM's base graph.  Using this, you could implement the filtering you describe.

The downside is that queries would be significantly slower, as they would not be able to use the acceleration overlays.  This would be painfully obvious for the `/table` plugin.

**Comment by boooch** [comment] 2018-07-31 08:53
Sorry for "it is not hard to implement" :-) but i mean that it is not harder than make atom bomb :-)
 Im not inside your code but I know graphs theory. 
May be you know some solutions differ from OSRM what can implement this feature?

**Comment by danpat** [comment] 2018-07-31 13:30
I do not know of an open-source routing engine that has the feature you need - including an "exclude zone" polygon as part fo the request.

You might want to take a look at https://pgrouting.org/ - I think it should be possible to use some of the PostGIS functions (like `ST_Within`) to flag edges to add additional cost to, as part of a routing query (maybe creating a temporary view of the edges table).

**Comment by boooch** [comment] 2018-07-31 15:14
Seems I found solution openrouteservice.org but not in Matrix function . :-)
![Uploading image.png…]()

**Comment by danpat** [comment] 2018-07-31 16:05
There you go :-)

I want to leave this ticket open in case someone gets motivated to implement something like this, but I suspect it won't happen in OSRM any time soon.

**Comment by boooch** [comment] 2018-07-31 19:37
ОК. Waiting for HERO :-)

**Comment by chaupow** [comment] 2018-09-28 21:30
I found a duplicate of this one: https://github.com/Project-OSRM/osrm-backend/issues/892 (we've been waiting for hero since 2014, it seems 😁).
Closing this one to have fewer issues open...

**Closed by chaupow** 2018-09-28 21:30 UTC
Labels: Feature Request
