### ISSUE TITLE
OSM: "Couldn't find a route between those two places."

### ISSUE THREAD

**Issue by bentolor** [Project-OSRM/osrm-backend#6237] opened 2022-04-27 11:54 UTC
Hi project OSRM,

not sure if this is the right place and if you are actually interested in, but I have an example where routing does not work using OSRM but works for Grashopper on OSM. It returns ""Couldn't find a route between those two places." instead and I assume this is located in the OSRM backend.

Any routing to  "73277 Owen" (Germany) seems to lead to this error.:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.1371%2C11.5754%3B48.5854%2C9.4515

Please close/mark invalid according to you project needs & standards.

Thanks for providing a FOSS alternative in the routing domain!

**Comment by jcoupey** [comment] 2022-04-27 12:05
The demo server used under the hood by openstreetmap.org is currently down. Closing as duplicate of #6236.

**Closed by jcoupey** 2022-04-27 12:05 UTC
