### ISSUE TITLE
CMake error 'TBB Not Found' in Ubuntu 22.04 

### ISSUE THREAD

**Issue by toton6868** [Project-OSRM/osrm-backend#6264] opened 2022-06-18 09:02 UTC
`CMake` returns `TBB Not Found` in Ubuntu 22.04 

```
ERROR: Intel TBB NOT found!
-- Looked for Threading Building Blocks in /usr
CMake Error at cmake/FindTBB.cmake:274 (message):
  Could NOT find TBB library.
Call Stack (most recent call first):
  CMakeLists.txt:533 (find_package)

-- Configuring incomplete, errors occurred!
```
<img width="485" alt="CleanShot 2022-06-18 at 14 57 24@2x" src="https://user-images.githubusercontent.com/1884539/174430716-0d254750-9467-4555-81d8-ecec53df4f22.png">

**Comment by systemed** [comment] 2022-06-18 13:39
This is a duplicate of #6248 and #6253. Building with `cmake -DENABLE_MASON=ON` will fix it.

**Closed** 2022-06-18 13:39 UTC
