### ISSUE TITLE
Add edge weights to tile service

### ISSUE THREAD

**Issue by Nate-Wessel** [Project-OSRM/osrm-backend#4135] opened 2017-06-07 13:21 UTC
Now that edge weights are [separate](https://www.openstreetmap.org/user/happygo/diary/40564) from speeds, it seems like the [tile service](http://project-osrm.org/docs/v5.6.0/api/#tile-service) should also return edge weights along with speeds if it is to be useful for debugging, etc. 

I would like to be able to use the tile service to verify that I am correctly applying weights (independent from speeds) in a profile I'm developing.

**Comment by daniel-j-h** [comment] 2017-06-07 13:45
Weight should be in the returned vector tiles already - the debug tile viewer just needs to visualize them

https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/debug/index.html

I think https://github.com/danpat/osrm-tile-viewer is upstream for the viewer?

@danpat can you chime in here.

**Comment by Nate-Wessel** [comment] 2017-06-07 14:11
If it is included in the tiles already, the tile service docs should be updated as well.

**Comment by danpat** [comment] 2017-06-07 14:26
Duplicate of of https://github.com/Project-OSRM/osrm-backend/issues/4018 and https://github.com/Project-OSRM/osrm-backend/issues/3793

**Closed by danpat** 2017-06-07 14:26 UTC
Labels: Feature Request
