### ISSUE TITLE
Move thresholds / heuristics depending on profiles out of the code into profiles

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2746] opened 2016-08-05 12:47 UTC
We just merged https://github.com/Project-OSRM/osrm-backend/pull/2738 with a threshold of 3 meter. For all profiles.

Move this and similar guidance thresholds / heuristics into the profile (`ProfileProperties`, data facades, pass through into guidance code in the api).

**Comment by MoKob** [comment] 2016-08-08 10:29
Closing as duplicate of https://github.com/Project-OSRM/osrm-backend/issues/2113

**Closed by MoKob** 2016-08-08 10:29 UTC
Labels: Guidance
