### ISSUE TITLE
On Master: invalid maneuvers in responses (crashing demo server)

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4100] opened 2017-05-29 14:21 UTC
The demo server currently sees hundreds of assertions per minute

```
[assert][140005675415296] /mnt/ebs/osrm/2017-05-26-173001/src/engine/api/json_factory.cpp:186
in: osrm::util::json::Object osrm::engine::api::json::makeStepManeuver(const osrm::engine::guidance::StepManeuver&): maneuver_type != "invalid"
unexpected invalid maneuver type
```

Maybe related to
- https://github.com/Project-OSRM/osrm-backend/pull/4077
- https://github.com/Project-OSRM/osrm-backend/pull/4073
- https://github.com/Project-OSRM/osrm-backend/issues/4030

**Comment by daniel-j-h** [comment] 2017-05-29 14:23
Flagging: some of those commits are in the `5.7` branch. Not sure yet if we're affected though.

cc @TheMarex @oxidase

**Comment by TheMarex** [comment] 2017-05-29 18:24
The above request works fine on `5.7`:

```json
{"code":"Ok","routes":[{"geometry":"t{kVlawdE??","legs":[{"steps":[{"intersections":[{"out":0,"entry":[true],"bearings":[0],"location":[-32.399748,-3.834354]}],"geometry":"t{kVlawdE??","mode":"driving","duration":0,"maneuver":{"bearing_after":0,"location":[-32.399748,-3.834354],"bearing_before":0,"type":"depart"},"ref":"BR-363","weight":0,"distance":0,"name":""},{"intersections":[{"in":0,"entry":[true],"bearings":[180],"location":[-32.399748,-3.834354]}],"geometry":"t{kVlawdE","mode":"driving","duration":0,"maneuver":{"bearing_after":0,"location":[-32.399748,-3.834354],"bearing_before":0,"type":"arrive"},"ref":"BR-363","weight":0,"distance":0,"name":""}],"distance":0,"duration":0,"summary":"","weight":0}],"distance":0,"duration":0,"weight_name":"routability","weight":0}],"waypoints":[{"hint":"lDsDgP___3-YKgEAAAAAAAIAAAA_AAAAAAAAAAAAAAACAAAAPwAAAAAAAAAskgIADQoAgHyeEf4OfsX_ybfLASAPkQMEABEPEfo_GA==","name":"","location":[-32.399748,-3.834354]},{"hint":"lDsDgP___3-YKgEAAAAAAAIAAAA_AAAAAAAAAAAAAAACAAAAPwAAAAAAAAAskgIADQoAgHyeEf4OfsX__jvMAcPNjAMEABEPEfo_GA==","name":"","location":[-32.399748,-3.834354]}]}
```

**Comment by oxidase** [comment] 2017-05-30 09:16
The issue is a regression in 47f2f1798

Steps to reproduce locally:
```
osmium extract -b -46.18309,-21.819433,-45.720978,-21.286175 brazil-latest.osm.pbf -o map.osm.pbf && ./osrm-extract -p ../profiles/car.lua map.osm.pbf && ./osrm-contract map.osrm && ./osrm-routed map.osrm
curl 'localhost:5000/route/v1/driving/-45.901913,-21.695328;-45.946967,-21.429502?alternatives=true&steps=true'
```

**Comment by oxidase** [comment] 2017-05-30 11:20
The problem is in [`postProcess`](https://github.com/Project-OSRM/osrm-backend/blob/45ee096260ba18b4402c76565b69a396be34ecde/src/engine/guidance/post_processing.cpp#L247):

* for `localhost:5000/route/v1/driving/-45.943141,-22.204016;-45.946967,-21.429502?steps=true`    `postProcess` changes two `EnterAndExitRoundabout` instructions (green and red in https://gist.github.com/oxidase/58213eea23929a27a50b70004c112937) into two `EnterRoundabout`, so `collapseTurnInstructions` [ignores](https://github.com/Project-OSRM/osrm-backend/blob/45ee096260ba18b4402c76565b69a396be34ecde/src/engine/guidance/collapse_turns.cpp#L315-L328) the rest of instructions 

* for `localhost:5000/route/v1/driving/-45.901913,-21.695328;-45.946967,-21.429502?steps=true` there is only one `EnterAndExitRoundabout` (the route starts  inside the roundabout) instruction that is also changed to one `EnterRoundabout` 

/cc @daniel-j-h @MoKob

**Comment by oxidase** [comment] 2017-06-01 09:18
Closing via #4108, demo server is rebased to d262c4dfaa11893c8322b3fcc67338f68f3a467e

**Closed by oxidase** 2017-06-01 09:18 UTC
Labels: Bug Report
