### ISSUE TITLE
Navigation Error

### ISSUE THREAD

**Issue by michaelschefczyk** [Project-OSRM/osrm-backend#3195] opened 2016-10-27 20:49 UTC
Dear All,

Using the public frontend (as well as other implementations), navigation seems to have recently started to fail. Upon entering startpoint and endpoint, there is always an additional waypoint on the Arizona / California state line in the middle.

Regards,

Michael Schefczyk

**Comment by daniel-j-h** [comment] 2016-10-27 21:11
Closing as duplicate of https://github.com/Project-OSRM/osrm-backend/issues/3186#issuecomment-256535566.

tl;dr only CA until the demo server re-processes the latest planet with the latest osrm nightly builds:

http://map.project-osrm.org/?z=7&center=38.406254%2C-115.191650&loc=37.020098%2C-112.840576&loc=43.221190%2C-118.410645&hl=en&alt=0

**Closed by daniel-j-h** 2016-10-27 21:11 UTC
