### ISSUE TITLE
Conditional restrictions

### ISSUE THREAD

**Issue by mzervens** [Project-OSRM/osrm-backend#5263] opened 2018-11-07 12:57 UTC
I am using OSRM version 5.18.0

It is installed on Ubuntu 16.04.4 LTS 

Using the default lua car profile when extracting data: https://github.com/Project-OSRM/osrm-backend/tree/master/profiles

Using osm file exported from this extent: https://www.openstreetmap.org/#map=17/56.96268/24.13877

Used timezone file taken from http://efele.net/maps/tz/world/tz_world.zip
The shapefile converted to geojson file and also overwriting the attribute name TZID to tzid since OSRM doesnt understand if the name is in capital case

The used tool chain of actions is this:

osrm-extract osmm.osm --profile /home/test/turndebug/profiles/car.lua --parse-conditional-restrictions

osrm-partition osmm.osrm

osrm-customize osmm.osrm --parse-conditionals-from-now 1541593864 --time-zone-file /home/test/turndebug/tz.geojson

 osrm-routed osmm.osrm --algorithm=MLD

My problem is that conditional turn restrictions are not working (there are no restrictions where conditional restrictions are)

If the same tool chain is used but without the --parse-conditional-restrictions flag:
osrm-extract osmm.osm --profile /home/test/turndebug/profiles/car.lua 

Then the conditional turn restrictions become regular turn restrictions and they are always present even if you modify the hours on/off to different time period.

Here is example of conditional restriction that isnt working: https://www.openstreetmap.org/relation/1732577#map=17/56.96268/24.13877

Also when checking this restriction in the openstreetmap.org routing the routing for OSRM doesnt seem to be working there aswell.... but running with GraphHopper it is taken into account.

Can somebody suggest where the problem is?

**Comment by mzervens** [comment] 2018-11-08 07:33
@oxidase noticed that you have helped others with issues related to timed conditional problems, maybe you have an idea what im missing? Have been trying to get this working for a while now with no success

**Comment by asaveljevs** [comment] 2019-10-30 16:33
This issue seems to be a duplicate of #5093. Maybe we could keep our discussion there, so that it is in one place only?

**Closed** 2019-10-30 18:43 UTC
