### ISSUE TITLE
Exposing More Infos in viaroute Service

### ISSUE THREAD

**Issue by programmer-art** [Project-OSRM/osrm-backend#1619] opened 2015-08-20 15:42 UTC
As a reference, I would like to show a Google Maps scenario:

![google2](https://cloud.githubusercontent.com/assets/13054704/9387720/30f141de-4762-11e5-9448-fd9e953b511f.png)

In the image, you can see that GM is exposing additional information like when crossing a street, so that it informs the user of being required to cross the street.

OSRM does not expose this kind of information in the viaroute service.
![pic1](https://cloud.githubusercontent.com/assets/13054704/9366592/94d6f6ee-46b8-11e5-9331-ac8e6cfc6f0a.png)

Is it somehow possible to access this kind of information with additional OSRM queries?

It is also related to #1615

**Comment by TheMarex** [comment] 2015-08-21 10:23
No, sadly it is not easily accessible. Closing here - duplicate of #1615.

**Closed by TheMarex** 2015-08-21 10:23 UTC
