### ISSUE TITLE
Today the OSRM have some problems to display the routes... Regards...

### ISSUE THREAD

**Issue by CusProjects** [Project-OSRM/osrm-backend#2439] opened 2016-05-20 20:30 UTC
IT Throws 500 Internal Server Error

GET /route/v1/driving/11.94,57.74;11.949,57.6792?alternatives=true&steps=true HTTP/1.1
Host: router.project-osrm.org
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:8080/
Origin: http://127.0.0.1:8080
Connection: keep-alive

**Comment by oxidase** [comment] 2016-05-21 00:28
It could be a duplicate of #2413 that must be fixed by #2419. gcc build is not crashing, but  windows build crashes with the call stack
```
    osrm-routed.exe!osrm::engine::routing_algorithms::BasicRoutingInterface<osrm::engine::datafacade::BaseDataFacade,osrm::engine::routing_algorithms::AlternativeRouting<osrm::engine::datafacade::BaseDataFacade> >::UnpackPath<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > > >(std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > > packed_path_begin, std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > > packed_path_end, const osrm::engine::PhantomNodes & phantom_node_pair, std::vector<osrm::engine::PathData,std::allocator<osrm::engine::PathData> > & unpacked_path) Line 325    C++
     osrm-routed.exe!osrm::engine::routing_algorithms::AlternativeRouting<osrm::engine::datafacade::BaseDataFacade>::operator()(const osrm::engine::PhantomNodes & phantom_node_pair, osrm::engine::InternalRouteResult & raw_route_data) Line 332    C++
     osrm-routed.exe!osrm::engine::plugins::ViaRoutePlugin::HandleRequest(const osrm::engine::api::RouteParameters & route_parameters, osrm::util::json::Object & json_result) Line 91    C++
     osrm-routed.exe!`anonymous namespace'::RunQuery<osrm::engine::api::RouteParameters,osrm::engine::plugins::ViaRoutePlugin,osrm::util::json::Object>(const std::unique_ptr<osrm::engine::Engine::EngineLock,std::default_delete<osrm::engine::Engine::EngineLock> > & lock, osrm::engine::datafacade::BaseDataFacade & facade, const osrm::engine::api::RouteParameters & parameters, osrm::engine::plugins::ViaRoutePlugin & plugin, osrm::util::json::Object & result) Line 96    C++
     osrm-routed.exe!osrm::engine::Engine::Route(const osrm::engine::api::RouteParameters & params, osrm::util::json::Object & result) Line 162    C++
     osrm-routed.exe!osrm::server::service::RouteService::RunQuery(unsigned __int64 prefix_length, std::basic_string<char,std::char_traits<char>,std::allocator<char> > & query, mapbox::util::variant<osrm::util::json::Object,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > & result) Line 65    C++
     osrm-routed.exe!osrm::server::ServiceHandler::RunQuery(osrm::server::api::ParsedURL parsed_url, mapbox::util::variant<osrm::util::json::Object,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > & result) Line 51    C++
     osrm-routed.exe!osrm::server::RequestHandler::HandleRequest(const osrm::server::http::request & current_request, osrm::server::http::reply & current_reply) Line 89    C++

```
With 200c53c windows build is not crashing.

**Comment by TheMarex** [comment] 2016-05-26 21:19
@CusProjects can you confirm this is working now?

**Comment by CusProjects** [comment] 2016-05-26 21:27
It's Work tanks... 

Regards.

**Closed** 2016-05-26 21:30 UTC
