### ISSUE TITLE
routing not optimal

### ISSUE THREAD

**Issue by huntw999** [Project-OSRM/osrm-backend#3366] opened 2016-11-25 22:43 UTC
i am using version 4 and i want to do a route similar to  Traveling Salesman Problem where you need to have the start and finish points fixed and the stops in between optimized without a fixed order - eg 5 stops beginning and end fixed and the 3 in the middle osrm will optimize by choosing the order for best overall trip 

i also need to have the above functionality with the start being the finish - 5 stops with only the start fixed as start and finish attribute

this was fixed in 4 and i assume it is working in 5

all this was addressed in -> issue #1704
Shortest path through specified points (that are unordered) #1704

can i get an update on the api call and status of this

any help is greatly appreciated

bh

**Comment by daniel-j-h** [comment] 2016-11-28 08:46
Closing as duplicate of:

- https://github.com/Project-OSRM/osrm-backend/issues/1623 <- the feature you want
- https://github.com/Project-OSRM/osrm-backend/issues/1644 <- similar issue

Setting a fixed start and end is not supported at the moment.

Maybe @chaupow has more details here.

**Closed by daniel-j-h** 2016-11-28 08:46 UTC
