### ISSUE TITLE
Separate destination and destination:ref

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#4447] opened 2017-08-27 23:58 UTC
Right now, we combine `destination` and `destination:ref` (and maybe more?) into a single `destination` fields. We are loosing the fidelity around which is which. Can we retain that by adding a separate `destination:ref` field?

/cc @miccolis

**Comment by daniel-j-h** [comment] 2017-08-28 10:15
Closing as duplicate of
- https://github.com/Project-OSRM/osrm-backend/issues/3304
- https://github.com/Project-OSRM/osrm-backend/issues/3329

**Closed by daniel-j-h** 2017-08-28 10:15 UTC
