### ISSUE TITLE
steps=true crashing osrm-routed (Oct 18 windows build)

### ISSUE THREAD

**Issue by peterdn1** [Project-OSRM/osrm-backend#3171] opened 2016-10-25 18:26 UTC
Requesting steps=true for some lats & lons causes osrm-routed fails windows build. (Oct 18 build)  Most lats/lons are working.

Data:
http://download.geofabrik.de/north-america/us/pennsylvania.html

http://127.0.0.1:5000/route/v1/driving/-75.28987884521484,39.92603302001953;-75.41616,39.9469528?alternatives=false&geometries=geojson
Success:
{"waypoints":[{"location":[-75.28998,39.926074],"name":"West Maryland Avenue","hint":"YmYPgMckEIAsigQAFAAAAEsAAAAAAAAAFgIAAKJ9CACGAQAAhCqD-zo5YQLqKoP7ETlhAgAAAQGEm1Qa"},{"location":[-75.416262,39.947156],"name":"North Feathering Lane","hint":"NoEPgIK9D4B0WAQAGgAAAHEAAAAAAAAAAAAAAKWUCACGAQAAOj2B-5SLYQKgPYH7yIphAgAAAQGEm1Qa"}],"routes":[{"distance":12351.2,"duration":785.6,"legs":[{"distance":12351.2,"duration":785.6,"summary":"","steps":[]}],"geometry":{"type":"LineString","coordinates":[[-75.28998,39.926074],[-75.300182,39.930426],[-75.315537,39.930236],[-75.322438,39.930782],[-75.326154,39.931875],[-75.330195,39.934585],[-75.339089,39.934237],[-75.340805,39.935354],[-75.344667,39.939825],[-75.355161,39.93725],[-75.361487,39.937447],[-75.367831,39.936556],[-75.391732,39.93644],[-75.399364,39.945354],[-75.40608,39.946487],[-75.410501,39.948485],[-75.413477,39.948777],[-75.414555,39.949505],[-75.415616,39.948892],[-75.415189,39.947474],[-75.416262,39.947156]]}}],"code":"Ok"}
Fails:

http://127.0.0.1:5000/route/v1/driving/-75.28987884521484,39.92603302001953;-75.41616,39.9469528?alternatives=false&geometries=geojson&steps=true

osrm-routed.exe has stopped working

A problem caused the program to stop working correctly.  Windows will close the program and notify you if a solution is available.

An unhandled win32 exception occurred in osrm-routed.exe [15004].

**Comment by daniel-j-h** [comment] 2016-10-25 18:37
Interestingly both queries work on the demo server (running master):

http://router.project-osrm.org/route/v1/driving/-75.28987884521484,39.92603302001953;-75.41616,39.9469528?alternatives=false&geometries=geojson

http://router.project-osrm.org/route/v1/driving/-75.28987884521484,39.92603302001953;-75.41616,39.9469528?alternatives=false&geometries=geojson&steps=true

I can remember someone reporting the exact same issue re. `steps=true` though - can't find it at the moment.

**Comment by MoKob** [comment] 2016-10-26 21:48
Do you have an exact commit? I've tried both with master and with the latest commit from Oct 18th. So far I cannot reproduce this error.

Closing here, but feel free to re-open if you should still see the same error on current versions.

**Closed by MoKob** 2016-10-26 21:48 UTC
Labels: Bug Report, Guidance

**Comment by peterdn1** [comment] 2016-10-26 22:38
Moritz,

You are testing the windows build?
http://build.project-osrm.org/latest/osrm_Release.zip (Oct 18th release).

Regards,
Peter

**Comment by MoKob** [comment] 2016-10-27 00:02
I am talking about the specific git commit. On Oct 18th there have been a series of commits. Can you tell us if current master still shows this problem (there have been a few fixes in between).

Sadly, none of our developers is running a windows machine.
