### ISSUE TITLE
Multiple routing profile in one data file

### ISSUE THREAD

**Issue by homersimpsons** [Project-OSRM/osrm-backend#2791] opened 2016-08-19 21:45 UTC
Hello, 

There is a request https://github.com/mapsme/omim/issues/1888 in maps.me to add an option to avoid toll. But as it's a smartphone software, they care about map size. Then they can't add this profile. 

Is it possible to extend routing data configuration to support multiple routing. This is to avoid one routing data per profile. 

I know that this is not the base idea (which was we 'basicaly' search for lowest penalty between two nodes to get the fastest route for this profile) maybe data file can describe more profile just by supporting boolean value (here is it for toll, but it could be heigh preference or to avoid trunk). The different profile should be penalty compatible but can get roads restrictions.

**Comment by danpat** [comment] 2016-08-19 21:55
@homersimpsons Because of the [Contraction Hierarchy](https://en.wikipedia.org/wiki/Contraction_hierarchies) graph structure that OSRM uses, it is non-trivial to support query-time options like "avoid tolls" or "avoid ferries".

For a more detailed discussion, see: https://github.com/Project-OSRM/osrm-backend/issues/2377

**Comment by frodrigo** [comment] 2016-08-20 15:37
Also look at #10

**Comment by homersimpsons** [comment] 2016-08-21 21:34
First of all, in profile you need to include different condition to take care (boolean toll, float height, float weight etc.)
This condition can be evaluated and only return a boolean.

**Comment by homersimpsons** [comment] 2016-08-22 14:58
For toll road, we can consider that a road is paid or not, then maybe is it possible to consider paid road as a subgraph. 
Then do two different Contraction for paid road and free ones

**Comment by daniel-j-h** [comment] 2016-09-02 14:34
Closing here as duplicate of the issues linked above. CH does not support dynamic query time flags e.g. for tolls, ferries and so on. What you can do is create multiple profiles run OSRM on each of them. This will create multiple *.osrm.* datasets. Feel free to zip them up and ship them.

**Closed by daniel-j-h** 2016-09-02 14:34 UTC

**Comment by MoKob** [comment] 2016-09-02 15:49
@danpat I would even do the daily ones. As long as you add half a day penalty and warn the user about it (e.g. check your timetables please), you would not separate the graph into components but prefer roads that are not using these ways.
