### ISSUE TITLE
Use exit_to tags in place of empty destination values

### ISSUE THREAD

**Issue by bsudekum** [Project-OSRM/osrm-backend#3317] opened 2016-11-15 17:41 UTC
Highway navigation is difficult where there is no name given in the instruction. In places where we're not returning a `name`, `destination` or `ref`, we can use `exit_to` tags in place of an empty destination value. 

Per conversation with @daniel-j-h, we could add a osmium handler that re-writes the exit_to tags to destination. This would be a separate pass of the planet, would be slow and add significant time to extraction. 

Open to other ideas on how to solve the issue.

/cc @MoKob @danpat @oxidase @willwhite

**Comment by emiltin** [comment] 2016-11-15 18:46
i might be missing something, but why can't this just be handled in the lua profile code, like the name, ref and destination tags?

**Comment by danpat** [comment] 2016-11-15 19:13
The problem is that `exit_to` goes on nodes: http://wiki.openstreetmap.org/wiki/Key:exit_to

Two things would need to happen to support it:

  1. store the `exit_to` value for nodes that have it
  2. after we construct the node-based-graph, explore nodes with `exit_to` values, figure out which outgoing edge is the actual exit (using a heuristic), and copy the value to the `destination` field on the outgoing edge.

**Comment by emiltin** [comment] 2016-11-15 19:35
i see

**Comment by TheMarex** [comment] 2016-11-17 23:30
Could we explore (half-)automated ways to fix this in the data? Even the [wiki page](http://wiki.openstreetmap.org/wiki/Key:exit_to) already tries to convince you to not use it anymore.

This seems like a better long-term appraoch then trying to add support in the OSRM pre-processing, which is rather challenging and costly (and would only solve this mapping problem for one OSM consumer, which is OSRM).

**Comment by daniel-j-h** [comment] 2016-12-14 17:26
Just spent some hours playing with `libosmium` builder and writer:
this is the half-automated way you were talking about:

https://github.com/mapbox/rewrite-exit-destination-signage

It's re-writing `exit_to=` node tags to `destination=` way tags and it's fairly conservative about it. For example it only writes the way tag when it's a `_link`, when it's tagged as oneway (possibly reversible), and there is not already a destination tag.

**Comment by daniel-j-h** [comment] 2017-01-02 11:20
Closing as data issue. Use

https://github.com/mapbox/rewrite-exit-destination-signage

as a pre-processor if needs be.

**Closed by daniel-j-h** 2017-01-02 11:20 UTC
Labels: Discussion, Guidance
