### ISSUE TITLE
Lua 5.2 exact required?

### ISSUE THREAD

**Issue by peter-evans** [Project-OSRM/osrm-backend#4525] opened 2017-09-20 03:02 UTC
While testing the latest [v5.13.0-cardinal.1](https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.13.0-cardinal.1) release I got the following error.
```
-- Could NOT find Lua: Found unsuitable version "5.2.3", but required is exact version "5.2" (found /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so)
CMake Error at CMakeLists.txt:524 (MESSAGE):
  Lua 5.2 was not found.
```
It seems that due to [this commit](https://github.com/Project-OSRM/osrm-backend/commit/f4f65f62ee460e148356f7d0f5af931c8cfc4630#diff-af3b638bc2a3e6c650974192a53c7291) Lua 5.2 exact is required. Is this intentional?

**Comment by danpat** [comment] 2017-09-20 03:48
@peter-evans yes, this was intentional, but these are beta releases, so this is not intended to be a final decision.

Some of the Lua interface code is significantly simpler under Lua 5.2, we couldn't see a compelling reason to keep the extra overhead around to maintain Lua 5.1 support - do you have a use-case that requires Lua 5.1, or is an update to 5.2 feasible for you?

**Comment by peter-evans** [comment] 2017-09-20 04:14
@danpat Sorry, I should have been a bit clearer about the issue. This is not related to support for 5.1 but about how a recent commit to CMakeLists.txt enforces Lua 5.2 **exact**.

Before [this commit](https://github.com/Project-OSRM/osrm-backend/commit/f4f65f62ee460e148356f7d0f5af931c8cfc4630#diff-af3b638bc2a3e6c650974192a53c7291) any minor version of Lua 5.2 could be used. e.g. 5.2.3
```
FIND_PACKAGE(Lua 5.2)
IF (LUA_FOUND)
    MESSAGE(STATUS "Using Lua ${LUA_VERSION_STRING}")
```
After the commit the `EXACT` keyword seems to enforce Lua 5.2(.0) to be present.
```
FIND_PACKAGE(Lua 5.2 EXACT)
IF (LUA_FOUND)
    MESSAGE(STATUS "Using Lua ${LUA_VERSION_STRING}")
```

I understand this is a beta release and not final. This is just testing to check for possible issues.

**Comment by oxidase** [comment] 2017-09-20 04:41
@peter-evans the problem is not with Lua but with cmake. The cmake version 3 correctly handles `EXACT` version checks without patch numbers.

On OSRM side we can:
- bump required cmake version to 3 as `cmake_minimum_required(VERSION 3.0)`
- drop `EXACT` and check `5.2(,?)` Lua version in `CMakeLists.txt`

**Comment by peter-evans** [comment] 2017-09-20 07:12
@oxidase That explains why the Ubuntu Xenial build worked but Trusty did not. Trusty's version of cmake is 2.8.12.

I've tested bumping cmake to 3.x on Trusty and it works fine. So for the two options you have outlined on the OSRM side, enforcing version 3 or dropping `EXACT`, either way works for me.

Thanks for your help.

**Comment by daniel-j-h** [comment] 2017-09-27 23:01
With https://github.com/Project-OSRM/osrm-backend/pull/4526 merged @peter-evans could you try and see if this fixes your issue?

**Comment by peter-evans** [comment] 2017-09-28 02:48
@daniel-j-h The issue is fixed on Trusty and it builds fine without needing to bump cmake to 3.x. Thank you!

**Closed** 2017-09-28 02:49 UTC
