### ISSUE TITLE
Unable to find a route that crosses anti-meridian

### ISSUE THREAD

**Issue by roman-lgx** [Project-OSRM/osrm-backend#4308] opened 2017-07-19 13:54 UTC
How do you handle routes that cross anti-merdian (i.e. -180 longitude)?

curl 'http://router.project-osrm.org/route/v1/driving/-180.0343,68.9594;179.9519,68.9532?overview=false'
{"message":"Invalid coordinate value.","code":"InvalidValue"}

curl 'http://router.project-osrm.org/route/v1/driving/-180.0343,68.9594;-179.9519,68.9532?overview=false'
{"message":"Invalid coordinate value.","code":"InvalidValue"}

curl 'http://router.project-osrm.org/route/v1/driving/179.9657,68.9594;-179.9519,68.9532?overview=false'
{"message":"Impossible route between points","code":"NoRoute"}

curl 'http://router.project-osrm.org/route/v1/driving/-180.0343,68.9594;-179.9519,68.9532'
{"message":"Invalid coordinate value.","code":"InvalidValue"}

Btw, if you put 179.x value that corresponds to the -180.x values above it still won't find the route.

**Comment by daniel-j-h** [comment] 2017-07-20 09:43
Closing as a duplicate of: https://github.com/Project-OSRM/osrm-backend/issues/1188.

Could you keep the discussion there please 🙇

**Closed by daniel-j-h** 2017-07-20 09:43 UTC
