### ISSUE TITLE
Build fails with master branch on Ubuntu 22.04

### ISSUE THREAD

**Issue by dpbnasika** [Project-OSRM/osrm-backend#7077] opened 2024-11-24 22:20 UTC
### Discussed in https://github.com/Project-OSRM/osrm-backend/discussions/7076

<div type='discussions-op-text'>

<sup>Originally posted by **dpbnasika** November 24, 2024</sup>
Hi i treid to build the src of the master branch repo on ubuntu 22.04, the build is failing, is the rpository upto date?, or does anyone have this build issues?.

Configuring in: /home/dp-dev/git/osrm-backend/build/default

cmake -G Unix Makefiles -DCMAKE_EXPORT_COMPILE_COMMANDS=ON /home/dp-dev/git/osrm-backend
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building on a 64 bit system
-- No build type specified, defaulting to Release
-- Configuring OSRM in release mode
-- Performing Test SUPPORTS_CXXFLAG_all
-- Performing Test SUPPORTS_CXXFLAG_all - Success
-- Performing Test SUPPORTS_CFLAG_all
-- Performing Test SUPPORTS_CFLAG_all - Success
-- Performing Test SUPPORTS_CXXFLAG_extra
-- Performing Test SUPPORTS_CXXFLAG_extra - Success
-- Performing Test SUPPORTS_CFLAG_extra
-- Performing Test SUPPORTS_CFLAG_extra - Success
-- Performing Test SUPPORTS_CXXFLAG_pedantic
-- Performing Test SUPPORTS_CXXFLAG_pedantic - Success
-- Performing Test SUPPORTS_CFLAG_pedantic
-- Performing Test SUPPORTS_CFLAG_pedantic - Success
-- Performing Test SUPPORTS_CXXFLAG_error
-- Performing Test SUPPORTS_CXXFLAG_error - Success
-- Performing Test SUPPORTS_CFLAG_error
-- Performing Test SUPPORTS_CFLAG_error - Success
-- Performing Test SUPPORTS_CXXFLAG_strict_overflow=1
-- Performing Test SUPPORTS_CXXFLAG_strict_overflow=1 - Success
-- Performing Test SUPPORTS_CFLAG_strict_overflow=1
-- Performing Test SUPPORTS_CFLAG_strict_overflow=1 - Success
-- Performing Test SUPPORTS_CXXFLAG_suggest_override
-- Performing Test SUPPORTS_CXXFLAG_suggest_override - Success
-- Performing Test SUPPORTS_CFLAG_suggest_override
-- Performing Test SUPPORTS_CFLAG_suggest_override - Failed
-- Flag -Wsuggest-override is unsupported
-- Performing Test SUPPORTS_CXXFLAG_suggest_destructor_override
-- Performing Test SUPPORTS_CXXFLAG_suggest_destructor_override - Failed
-- Performing Test SUPPORTS_CFLAG_suggest_destructor_override
-- Performing Test SUPPORTS_CFLAG_suggest_destructor_override - Failed
-- Flag -Wsuggest-destructor-override is unsupported
-- Flag -Wsuggest-destructor-override is unsupported
-- Performing Test SUPPORTS_CXXFLAG_unused
-- Performing Test SUPPORTS_CXXFLAG_unused - Success
-- Performing Test SUPPORTS_CFLAG_unused
-- Performing Test SUPPORTS_CFLAG_unused - Success
-- Performing Test SUPPORTS_CXXFLAG_unreachable_code
-- Performing Test SUPPORTS_CXXFLAG_unreachable_code - Success
-- Performing Test SUPPORTS_CFLAG_unreachable_code
-- Performing Test SUPPORTS_CFLAG_unreachable_code - Success
-- Performing Test SUPPORTS_CXXFLAG_delete_incomplete
-- Performing Test SUPPORTS_CXXFLAG_delete_incomplete - Success
-- Performing Test SUPPORTS_CFLAG_delete_incomplete
-- Performing Test SUPPORTS_CFLAG_delete_incomplete - Failed
-- Flag -Wdelete-incomplete is unsupported
-- Performing Test SUPPORTS_CXXFLAG_duplicated_cond
-- Performing Test SUPPORTS_CXXFLAG_duplicated_cond - Success
-- Performing Test SUPPORTS_CFLAG_duplicated_cond
-- Performing Test SUPPORTS_CFLAG_duplicated_cond - Success
-- Performing Test SUPPORTS_CXXFLAG_disabled_optimization
-- Performing Test SUPPORTS_CXXFLAG_disabled_optimization - Success
-- Performing Test SUPPORTS_CFLAG_disabled_optimization
-- Performing Test SUPPORTS_CFLAG_disabled_optimization - Success
-- Performing Test SUPPORTS_CXXFLAG_init_self
-- Performing Test SUPPORTS_CXXFLAG_init_self - Success
-- Performing Test SUPPORTS_CFLAG_init_self
-- Performing Test SUPPORTS_CFLAG_init_self - Success
-- Performing Test SUPPORTS_CXXFLAG_bool_compare
-- Performing Test SUPPORTS_CXXFLAG_bool_compare - Success
-- Performing Test SUPPORTS_CFLAG_bool_compare
-- Performing Test SUPPORTS_CFLAG_bool_compare - Success
-- Performing Test SUPPORTS_CXXFLAG_logical_not_parentheses
-- Performing Test SUPPORTS_CXXFLAG_logical_not_parentheses - Success
-- Performing Test SUPPORTS_CFLAG_logical_not_parentheses
-- Performing Test SUPPORTS_CFLAG_logical_not_parentheses - Success
-- Performing Test SUPPORTS_CXXFLAG_logical_op
-- Performing Test SUPPORTS_CXXFLAG_logical_op - Success
-- Performing Test SUPPORTS_CFLAG_logical_op
-- Performing Test SUPPORTS_CFLAG_logical_op - Success
-- Performing Test SUPPORTS_CXXFLAG_misleading_indentation
-- Performing Test SUPPORTS_CXXFLAG_misleading_indentation - Success
-- Performing Test SUPPORTS_CFLAG_misleading_indentation
-- Performing Test SUPPORTS_CFLAG_misleading_indentation - Success
-- Performing Test SUPPORTS_CXXFLAG_no_return_local_addr
-- Performing Test SUPPORTS_CXXFLAG_no_return_local_addr - Success
-- Performing Test SUPPORTS_CFLAG_no_return_local_addr
-- Performing Test SUPPORTS_CFLAG_no_return_local_addr - Success
-- Performing Test SUPPORTS_CXXFLAG_odr
-- Performing Test SUPPORTS_CXXFLAG_odr - Success
-- Performing Test SUPPORTS_CFLAG_odr
-- Performing Test SUPPORTS_CFLAG_odr - Success
-- Performing Test SUPPORTS_CXXFLAG_pointer_arith
-- Performing Test SUPPORTS_CXXFLAG_pointer_arith - Success
-- Performing Test SUPPORTS_CFLAG_pointer_arith
-- Performing Test SUPPORTS_CFLAG_pointer_arith - Success
-- Performing Test SUPPORTS_CXXFLAG_redundant_decls
-- Performing Test SUPPORTS_CXXFLAG_redundant_decls - Success
-- Performing Test SUPPORTS_CFLAG_redundant_decls
-- Performing Test SUPPORTS_CFLAG_redundant_decls - Success
-- Performing Test SUPPORTS_CXXFLAG_reorder
-- Performing Test SUPPORTS_CXXFLAG_reorder - Success
-- Performing Test SUPPORTS_CFLAG_reorder
-- Performing Test SUPPORTS_CFLAG_reorder - Failed
-- Flag -Wreorder is unsupported
-- Performing Test SUPPORTS_CXXFLAG_shift_negative_value
-- Performing Test SUPPORTS_CXXFLAG_shift_negative_value - Success
-- Performing Test SUPPORTS_CFLAG_shift_negative_value
-- Performing Test SUPPORTS_CFLAG_shift_negative_value - Success
-- Performing Test SUPPORTS_CXXFLAG_sizeof_array_argument
-- Performing Test SUPPORTS_CXXFLAG_sizeof_array_argument - Success
-- Performing Test SUPPORTS_CFLAG_sizeof_array_argument
-- Performing Test SUPPORTS_CFLAG_sizeof_array_argument - Success
-- Performing Test SUPPORTS_CXXFLAG_switch_bool
-- Performing Test SUPPORTS_CXXFLAG_switch_bool - Success
-- Performing Test SUPPORTS_CFLAG_switch_bool
-- Performing Test SUPPORTS_CFLAG_switch_bool - Success
-- Performing Test SUPPORTS_CXXFLAG_tautological_compare
-- Performing Test SUPPORTS_CXXFLAG_tautological_compare - Success
-- Performing Test SUPPORTS_CFLAG_tautological_compare
-- Performing Test SUPPORTS_CFLAG_tautological_compare - Success
-- Performing Test SUPPORTS_CXXFLAG_trampolines
-- Performing Test SUPPORTS_CXXFLAG_trampolines - Success
-- Performing Test SUPPORTS_CFLAG_trampolines
-- Performing Test SUPPORTS_CFLAG_trampolines - Success
-- Performing Test SUPPORTS_CXXFLAG_no_deprecated_comma_subscript
-- Performing Test SUPPORTS_CXXFLAG_no_deprecated_comma_subscript - Success
-- Performing Test SUPPORTS_CFLAG_no_deprecated_comma_subscript
-- Performing Test SUPPORTS_CFLAG_no_deprecated_comma_subscript - Success
-- Performing Test SUPPORTS_CXXFLAG_no_comma_subscript
-- Performing Test SUPPORTS_CXXFLAG_no_comma_subscript - Success
-- Performing Test SUPPORTS_CFLAG_no_comma_subscript
-- Performing Test SUPPORTS_CFLAG_no_comma_subscript - Failed
-- Flag -Wno-comma-subscript is unsupported
-- Performing Test SUPPORTS_CXXFLAG_no_ambiguous_reversed_operator
-- Performing Test SUPPORTS_CXXFLAG_no_ambiguous_reversed_operator - Success
-- Performing Test SUPPORTS_CFLAG_no_ambiguous_reversed_operator
-- Performing Test SUPPORTS_CFLAG_no_ambiguous_reversed_operator - Success
-- Performing Test SUPPORTS_CXXFLAG_no_restrict
-- Performing Test SUPPORTS_CXXFLAG_no_restrict - Success
-- Performing Test SUPPORTS_CFLAG_no_restrict
-- Performing Test SUPPORTS_CFLAG_no_restrict - Success
-- Performing Test SUPPORTS_CXXFLAG_no_free_nonheap_object
-- Performing Test SUPPORTS_CXXFLAG_no_free_nonheap_object - Success
-- Performing Test SUPPORTS_CFLAG_no_free_nonheap_object
-- Performing Test SUPPORTS_CFLAG_no_free_nonheap_object - Success
-- Performing Test SUPPORTS_CXXFLAG_no_stringop_overflow
-- Performing Test SUPPORTS_CXXFLAG_no_stringop_overflow - Success
-- Performing Test SUPPORTS_CFLAG_no_stringop_overflow
-- Performing Test SUPPORTS_CFLAG_no_stringop_overflow - Success
-- Performing Test HAS_COLOR_FLAG
-- Performing Test HAS_COLOR_FLAG - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test SUPPORTS_CXXFLAG_no_unused_variable
-- Performing Test SUPPORTS_CXXFLAG_no_unused_variable - Success
-- Performing Test SUPPORTS_CXXFLAG_no_format
-- Performing Test SUPPORTS_CXXFLAG_no_format - Success
-- Proceeding with version: 24.3.25.0
-- Looking for strtof_l
-- Looking for strtof_l - found
-- Looking for strtoull_l
-- Looking for strtoull_l - found
-- Looking for realpath
-- Looking for realpath - found
-- CMAKE_CXX_FLAGS:  -Wall -Wextra -Wpedantic -Werror -Wstrict-overflow=1 -Wsuggest-override -Wunused -Wunreachable-code -Wdelete-incomplete -Wduplicated-cond -Wdisabled-optimization -Winit-self -Wbool-compare -Wlogical-not-parentheses -Wlogical-op -Wmisleading-indentation -Wno-return-local-addr -Wodr -Wpointer-arith -Wredundant-decls -Wreorder -Wshift-negative-value -Wsizeof-array-argument -Wswitch-bool -Wtautological-compare -Wtrampolines -Wno-deprecated-comma-subscript -Wno-comma-subscript -Wno-ambiguous-reversed-operator -Wno-restrict -Wno-free-nonheap-object -Wno-stringop-overflow -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fdiagnostics-color=auto -fPIC -ftemplate-depth=1024
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.70") found components: date_time iostreams program_options thread unit_test_framework 
-- Found EXPAT: /usr/lib/x86_64-linux-gnu/libexpat.so (found version "2.4.7") 
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so (found suitable version "5.2.4", minimum required is "5.2") 
-- Using Lua 5.2.4
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.1") found components: doxygen dot 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found Protozero: /home/dp-dev/git/osrm-backend/third_party/protozero/include (found suitable version "1.7.1", minimum required is "1.6.3") 
-- Found Osmium: /home/dp-dev/git/osrm-backend/third_party/libosmium/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dp-dev/git/osrm-backend/build/default
Building in: /home/dp-dev/git/osrm-backend/build/default
cmake --build . --target all
[  0%] Building CXX object CMakeFiles/UTIL.dir/src/util/assert.cpp.o
[  0%] Building CXX object CMakeFiles/UTIL.dir/src/util/conditional_restrictions.cpp.o
[  0%] Building CXX object CMakeFiles/UTIL.dir/src/util/coordinate.cpp.o
[  0%] Building CXX object CMakeFiles/UTIL.dir/src/util/coordinate_calculation.cpp.o
[  0%] Building CXX object CMakeFiles/UTIL.dir/src/util/exception.cpp.o
[  4%] Building CXX object CMakeFiles/UTIL.dir/src/util/fingerprint.cpp.o
[  4%] Building CXX object CMakeFiles/UTIL.dir/src/util/geojson_debug_policies.cpp.o
In file included from /usr/include/c++/11/bits/move.h:57,
                 from /usr/include/c++/11/bits/stl_pair.h:59,
                 from /usr/include/c++/11/utility:70,
                 from /usr/include/c++/11/optional:36,
                 from /home/dp-dev/git/osrm-backend/include/util/geojson_debug_policies.hpp:4,
                 from /home/dp-dev/git/osrm-backend/src/util/geojson_debug_policies.cpp:1:
/usr/include/c++/11/type_traits: In instantiation of ‘struct std::is_copy_constructible<osrm::util::json::Object>’:
/usr/include/c++/11/type_traits:3180:33:   required from ‘constexpr const bool std::is_copy_constructible_v<osrm::util::json::Object>’
/usr/include/c++/11/variant:310:5:   required from ‘constexpr const bool std::__detail::__variant::_Traits<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null>::_S_copy_ctor’
/usr/include/c++/11/variant:1326:11:   required from ‘class std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null>’
/usr/include/c++/11/bits/stl_pair.h:218:11:   required from ‘struct std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >’
/usr/include/c++/11/ext/aligned_buffer.h:91:28:   required from ‘struct __gnu_cxx::__aligned_buffer<std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> > >’
/usr/include/c++/11/bits/hashtable_policy.h:234:43:   [ skipping 3 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/c++/11/bits/hashtable_policy.h:1812:13:   required from ‘struct std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >, true> > >’
/usr/include/c++/11/bits/hashtable_policy.h:811:13:   required from ‘struct std::__detail::_Insert_base<std::basic_string_view<char>, std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >, std::allocator<std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> > >, std::__detail::_Select1st, std::equal_to<std::basic_string_view<char> >, std::hash<std::basic_string_view<char> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >’
/usr/include/c++/11/bits/hashtable_policy.h:1004:12:   required from ‘struct std::__detail::_Insert<std::basic_string_view<char>, std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >, std::allocator<std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> > >, std::__detail::_Select1st, std::equal_to<std::basic_string_view<char> >, std::hash<std::basic_string_view<char> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, false>’
/usr/include/c++/11/bits/hashtable.h:180:11:   required from ‘class std::_Hashtable<std::basic_string_view<char>, std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >, std::allocator<std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> > >, std::__detail::_Select1st, std::equal_to<std::basic_string_view<char> >, std::hash<std::basic_string_view<char> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >’
/usr/include/c++/11/bits/unordered_map.h:105:18:   required from ‘class std::unordered_map<std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >’
/home/dp-dev/git/osrm-backend/include/util/json_container.hpp:107:49:   required from here
/usr/include/c++/11/type_traits:987:52: error: static assertion failed: template argument must be a complete class or an unbounded array
  987 |       static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/11/type_traits:987:52: note: ‘std::__is_complete_or_unbounded<std::__type_identity<osrm::util::json::Object> >((std::__type_identity<osrm::util::json::Object>{}, std::__type_identity<osrm::util::json::Object>()))’ evaluates to false
/usr/include/c++/11/type_traits: In instantiation of ‘struct std::is_copy_constructible<osrm::util::json::Array>’:
/usr/include/c++/11/type_traits:3180:33:   required from ‘constexpr const bool std::is_copy_constructible_v<osrm::util::json::Array>’
/usr/include/c++/11/variant:310:5:   required from ‘constexpr const bool std::__detail::__variant::_Traits<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null>::_S_copy_ctor’
/usr/include/c++/11/variant:1326:11:   required from ‘class std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null>’
/usr/include/c++/11/bits/stl_pair.h:218:11:   required from ‘struct std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >’
/usr/include/c++/11/ext/aligned_buffer.h:91:28:   required from ‘struct __gnu_cxx::__aligned_buffer<std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> > >’
/usr/include/c++/11/bits/hashtable_policy.h:234:43:   [ skipping 3 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/c++/11/bits/hashtable_policy.h:1812:13:   required from ‘struct std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >, true> > >’
/usr/include/c++/11/bits/hashtable_policy.h:811:13:   required from ‘struct std::__detail::_Insert_base<std::basic_string_view<char>, std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >, std::allocator<std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> > >, std::__detail::_Select1st, std::equal_to<std::basic_string_view<char> >, std::hash<std::basic_string_view<char> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >’
/usr/include/c++/11/bits/hashtable_policy.h:1004:12:   required from ‘struct std::__detail::_Insert<std::basic_string_view<char>, std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >, std::allocator<std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> > >, std::__detail::_Select1st, std::equal_to<std::basic_string_view<char> >, std::hash<std::basic_string_view<char> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, false>’
/usr/include/c++/11/bits/hashtable.h:180:11:   required from ‘class std::_Hashtable<std::basic_string_view<char>, std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >, std::allocator<std::pair<const std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> > >, std::__detail::_Select1st, std::equal_to<std::basic_string_view<char> >, std::hash<std::basic_string_view<char> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >’
/usr/include/c++/11/bits/unordered_map.h:105:18:   required from ‘class std::unordered_map<std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >’
/home/dp-dev/git/osrm-backend/include/util/json_container.hpp:107:49:   required from here
/usr/include/c++/11/type_traits:987:52: error: static assertion failed: template argument must be a complete class or an unbounded array
/usr/include/c++/11/type_traits:987:52: note: ‘std::__is_complete_or_unbounded<std::__type_identity<osrm::util::json::Array> >((std::__type_identity<osrm::util::json::Array>{}, std::__type_identity<osrm::util::json::Array>()))’ evaluates to false
/usr/include/c++/11/type_traits: In instantiation of ‘struct std::is_copy_assignable<osrm::util::json::Object>’:</div>

**Comment by jcoupey** [comment] 2024-11-25 08:19
Closing as duplicate of #7076.

**Closed by jcoupey** 2024-11-25 08:19 UTC

**Comment by shin0859** [comment] 2025-03-19 18:49
How about this?

ｘ git clone https://github.com/Project-OSRM/osrm-backend.git
〇 git clone –branch v5.27.1 https://github.com/Project-OSRM/osrm-backend.git
