### ISSUE TITLE
generating edge-expanded edges processing 10%....

### ISSUE THREAD

**Issue by eryalee** [Project-OSRM/osrm-backend#2818] opened 2016-08-29 10:30 UTC
**generating edge-expanded edges processing 10%,it will not going done any more...what happend?**
[info] Parsing in progress..
[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)
[info] timestamp: 2016-08-24T19:28:02Z
[info] Found 3 exceptions to turn restrictions:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parsing finished after 17.0117 seconds
[info] Raw input contains 33584690 nodes, 2448138 ways, and 29645 relations
[extractor] Sorting used nodes        ... ok, after 0.381508s
[extractor] Erasing duplicate nodes   ... ok, after 0.590714s
[extractor] Sorting all nodes         ... ok, after 9.23078s
[extractor] Building node id map      ... ok, after 7.10272s
[extractor] setting number of nodes   ... ok
[extractor] Confirming/Writing used nodes     ... ok, after 2.65009s
[info] Processed 14810470 nodes
[extractor] Sorting edges by start    ... ok, after 13.9495s
[extractor] Setting start coords      ... ok, after 11.8564s
[extractor] Sorting edges by target   ... ok, after 14.5759s
[extractor] Computing edge weights    ... ok, after 14.4678s
[extractor] Sorting edges by renumbered start ... ok, after 6.5993s
[extractor] Writing used edges       ... ok, after 1.62723s
[extractor] setting number of edges   ... ok
[info] Processed 15454776 edges
[extractor] Sorting used ways         ... ok, after 0.159115s
[extractor] Sorting 5175 restriction. by from... ok, after 0.003398s
[extractor] Fixing restriction starts ... ok, after 0.031248s
[extractor] Sorting restrictions. by to  ... ok, after 0.009904s
[extractor] Fixing restriction ends   ... ok, after 0.019504s
[info] usable restrictions: 4660
[extractor] writing street name index ... ok, after 0.006687s
[info] Writing turn lane masks...
[info] done (2.7e-05)
[info] extraction finished after 107.449s
[info] Generating edge-expanded graph representation
[info]  - 4660 restrictions.
[info] Importing n = 14810470 nodes
[info]  - 464 bollard nodes, 13628 traffic lights
[info]  and 15454776 edges
[info] Graph loaded ok and has 15454776 edges
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.114187
[info] Edge compression ratio: 0.151098
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Generated 15454452 nodes in edge-expanded graph
[info] generating edge-expanded edges
[info] turn analysis done....
. 10%

**Comment by MoKob** [comment] 2016-08-29 11:01
Closing as duplicate of https://github.com/Project-OSRM/osrm-backend/issues/2814

**Closed by MoKob** 2016-08-29 11:01 UTC
