### ISSUE TITLE
FindLibOSRM cannot find libosrm

### ISSUE THREAD

**Issue by drnextgis** [Project-OSRM/osrm-backend#4650] opened 2017-11-01 11:42 UTC
Try to build custom docker image based on official one and use FindLibOSRM.cmake from [here](https://github.com/Project-OSRM/node-osrm/blob/master/cmake/FindLibOSRM.cmake) to build own OSRM-based application. But CMake cannot find `libosrm` because:

```
$ pkg-config --libs libosrm
Package libosrm was not found in the pkg-config search path.
Perhaps you should add the directory containing `libosrm.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libosrm', required by 'virtual:world', not found
```

It works if specify  `PKG_CONFIG_PATH` manually:

```
PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig pkg-config
 --libs libosrm
-L/usr/local/lib -losrm -flto -Wl,--gc-sections -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common
```

What is the right way to fix this issue?

**Comment by danpat** [comment] 2017-11-01 14:23
Hmm, looks like the problem is that we're installing the `.pc` file in `CMAKE_INSTALL_LIBDIR/pkgconfig`.  For whatever reason, under the Alpine environment, that resolves to `/usr/local/lib64/pkgconfig`.  However, `pkg-config` on Alpine doesn't have that path in it's search list:

```
# pkg-config --variable pc_path pkg-config
/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
```

I think the fix is this PR: https://github.com/Project-OSRM/osrm-backend/pull/4652, but I'd like some feedback on that before merging.

**Comment by daniel-j-h** [comment] 2017-11-06 18:16
#4652 landed in master - @drnextgis could you try and see if it helps?

**Comment by drnextgis** [comment] 2017-11-06 18:26
I've already tried and all works fine, thanks!

**Comment by daniel-j-h** [comment] 2017-11-06 18:43
Perfect - happy routing! 🎉 🚗

**Closed by daniel-j-h** 2017-11-06 18:43 UTC
