### ISSUE TITLE
OSRM demo seems to broken

### ISSUE THREAD

**Issue by bchepur** [Project-OSRM/osrm-backend#3194] opened 2016-10-27 19:11 UTC
http://map.project-osrm.org/
The routing seems to be broken.  select any two random origin and destination, the route maps all the way across the country.

Thank you,
BC

**Comment by daniel-j-h** [comment] 2016-10-27 19:24
Closing as duplicate of https://github.com/Project-OSRM/osrm-backend/issues/3186#issuecomment-256535566.

tl;dr only CA until the demo server re-processes the latest planet with the latest osrm nightly builds:

http://map.project-osrm.org/?z=7&center=38.406254%2C-115.191650&loc=37.020098%2C-112.840576&loc=43.221190%2C-118.410645&hl=en&alt=0

**Closed by daniel-j-h** 2016-10-27 19:24 UTC
