### ISSUE TITLE
Import of planet.osm.pbf failed

### ISSUE THREAD

**Issue by georgbachmann** [Project-OSRM/osrm-backend#3299] opened 2016-11-12 16:08 UTC
Hello,

I already did a testrun with a smaller osm.pbf file and now I wanted to see how OSRM performs on the whole world. So I downloaded a pdf file covering the whole world and tried importing. It failed before because it ran out of memory, then out of disk space. I eliminated those issues (by increasing my google-compute-engine machine... now I have quite a monster with more than 50GB RAM and 8 cores) and now it says that it was killed in the middle of processing?!?

```
osrm@instance-1:~/pbf-files$ osrm-extract planet-latest.osm.pbf -p ~/osrm-backend/profiles/bicycle.lua
[info] Using script /home/osrm/osrm-backend/profiles/bicycle.lua
[info] Input file: planet-latest.osm.pbf
[info] Profile: bicycle.lua
[info] Threads: 8
[STXXL-MSG] STXXL v1.4.1 (prerelease/Debug)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 1000 MiB, I/O implementation: syscall autogrow delete_on_exit queue=0 devid=0
[info] Parsing in progress..
[info] input file generated by planet-dump-ng 1.1.4
[info] timestamp: 2016-10-31T02:00:01Z
[info] Parsing finished after 4317.63 seconds
[info] Raw input contains 3585286779 nodes, 374765439 ways, and 4564745 relations
[extractor] Sorting used nodes        ... ok, after 289.562s
[extractor] Erasing duplicate nodes   ... ok, after 249.858s
[extractor] Sorting all nodes         ... ok, after 2283.89s
[extractor] Building node id map      ... ok, after 1244.16s
[extractor] setting number of nodes   ... ok
[extractor] Confirming/Writing used nodes     ... ok, after 680.895s
[info] Processed 904070651 nodes
[extractor] Sorting edges by start    ... Killed
```

Are there any more logs that would be helpful? In `stxxl.errlog` and `stxxl.log` I can't find any more useful information on what went wrong...

Should OSRM even be able to handle files as large as the whole world?

Cheers,
Georg

**Comment by daniel-j-h** [comment] 2016-11-12 18:22
I don't think 50 GB is enough for the planet. Check `dmesg` to see if you got killed by the oom killer?

Check https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM for swapfile and stxxl config.

Note: the demo server runs on a r3.4xlarge for the planet.

**Comment by georgbachmann** [comment] 2016-11-13 09:44
Alright! Thanks for your replies! I'll try to increase my swap and will try again! Not that much of a linux guru but I guess I will find a solution :) Thanks!

**Comment by georgbachmann** [comment] 2016-11-14 07:04
With 300GB of swapfile it still got an error. `Segmentation fault (core dumped)`... Will still be an out of memory problem?

```osrm@instance-1:~/pbf-files$ osrm-extract planet-latest.osm.pbf -p ~/osrm-backend/profiles/bicycle.lua
[info] Using script /home/osrm/osrm-backend/profiles/bicycle.lua
[info] Input file: planet-latest.osm.pbf
[info] Profile: bicycle.lua
[info] Threads: 8
[STXXL-MSG] STXXL v1.4.1 (prerelease/Debug)
[STXXL-MSG] Disk 'myswapfile' is allocated, space: 300000 MiB, I/O implementation: syscall queue=0 devid=0
[info] Parsing in progress..
[info] input file generated by planet-dump-ng 1.1.4
[info] timestamp: 2016-10-31T02:00:01Z
[info] Parsing finished after 4297.87 seconds
[info] Raw input contains 3585286779 nodes, 374765439 ways, and 4564745 relations
[extractor] Sorting used nodes        ... ok, after 284.034s
[extractor] Erasing duplicate nodes   ... ok, after 215.775s
[extractor] Sorting all nodes         ... ok, after 2303.12s
[extractor] Building node id map      ... ok, after 1245.73s
[extractor] setting number of nodes   ... ok
[extractor] Confirming/Writing used nodes     ... ok, after 673.139s
[info] Processed 904070651 nodes
[extractor] Sorting edges by start    ... ok, after 1820.67s
[extractor] Setting start coords      ... ok, after 1981.84s
[extractor] Sorting edges by target   ... ok, after 1701.49s
[extractor] Computing edge weights    ... ok, after 1991.91s
[extractor] Sorting edges by renumbered start ... Segmentation fault (core dumped)```

**Comment by oxidase** [comment] 2016-11-15 16:27
@georgbachmann position of segfault is similar to one in #3145, but I was not able to reproduce it. Please could you give more context: 
* is it reproducible with the current master 8f6dd805e54fac0e3e57a19a19781f5b37229960
* how often it is reproducible?
* cmake output with complete configuration will be helpful to reproduce the issue

**Comment by georgbachmann** [comment] 2016-11-16 08:15
@oxidase I just did it once as it takes quite a while (I was then focusing on testing the raster-data feature as we would also need that worldwide, which is going to be an other problem). The version I was using was about 2-3 weeks old.
I'll make a new build again today and let you know the outcome!

**Comment by daniel-j-h** [comment] 2016-11-16 10:19
Just a heads up @georgbachmann this bundles latest libosmium: https://github.com/Project-OSRM/osrm-backend/pull/3323 Older versions have issues on larger datasets. We will merge this into master today, just letting you know in case you're faster :)

**Comment by georgbachmann** [comment] 2016-11-16 11:38
Ok, so I should wait for your merge into master then? Thx for the info!

**Comment by daniel-j-h** [comment] 2016-11-16 12:43
I just merged it into master.

**Comment by georgbachmann** [comment] 2016-11-16 13:00
Install looked fine just a few warnings while building. You can see the logs attached

`cmake .. -DCMAKE_BUILD_TYPE=Release`
http://pastebin.com/9upEQbWk

`cmake --build .`
http://pastebin.com/UkQ0m9Hu

`sudo cmake --build . --target install`
http://pastebin.com/CHGA9dC7

I'll try again to import the world with 500GB of swap file... I'll keep you posted

**Comment by georgbachmann** [comment] 2016-11-17 07:49
It's still doing it's import-thing... quite a while now :)

**Comment by daniel-j-h** [comment] 2016-12-14 11:24
Stale. Try latest master and make sure the issue is not on your side (check for enough memory, large enough stxxl file, etc.). If you can still reproduce this, feel free to re-open this ticket.

**Closed by daniel-j-h** 2016-12-14 11:24 UTC
