### ISSUE TITLE
Infinite Loop in OSRM-backend route

### ISSUE THREAD

**Issue by mdenhoedt** [Project-OSRM/osrm-backend#2122] opened 2016-03-19 11:52 UTC
I am on the `rewrite/new-api` branch with [4e9c90447969f5a9b710a395c2025fca4aab6799](https://github.com/Project-OSRM/osrm-backend/commit/4e9c90447969f5a9b710a395c2025fca4aab6799) as latest commit. I though everything worked fine until my code got stuck. After some investigation is located the problem, it is the `osrm:OSRM:Route` call with very specific coordinates. Then I tried the web service version of OSRM-backend (`build/osrm-routed`) and with these specific coordinates my browser says 'Connecting...' to infinity. 

The call is the following:
`localhost:5000/route/v1/car/6.14983,53.4901;6.14991,53.4902`

I searched for this location on Google Maps and I got the following result:

![Google Maps](http://mdenhoedt.github.io/images/bug_osrm.png)

Is there a way to prevent the infinite loop?

**Edit:** I am currently compiling and testing with the latest version of the `develop` branch.

**Comment by mdenhoedt** [comment] 2016-03-19 13:57
Ok, the specific api call does work on [db0db58bf8748d91c7caa7c7cddbb8ba36fe1d27](https://github.com/Project-OSRM/osrm-backend/commit/db0db58bf8748d91c7caa7c7cddbb8ba36fe1d27). So if you guys think you fixed the bug with commits between the two commits, this issues can be closed :smile:

**Comment by MoKob** [comment] 2016-03-21 12:17
I tried to reproduce it with multiple setups and the referenced commits. Sadly I could not reproduce the bug so far. 

Can you reproduce the error on your data-set with the original mentioned commit?
If so, can you provide an extract of the data-set you are using, ideally limited to the region your request fails on?

If such a loop should occur again, please do not hesitate to report it.
We are currently in the process of a huge re-design/re-write. The possibility to include bugs is very large and any hint to prevent such loops is highly appreciated.

**Comment by MoKob** [comment] 2016-03-24 14:10
I think I might have found the cause which should be fixed now.

The reasoning was invalid accesses in a combination https://github.com/Project-OSRM/osrm-backend/blob/rewrite/new-api/include/engine/guidance/assemble_geometry.hpp#L55
and https://github.com/Project-OSRM/osrm-backend/blob/rewrite/new-api/include/engine/guidance/assemble_steps.hpp#L96 not operating on the same data which could cause access-violations and undefined behaviour.

The fix is already merged into rewrite/new-api, but thank you again for reporting the issue.

**Closed by MoKob** 2016-03-24 14:10 UTC
