### ISSUE TITLE
SSL OSRM

### ISSUE THREAD

**Issue by jrischma** [Project-OSRM/osrm-backend#4644] opened 2017-10-28 01:19 UTC
Hi, is possible install SSL certificates? how? ty

**Comment by danpat** [comment] 2017-10-28 02:56
OSRM doesn't support SSL out of the box.

This ticket is a duplicate of https://github.com/Project-OSRM/osrm-backend/issues/4537

There is an example `nginx` reverse proxy configuration here: https://github.com/Project-OSRM/osrm-backend/issues/4517#issuecomment-330359238, you can enable SSL on `nginx`.

Soon, I also hope to land https://github.com/Project-OSRM/osrm-backend/pull/4604, which will make it fairly simple to create a HTTPS-capable server using [ExpressJS](http://expressjs.com/en/api.html), but this PR is still under development.

**Closed by danpat** 2017-10-28 02:56 UTC
