### ISSUE TITLE
accept HTTP POST requests

### ISSUE THREAD

**Issue by Carsten64** [Project-OSRM/osrm-backend#1293] opened 2014-11-25 22:25 UTC
Hello together,

I'm facing a problem with the length of URL by requesting the OSRM services , I get a HTTP Error 414, that means that my URL is too long. I was reviewing the code and found in the file [Connection.h] (https://github.com/Project-OSRM/osrm-backend/blob/master/Server/Connection.h) in line 98 the following code snippet:
<b>boost::array<char, 8192> incoming_data_buffer; </b>.

Is this the place where I can change the value to more KB per request, for example 32 kb?

kind regards

Carsten

**Comment by emiltin** [comment] 2015-01-06 09:22
duplicate of #205? 
maybe rename this issue to soemthing like "accept HTTP POSTrequests"?

**Comment by DennisOSRM** [comment] 2015-01-06 09:24
renamed and closed the other issue.

**Comment by solidsnake2013** [comment] 2015-01-06 10:09
oh! we every time use point of 300-400.
and we We also need to use [table] and [viaroute].

There is no other way?

**Comment by TheMarex** [comment] 2015-05-24 12:12
@solidsnake2013 at this point I would suggest building every serious application on top of `node-osrm` and not using the HTTP interface directly. `osrm-routed` is super convenient for debugging and small deployments, but does not scale to large requests.

**Comment by emiltin** [comment] 2015-05-25 08:57
is ndoe-osrm described in the wiki?

**Comment by TheMarex** [comment] 2015-05-25 09:01
@emiltin [yep](https://github.com/Project-OSRM/osrm-backend/wiki/Library-api#nodejs-language-bindings) but I should move that on the main page.

**Comment by TheMarex** [comment] 2016-01-12 15:20
This was implemented.

**Closed by TheMarex** 2016-01-12 15:20 UTC
Labels: Feature Request
