### ISSUE TITLE
Weird routing with a highway=primary_link

### ISSUE THREAD

**Issue by Codain** [Project-OSRM/osrm-backend#2801] opened 2016-08-23 05:51 UTC
I've found a weird routing proposal:

- 1. http://map.project-osrm.org/?z=17&center=33.620985%2C-117.927557&loc=33.618595%2C-117.929901&loc=33.621101%2C-117.926458&hl=en&alt=0

The turn around and all turning instructions are allowed. But there is a better routing: simply to take the primary_link which allows to pass from CA 55 to CA 1.

Even more strange: it looks like he simply doesn't want to take the motorlink!

- 2. http://map.project-osrm.org/?z=18&center=33.621108%2C-117.928635&loc=33.620445%2C-117.929215&loc=33.621195%2C-117.927139&hl=en&alt=0
- 3. http://map.project-osrm.org/?z=18&center=33.621108%2C-117.928635&loc=33.620391%2C-117.929306&loc=33.621195%2C-117.927139&hl=en&alt=0

Hopefully this one looks ok:

- 4. http://map.project-osrm.org/?z=17&center=33.623138%2C-117.929306&loc=33.620453%2C-117.929183&loc=33.620985%2C-117.928571&hl=en&alt=0

I've looked at the OSM tags and everything looks ok. It has to be noticed that Mapzen has no issue to find this routing.

Any idea?

**Comment by danpat** [comment] 2016-08-23 06:05
The problem is this `restriction=yield` relation:

http://www.openstreetmap.org/relation/543620

OSRM's tag parser is not very fancy.  It only looks for `restriction=only*`, otherwise, it assumes it's a `restriction=no_turn`, then it looks at the `via`, `from` and `to` tags.  The way this tag is set up means OSRM doesn't allow turns from the sliproad onto the east-bound highway.

The easiest fix here is to remove that relation, and place a new node with `highway=give_way` before the end of the slip-road.  There are only 9 `restriction=yield` globally, and it's not documented anywhere in the wiki.  It was added 6 years ago, I think the user who did it might have just invented the tagging scheme.

OSRM's parsing is weak, but I think we can class this one as bad data.  Ideally OSRM's restriction tag handling would be a bit more forgiving.

**Comment by danpat** [comment] 2016-08-23 06:06
Note, you can see how this sliproad is isolated from the rest of the road network here:

http://map.project-osrm.org/debug/#17.35/33.62095/-117.92865

the pink highlight means that this section of road is disconnected, either via a gap, impossible one-way, or a restriction.

**Comment by Codain** [comment] 2016-08-23 06:35
@danpat Ok thank you, I will correct this intersection by removing the relation.

But I think there still is a problem:

http://map.project-osrm.org/?z=18&center=33.620719%2C-117.928877&loc=33.620342%2C-117.929408&loc=33.620985%2C-117.928571&hl=en&alt=0 => KO

http://map.project-osrm.org/?z=18&center=33.620719%2C-117.928877&loc=33.620458%2C-117.929177&loc=33.620985%2C-117.928571&hl=en&alt=0 => OK

The only difference is the starting point, which in the first case is not in the same way than the destination. I don't see how this restriction relation can still be an issue, it is not anymore in the path.

**Comment by danpat** [comment] 2016-08-23 06:41
The weird snapping is caused by the isolated component behaviour.  OSRM tries to do the right thing if you drop a marker near a disconnected area and it moves it to the road network where it can find a route.

Here's a GIF that sort of shows how it works:

<img src="https://i.imgur.com/0XvR1eY.gif"/>
(Linked from https://www.mapbox.com/blog/smart-neighbor/)

Basically, if you drop both coordinates on the small component (the pink), they will both snap to it.  If you drop one coordinate near the main road network, the other marker will also be snapped to the main road network, even if it's closer to your isolated road.

This gets a little more complex when you're dragging markers around on the UI because Leaflet Routing Machine is sending back a `hint`, which keeps a marker locked to it's previous snap point, even if you move both markers near the sliproad.

**Comment by Codain** [comment] 2016-08-23 07:00
I've deleted the relation and will wait to see if it solves the problem.

But wouldn't it be better to ignore an unknown relation instead of considering it as a no_turn?

**Comment by danpat** [comment] 2016-08-23 07:10
@Codain probably.  This relation was a `type=restriction`, and that's all OSRM is currently looking for.

I'll change the title of this ticket and leave it open, we should probably only add restrictions for `restriction=*` types that we know are good.

**Comment by danpat** [comment] 2016-08-23 07:15
Closing in favour of https://github.com/Project-OSRM/osrm-backend/issues/2802

**Closed by danpat** 2016-08-23 07:15 UTC

**Comment by Codain** [comment] 2016-08-23 07:16
Thank you!!
