### ISSUE TITLE
Support routing when to/from are located inside private places

### ISSUE THREAD

**Issue by naoliv** [Project-OSRM/osrm-backend#2663] opened 2016-07-15 15:35 UTC
Is it possible to have [this part](https://github.com/Project-OSRM/osrm-backend/issues/358#issuecomment-8185400) implemented, please?

`Access restricted areas are not yet handled correctly in the sense that it should be possible to start on or end at such a street, but not route should go over such a street if not absolutely necessary.`

ie, if I _want_ to go to a place with a restriction (`access=private`) then it should support it (and not route to the nearest non-restricted highway)

You can see an example [here](http://map.project-osrm.org/?z=16&center=-9.591345%2C-35.726638&loc=-9.594953%2C-35.725318&loc=-9.596846%2C-35.729578&hl=en&alt=0) of what is happening

**Comment by TheMarex** [comment] 2016-07-19 10:03
Please don't open duplicate issues that just state that you would like to have a feature implemented. This is a duplicate of https://github.com/Project-OSRM/osrm-backend/issues/156

You can use the :+1: emoji reaction to the issue if you really want to voice your input.

**Closed by TheMarex** 2016-07-19 10:03 UTC

**Comment by naoliv** [comment] 2016-07-19 12:30
#156 tile says `Respect access=destination` and the discussion is also mainly about `access=destination`
That is why I did open another issue
