### ISSUE TITLE
Unable to listen it through browser

### ISSUE THREAD

**Issue by maheshnathwani** [Project-OSRM/osrm-backend#2895] opened 2016-09-11 03:16 UTC
The osrm-routed service runs on 0.0.0.0:5000. It gives a response when called using curl or wget but does not respond when called from the browser or any other REST client. I even tried to proxy it using nginx and apache but none of the methods work. I've even tried changing the ip from 0.0.0.0 to the server ip using osrm-routed -i but nothing seems to work. 
PS: I use osrm-routed 5.3.0v

**Comment by danpat** [comment] 2016-09-11 03:44
@maheshnathwani Listening on "0.0.0.0" means "listen on all network interfaces".

Here's how it looks for me:

![screen shot 2016-09-10 at 8 42 05 pm](https://cloud.githubusercontent.com/assets/1892250/18415007/18455542-7797-11e6-9c55-f94e69795153.png)

If you can hit your local `osrm-routed` instance with `curl`, then the `osrm-routed` server is working fine.  It sounds like there's a problem with your browser, or the URL you're constructing.

The code that runs `osrm-routed` has not changed significantly recently, and nobody else has reported this issue, I think the problem is somewhere in your browser or how you're specifying the URL.

**Comment by maheshnathwani** [comment] 2016-09-11 04:05
@danpat Here's the screenshot of the terminal and browser, the url used is same in both the cases. I've tried using IE, firefox and chrome. It doesn't seem to work on any of it.
![capture](https://cloud.githubusercontent.com/assets/10951432/18415072/f6a3ab2a-7802-11e6-9653-95cf274dc93e.PNG)

**Comment by danpat** [comment] 2016-09-11 05:14
@maheshnathwani check your browser security/proxy/firewall settings.  If curl continues to work, then `osrm-routed` is probably fine and the problem lies somewhere else.  I can't think of a good reason for it to respond to curl but not to a browser. That's a big hint that the browsers are doing something wrong.

Under Windows all browsers pick up the global proxy and security settings, check those and make sure nothing is being blocked.

The "connection timed out" message hints at a firewall - the browser is not even getting a connection ack from the server - this means the request is probably never getting to `osrm-routed` in the first place.

Use the debugging console in your browser to check the network traffic - maybe also use something like wireshark to trace where the connection is going.

**Comment by maheshnathwani** [comment] 2016-09-11 07:07
@danpat I switched off the firewall and checked the thing but the results are still negative, I even checked the network traffic using wireshark, it's hitting the right port. And yes you're right the _osrm-router_ doesn't seem to receive the request made from the browser.

![capture](https://cloud.githubusercontent.com/assets/10951432/18415796/80d8331a-781c-11e6-99e7-1428491521e0.PNG)

**Comment by danpat** [comment] 2016-09-11 15:35
@maheshnathwani Without knowing your network setup, I don't know what else I can suggest.

Can you run `tcpdump -vv -X -s 1500 tcp port 5000` on the 70.35.202.65 machine and see if the requests are making it?

If they're not even making it to the `osrm-routed` machine, then the problem lies not with `osrm-routed`, but with something else on your network.  If this is the case, please close this ticket.

**Comment by danpat** [comment] 2016-09-11 18:03
@maheshnathwani Looking back at your screenshots, are you even running the browser and `curl` on the same machine?

It looks like you might be running `curl` on a Linux machine, perhaps the same machine that's running `osrm-routed`?  However, your browser is local and needs to go over the network to access 70.35.202.65.

If that's the case, then the problem is definitely your network setup - either you've got a firewall in place somewhere that's blocking port 5000, or you desktop can't route to 70.35.202.65 - perhaps it's running on a VM that you haven't properly connected to your network, or is running via NAT and can't accept incoming requests.

Either way, this doesn't look like an `osrm-routed` problem, but rather how you've configured your network.

Closing, please re-open if you can confirm it's an `osrm-routed` issue.

**Closed by danpat** 2016-09-11 18:03 UTC
