### ISSUE TITLE
Complex Turn Lane Cases

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#2774] opened 2016-08-16 19:47 UTC
Capturing from notes from @MoKob:

> We are handling turn lane cases only that can be assigned more or less directly. We are missing cases that cannot be handled as one-to-one assignment (e.g. left-arrow to left-turn).

/cc @MoKob

**Comment by MoKob** [comment] 2016-08-17 07:13
This is more or less a duplicate of whats in https://github.com/Project-OSRM/osrm-backend/issues/2553

**Closed by MoKob** 2016-08-17 07:13 UTC
Labels: Guidance
