### ISSUE TITLE
Profile profiles/car.lua not found!

### ISSUE THREAD

**Issue by billystalnaker** [Project-OSRM/osrm-backend#3723] opened 2017-02-16 15:14 UTC
I'm trying to extract a map using `osrm-extract map.osm` I have to symbolic links in the working directory. One to osrm-backend/profiles/lib. One to osrm-backend/profiles/car.lua named profile.lua. And I am getting the error `[error] Profile profiles/car.lua not found!`. Any help would be appreciated!

**Comment by danpat** [comment] 2017-02-16 15:15
@billystalnaker Any reason you can't just run `osrm-extract -p wherever/profiles/car.lua map.osm` ?

**Comment by billystalnaker** [comment] 2017-02-16 15:24
No reason at all, I'm just following this article https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04 and honestly I don't really know how to use the service other than what I'm reading here and googling. I tried to run `man osrm-extract` but there are no man pages for it. Is there a documentation page foreach command somewhere?

**Comment by daniel-j-h** [comment] 2017-02-16 15:28
Yeah that article is super outdated. Don't use it. I tried to get them to update it once but it has to go through review process, needs to get tested on their infrastructure etc.

Please use the Wiki
https://github.com/Project-OSRM/osrm-backend/wiki

Closing as not actionable on our side.

**Closed by daniel-j-h** 2017-02-16 15:28 UTC

**Comment by daniel-j-h** [comment] 2017-02-16 15:29
It seems like you're also using an old version

https://github.com/Project-OSRM/osrm-backend/pull/3554

changes the default to `profiles/car.lua` and

https://github.com/Project-OSRM/osrm-backend/pull/3510

removes the root symlink.

Please use the latest stable release. Docker images if you can.

**Comment by billystalnaker** [comment] 2017-02-16 15:48
@daniel-j-h I thought I cloned master using `git clone https://github.com/Project-OSRM/osrm-backend.git` is this not correct?

**Comment by daniel-j-h** [comment] 2017-02-16 16:05
Yes, it will give you a development version though, from which we cut stable releases every other months.

**Comment by driconmax** [comment] 2017-02-22 19:50
I still not knowing what to do to solve this same problem....

**Comment by billystalnaker** [comment] 2017-02-22 19:56
I believe the problem for me was not specifying the exact path of the profile from the current working directory.

**Comment by daniel-j-h** [comment] 2017-02-23 10:16
Running OSRM: https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM
Docker images: https://github.com/Project-OSRM/osrm-backend/wiki/Docker-Recipes
Building from source: https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM

**Comment by driconmax** [comment] 2017-02-23 12:27
> Quickstart:
> 
> wget http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf
> 
> osrm-extract berlin-latest.osm.pbf -p profiles/car.lua
> osrm-contract berlin-latest.osrm
> osrm-routed berlin-latest.osrm

Those steps didn't work for me..... 

`[error] Profile profiles/car.lua not found!`

If you are not going to explain, or try to resolve the problem, please don't answer.

**Comment by emiltin** [comment] 2017-02-23 13:32
you pass the path to the profile file when running osrm-extract:

osrm-extract berlin-latest.osm.pbf -p profiles/car.lua

in the above case, it's a relative path, ie. relative from the folder you're in when running osrm-extract. the above command should work if you cloned the osrm-backend repo and are in the root folder when running osrm-extract, since the repo contains profiles/car.lua.

you can also pass an absolute path, e.g. -p /home/myuser/myprofiles/car.lua. you would have to adjust to the acual location of your car.lua file.

**Comment by driconmax** [comment] 2017-02-23 14:11
But the problem is that `car.lua` it doesn't exist. And i don't know what to do to create it.

**Comment by emiltin** [comment] 2017-02-23 14:34
it's in the osrm-backend repo: https://github.com/Project-OSRM/osrm-backend/tree/master/profiles. if you clone the repo, you get all files, including the profiles.

**Comment by driconmax** [comment] 2017-02-23 14:37
I used the windows binaries. Because it says that windows is no longer compiling in all the PCs. I will take a look at that, thx.

**Comment by wangzi6578** [comment] 2018-01-02 06:16
hello,after i run it on my local file successfully, how could i set up server on nginx ,is there a documents to read ?

**Comment by daniel-j-h** [comment] 2018-01-02 09:59
https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM#running-the-engine-via-a-http-server-osrm-routed

**Comment by IonicaBizau** [comment] 2018-02-20 09:32
I had the same problem. In my case, my file structure was looking like this:

```
 - osrm-backend
   - profiles
     - car.lua
     ...
 - my-project
   - my-map.osm.pbf
```

I was running the command in `my-project` and I specified the path to the `car.lua`:

```sh
osrm-extract my-map.osm.pbf -p ../osrm-backend/profiles/car.lua
```

That worked and generated `my-map.osrm`. Then I ran:

```sh
osrm-contract my-map.osrm
```

**Comment by IonicaBizau** [comment] 2018-02-20 09:41
In the context of a Node.js app, after doing more progress, I realized that the `osrm-extract` is located in the `node_modules/osrm/lib/osrm-extract` (so, no need to build `osrm-backend` manually).

```sh
./node_modules/osrm/lib/binding/osrm-extract my-map.osm.pbf -p ./node_modules/osrm/profiles/car.lua
```

**Comment by DDmisc** [comment] 2019-01-03 17:12
From osrm-backend folder, the following command seems to work :  ./build/osrm-extract ./build/france-latest.osm.pbf -p profiles/car.lua

**Comment by rborges89** [comment] 2019-02-21 11:08
> I had the same problem. In my case, my file structure was looking like this:
> 
> ```
>  - osrm-backend
>    - profiles
>      - car.lua
>      ...
>  - my-project
>    - my-map.osm.pbf
> ```
> I was running the command in `my-project` and I specified the path to the `car.lua`:
> 
> ```shell
> osrm-extract my-map.osm.pbf -p ../osrm-backend/profiles/car.lua
> ```
> 
> That worked and generated `my-map.osrm`. Then I ran:
> 
> ```shell
> osrm-contract my-map.osrm
> ```
you saved my life
