### ISSUE TITLE
How to get distance in table api

### ISSUE THREAD

**Issue by devravi** [Project-OSRM/osrm-backend#2975] opened 2016-09-30 10:11 UTC
According to documentation (README.MD)

> table 	computes distance tables for given coordinates

But it returns duration in response, can you help me how can I get distance between two cordinate (One source to many destinations).

**Comment by daniel-j-h** [comment] 2016-09-30 10:29
Closing as duplicate of https://github.com/Project-OSRM/osrm-backend/issues/1353.

**Closed by daniel-j-h** 2016-09-30 10:29 UTC
