### ISSUE TITLE
Problem accessing web server

### ISSUE THREAD

**Issue by zbychuk** [Project-OSRM/osrm-backend#1357] opened 2015-01-26 17:01 UTC
Last night I have noticed a problem accessing your service. It is still there.
When I issue request from my program, I am getting {"The remote server returned an error: (502) Bad Gateway."}, when I issue the very same request from the browser, I am getting proper response.
I guess it must be a header problem, but it was working with the same software before, so I am not sure what to change.

**Comment by TheMarex** [comment] 2015-01-26 17:04
Might be you just hit the 3 minute of downtime we have each day when we cycle the data. Does the request work now?

**Comment by DennisOSRM** [comment] 2015-01-27 06:37
This is a brief inconvenience due to a regression in the http code. Should be fixed shortly. Tracking in #1359

**Closed by DennisOSRM** 2015-01-27 06:37 UTC
