### ISSUE TITLE
Split CompressedEdge into separate arrays

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2423] opened 2016-05-19 18:28 UTC
Currently we save `CompressedEdge` as a vector on disc, and load it as-is in memory. That means the data is interleaved and when we need to retrieve it over `GetUncompressedGeometry` and `GetUncomrpessedWeights` we need it iterate over the range and copy the corresponding values out. Like [here](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/datafacade/internal_datafacade.hpp#L612-L620).

- Serialize out components of `CompressedEgde` as separate arrays.
- Return a read-only-range and not a vector. (== zero-copy) in `{Internal,Shared}DataFacade`

**Comment by danpat** [comment] 2016-08-26 05:19
Dupe of https://github.com/Project-OSRM/osrm-backend/issues/2423

**Closed by danpat** 2016-08-26 05:19 UTC
Labels: Refactor
