### ISSUE TITLE
Problem since luabind replace by Sol2 

### ISSUE THREAD

**Issue by fijemax** [Project-OSRM/osrm-backend#3452] opened 2016-12-15 10:45 UTC
Since that luabind was replaced by Sol2 I can't iter on way's nodes.

My lua code : 

```
  print("way id : ", way:id());
  for node in way:get_nodes() do
   print("  node id  : ", node:id())
  end
```

The error exception : 
```
way id : 	5203906
TBB Warning: Exact exception propagation is requested by application but the linked library is built without support for it
terminate called after throwing an instance of 'tbb::captured_exception'
  what():  lua: error: profile.lua:677: attempt to call a userdata value
Abandon (core dumped)
```

**Comment by daniel-j-h** [comment] 2016-12-15 10:56
Thanks,

@karenzshea can you have a look? This could be related to the notes [here](http://sol2.readthedocs.io/en/latest/api/containers.html).

@fijemax can you tell us the Lua version you are using? 5.1 by chance?

**Comment by fijemax** [comment] 2016-12-15 11:10
@daniel-j-h 
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

**Comment by fijemax** [comment] 2016-12-15 11:15
I can solved the problem by updating lua ?

**Comment by daniel-j-h** [comment] 2016-12-15 11:17
Maybe; you can give Lua 5.2 a try.

But that's still an issue for us since we support both Lua 5.1 _and_ Lua 5.2.

Lua 5.3 has some garbage collection issues which make it consume way more memory during extraction.

**Comment by danpat** [comment] 2016-12-17 06:40
I can reproduce this, and unfortunately, simply switching to Lua 5.2 doesn't fix it.  Needs some more digging, but it looks like we're not binding everything we need to with Sol2.

**Comment by oxidase** [comment] 2016-12-17 22:04
@fijemax in your example `for node in way:get_nodes() do` will not work with #3468 but `for _, node in ipairs(way:get_nodes()) do` should be ok. I don't see a way to make an iterator with a state in sol.

**Comment by fijemax** [comment] 2016-12-20 10:10
Hi,
I tested with `for _, node in ipairs(way:get_nodes()) do`
this don't work no more.

**Comment by oxidase** [comment] 2016-12-20 10:34
@fijemax the fix is not yet merged to `master` but located  the branch `sol-metafunctions`.
It must be clarified first how to deal with iterators for user defined types in sol2.

**Comment by ThePhD** [comment] 2016-12-21 18:41
For Lua 5.2 and 5.3, you can override the appropriate iteration metamethods (`pairs`, `next`, etc.). We do that when we serialize userdata containers (implementation [here](https://github.com/ThePhD/sol2/blob/develop/sol/container_usertype_metatable.hpp#L259) where we store a userdata iterator and call the state with whatever `begin` and `end` iterators provided by the class, if they exist).

For Lua 5.1, **if and only if you want to use ipairs or pairs**, you must hand the function a table of some sort (you have to serialize whatever data to a table). This makes it read-only and also makes it hard to modify elements during iteration (if that is what you require), but that's just how it goes (unless you iterate in some other manner).

Note that using a numeric for loop and somehow associating some state data with that might also be beneficial for your purposes.

**Comment by MoKob** [comment] 2017-01-04 07:31
@oxidase does you PR fully solve this problem? If so, could you close here. Otherwise it would be great if we could capture clearly whats left to do.

**Comment by fijemax** [comment] 2017-01-04 09:37
Hi @MoKob, @oxidase 

1) I just noticed that nodes accecible in the luabind in "way_function" are actually "noderefs" and this class don't contains version argument, i can't test version here.
But I have tested node version in the "node_function" in lua and it's all good.

2)  I tested the returned value of get_nodes and I can iter on with ipairs.

I rebase this commit on master.

**Comment by oxidase** [comment] 2017-01-04 09:54
@fijemax thanks for your feedback! Closed as partially implemented. Full solution would require dropping Lua 5.1 support and implementation of userdata meta functions for `WayNodeList`.

**Closed by oxidase** 2017-01-04 09:54 UTC
Labels: Bug Report
