### ISSUE TITLE
CORS with angularjs

### ISSUE THREAD

**Issue by wilifabrizio** [Project-OSRM/osrm-backend#1667] opened 2015-09-10 00:37 UTC
Hello, I have the following problem with angularjs

XMLHttpRequest cannot load http://159.203.66.78:5000/viaroute?loc=-29.15199,-59.65164&loc=-29.118311,-59.6552098. Request header field Authorization is not allowed by Access-Control-Allow-Headers.

code angularjs:

$http.get('http://159.203.66.78:5000/viaroute?loc=-29.15199,-59.65164&loc=-29.118311,-59.6552098').success(function(response){
console.log(response);
});

as I add the CORS?

sorry, my English is bad.

**Comment by woodbri** [comment] 2015-09-10 00:50
On 9/9/2015 8:37 PM, Javier Fabrizio wrote:
> Hello, I have the following problem with angularjs
>
> XMLHttpRequest cannot load
> http://159.203.66.78:5000/viaroute?loc=-29.15199,-59.65164&loc=-29.118311,-59.6552098.
> Request header field Authorization is not allowed by
> Access-Control-Allow-Headers.
>
> code angularjs:
>
> $http.get('http://159.203.66.78:5000/viaroute?loc=-29.15199,-59.65164&loc=-29.118311,-59.6552098').success(function(response){
> <http://159.203.66.78:5000/viaroute?loc=-29.15199,-59.65164&loc=-29.118311,-59.6552098').success(function(response)%7B>
> console.log(response);
> });
>
> as I add the CORS?
>
> sorry, my English is bad.

See https://www.google.com/#newwindow=1&q=CORS+apache

Basically, the issue is that your ajax requests need to go to the same 
server as the source page is loaded from. For example: put your OSRM 
server on the same host as the apache server.

Or you can setup a proxy server on your web server to redirect the osrm 
requests to that server. So you ajax request goes to apache and apache 
then forwards the OSRM request to the other server and returns it 
response back to you.

HTH,
   -Steve

**Comment by TheMarex** [comment] 2015-09-10 14:52
Closing. This is a user error.

**Closed by TheMarex** 2015-09-10 14:52 UTC
