### ISSUE TITLE
Problem with running multiple osrm instances (datastore)

### ISSUE THREAD

**Issue by Behizz** [Project-OSRM/osrm-backend#4023] opened 2017-05-10 09:45 UTC
hello,
I'm using the latest release of osrm (5.7.0) to run multiple routing servers. I use datastore component to load data to ram, each osrm instance has different datasets. 
I used to change the name of the lock file in c++ to create different locks but it doesn't work with the latest release. When I run datastore on another instance, the routed component on the other instance "core dumped".
How can I run these instances simultaneously?

Thanks

**Comment by daniel-j-h** [comment] 2017-05-10 10:14
You can't at least not when using the datastore to pre-load data into shared memory. We don't have named shared segments yet which means only one datastore dataset will reside in shared memory.

Duplicate of:
- https://github.com/Project-OSRM/osrm-backend/issues/1907
- https://github.com/Project-OSRM/osrm-backend/issues/1221

An interesting question is if you can spawn multiple docker containers and for each one you basically run a separate datastore and routed binary. You just have to keep the container alive between running datastore and routed, otherwise the shared memory will be gone. But running a small script inside a container which basically runs `osrm-datastore && osrm-routed` should work.

Not sure if the cgroup namespaces will isolate the shared memory regions, too. You have to test this.

- https://github.com/Project-OSRM/osrm-backend#quick-start
- https://hub.docker.com/r/osrm/osrm-backend/

**Comment by Behizz** [comment] 2017-05-11 09:40
@daniel-j-h Thanks for your answer, but I can't use the docker images to this, because each time I should kill the last container, run a new container and run "osrm-datastore && osrm-routed" script on it.
I's not possible because I want to do this update every 5 or 10 minutes.
Isn't there any other solutions for this?

**Comment by daniel-j-h** [comment] 2017-05-11 09:49
Someone needs to implement named shared regions it's just that no one did it so far and it's not a priority for the core devs right now. If you want to help out here we're more than happy to guide you along.

Or don't use the datastore. Sorry.

**Closed** 2017-07-06 13:17 UTC

**Comment by RobertSellers** [comment] 2018-06-28 15:35
@Behizz Did you ever come up with an alternative? I'm facing the same problem and I'm not finding a single doc/thread outlining a different method.

**Comment by Behizz** [comment] 2018-06-28 18:10
@RobertSellers Yes, actually in the 5.17.0 release of OSRM this feature is implemented by adding named shared regions. You can set the name of the shared region with `--dataset-name` flag.
