### ISSUE TITLE
Unexpected car routing path

### ISSUE THREAD

**Issue by PinkDuck** [Project-OSRM/osrm-backend#1557] opened 2015-06-30 16:03 UTC
Re: http://osrm.at/dfT

I'm not sure why, but the demo website's route output takes the upper and downwards edges of a triangle of one way roads in the middle here, a distance of 35 m, compared to the direct segment one-way of 33.8 m.

**Comment by TheMarex** [comment] 2015-07-01 09:19
The problem is that the travel time is the same for both segments: `3s` so to OSRM it looks like both are equally good and it just choses the first one it finds. What will help with this are turn penalties that we want to introduce by default in `v4.8.0`.

Keeping this around for reference.

**Comment by lordsutch** [comment] 2015-07-01 17:06
Technically I believe the cross-over legs should be tagged in OSM with only_straight_on restrictions, although turn penalties will help as well of course.

**Comment by PinkDuck** [comment] 2015-07-02 17:09
I also think that if optimising for time and two possibilities have the same time (to whatever rounding degree) then the one with less distance should be selected ahead of the first found.

There's no actual restriction signed at the junction in question, the cross-over mainly coming from the on-road markings. I prefer the adjustment mentioned above over the addition of virtual restriction relations.

**Comment by woodbri** [comment] 2015-07-02 18:17
turn penalties are not restrictions. A turn penalty comes from the fact that is you have to make a turn it requires you to negotiate the turn, so adding a time penalty for that fact will cause it to not exit the current roadway and renter it again unless the benefit is greater than the added penalties. And you can also to things like look at the angle of the turn so sharper turns are penalized more than shollow turns like merging or a fork.

**Comment by MoKob** [comment] 2016-06-06 12:43
This is a clear issue of a missing turn restriction on the lane. Turning at that location is simply not possible.

Its just the same as if we were looking at a two turning lanes crossing and would allow to switch.
I've added the respective restriction to OSM. Closing here.

**Closed by MoKob** 2016-06-06 12:43 UTC
Labels: Bug Report

**Comment by PinkDuck** [comment] 2016-06-06 17:14
There is no actual turn restriction, it is legal to make a U-turn there, it's just unadvisable. This is more a software quality thing in determining the risk for switching direction in a 70 mph zone. Adding the turn restriction fixes only this instance.
