### ISSUE TITLE
Routing api doesn't prefer highway route for car profile

### ISSUE THREAD

**Issue by skthon** [Project-OSRM/osrm-backend#5369] opened 2019-02-20 08:34 UTC
I am trying to get the route between two coordinates on a highway which passes through a tunnel. The result prefers the residential route instead of highway.
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=41.0558,29.1823;41.0548,29.1878

![route](https://user-images.githubusercontent.com/16775059/53076993-096a6b80-3517-11e9-81e3-a0da061ccdf8.png)

The above route distance is 3.6kms, if the route is through the highway then it will take only 1.5kms. Even if i use the alternatives parameter it gives only the above route. I want to know how to fallback to the highway route to get the shortest path.

Thanks in advance.

**Comment by chaupow** [comment] 2019-02-20 21:37
Hi @skthon,

unfortunately I cannot reproduce the error, because the osrm demo server seems to get the route correctly: https://map.project-osrm.org/?z=17&center=41.054300%2C29.186436&loc=41.055796%2C29.182348&loc=41.055149%2C29.186897&hl=en&alt=0

<img width="1087" alt="screenshot 2019-02-20 22 36 09" src="https://user-images.githubusercontent.com/804027/53126203-ee701980-355f-11e9-90a2-11f55ff71e99.png">



It seems like openstreetmap.org is running a different OSRM instance:
https://github.com/fossgis-routing-server/osrm-backend 
There must be some differences, because it seems to be running on `v5.14.1` according to https://routing.openstreetmap.de/about.html

Maybe it'd be worth asking [here](https://github.com/fossgis-routing-server/osrm-backend#contact)

**Comment by chaupow** [comment] 2019-02-20 21:38
Closing this issue but feel free to reopen if you need to 🙂

**Closed by chaupow** 2019-02-20 21:38 UTC

**Comment by skthon** [comment] 2019-03-02 06:59
@chaupow Thanks for information. I tried installing a local copy of osrm with latest version(v5.22.0). But i am not able to get the same results as the osrm demo server. Do we have to set any configurations options before running the osrm instance.

**Comment by danpat** [comment] 2019-03-02 16:39
The way in OSM is tagged with `construction=motorway`, which basically disables it in the default OSRM profiles.

The OSRM demoserver ignores construction tags, but that is not the default in that are included.

**Comment by skthon** [comment] 2019-03-06 12:45
@danpat Thanks for the instructions. I commented out `construction=motorway` in car profile & pre-processed the extract again. I got improved results. But i am still not able to get the results same as osrm demo server which is correct.

Can i get the copy of car.lua which osrm demo server(https://map.project-osrm.org) is using. If there's a publicly available repository can you direct me to that page. 

Thanks in advance

**Comment by skthon** [comment] 2019-03-11 05:14
Hey @danpat, did you get time to go through my previous comment. Can you help me out with the configuration.
