### ISSUE TITLE
Not routing via access=destination and not shown as small-components

### ISSUE THREAD

**Issue by srividyacb** [Project-OSRM/osrm-backend#4173] opened 2017-06-19 07:14 UTC
In the below route the routing is not happening because of the `access=destination` tag to the service road - https://www.openstreetmap.org/way/6677845/

[Route](http://map.project-osrm.org/?z=18&center=52.356140%2C6.666714&loc=52.356047%2C6.666754&loc=52.355749%2C6.666893&hl=en&alt=0)

![image](https://user-images.githubusercontent.com/3423533/27273277-f531b4f0-54eb-11e7-94e7-c14c701ab29e.png)

Tried running this request locally by removing the `access=destination` and the routing works fine. 

![image](https://user-images.githubusercontent.com/3423533/27273446-b60d4fea-54ec-11e7-9fc6-67747d3b3090.png)
*Localhost routing without `access=destination*

As [`access=destination` is a blacklisted tag](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L80) this road should have shown as a small-component, but it looks like it in included with rest of the roads. Not sure what is the issue with this tag getting excluded.

cc @daniel-j-h @mokob

**Comment by danpat** [comment] 2017-07-03 21:54
Currently, we're completely removing all `access=destination` tags - they don't get disconnected from the road network, they get completely removed.

If you check out the "debug map" you can see that some of the geometry is missing:

![screen shot 2017-07-03 at 2 51 54 pm](https://user-images.githubusercontent.com/1892250/27808785-3434651c-5fff-11e7-875c-f81686e48636.png)


The piece of road on the west side is tagged `access=destination` - this means we exclude it complete (currently).

The rest of the loop road is tagged as `oneway=yes` - this becomes a small component because you can't access it unless you start on it (for something to be considered "connected to the main network" you have to be able to both exit and enter).

**Comment by danpat** [comment] 2017-07-03 21:56
Note that routing *within* the component works as expected:

![screen shot 2017-07-03 at 2 56 02 pm](https://user-images.githubusercontent.com/1892250/27808873-c1fbb058-5fff-11e7-8cbe-ca0df3b4032c.png)

**Comment by MoKob** [comment] 2017-07-04 09:02
@danpat did access=destination not make it into the list of penalised private access roads? We have the `weights` in place to handle these, right?

**Comment by danpat** [comment] 2017-07-05 18:14
The problem here is that the way is tagged as `highway=service` - @TheMarex pointed out https://github.com/Project-OSRM/osrm-backend/pull/4232#issuecomment-312752703 that if we include these restricted-access service roads, we cause a common problem of service roads around large private facilities, like airports (imprecise geocoding often leads to routing people to airport service roads).

**Comment by daniel-j-h** [comment] 2017-09-27 23:11
@danpat @MoKob what do you see as next actions here?

**Comment by MoKob** [comment] 2017-09-28 08:35
Since `highway=service` and `access=restricted` is out by design, I would consider this a wont fix issue.

**Closed by MoKob** 2017-09-28 08:35 UTC
