### ISSUE TITLE
Support via-way restrictions for multiple vias

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#4439] opened 2017-08-24 19:56 UTC
Over in https://github.com/Project-OSRM/osrm-backend/issues/2681, support was added for turn restricitons in OSM that use a `way` as the `via`.

In theory, it's possible to have multiple `via`s for a turn, although in practice they're pretty rare, most restructions are expressed with a single via `way` or `node`.

For completeness, we should support multiple vias for turn restrictions.

**Comment by Andygol** [comment] 2017-11-15 19:38
@danpat ✋ I'm really waiting for that moment when this feature would be implemented.
It will help to avoid adding tonnes of excessive TRs 🙄 👉 https://www.openstreetmap.org/#map=19/33.85192/-84.36983

![java openstreetmap editor 2017-11-15 21-33-26](https://user-images.githubusercontent.com/369696/32856150-a91a1446-ca4c-11e7-8280-37cd60539ab7.png)

ref https://github.com/mapbox/mapping-guides-internal/issues/7#issuecomment-343212860
/cc @daniel-j-h

**Comment by danpat** [comment] 2017-11-16 05:36
@Andygol This ticket is open, but we have no plans to work on it for a while.

Quick question about the modelling at this location.  The highlighted node:

![screen shot 2017-11-15 at 9 32 57 pm](https://user-images.githubusercontent.com/1892250/32875395-a368f274-ca4c-11e7-892d-7e79844374b6.png)

has two `via` roles in turn restrictions.  You could achieve the same result by simply disconnecting these ways.

**Comment by Andygol** [comment] 2017-11-16 09:34
>You could achieve the same result by simply disconnecting these ways.

Yeah, I know this approach. If we remove this node in order to disconnect the lines, this place will appear in one of the way-crossing validators and the point will be added again - this is not a solution to the problem. 

The main goal is to encourage mappers to follow up our mapping guides and establish them as the best practices among OSM community. But without supporting multi-vias turn restriction it is hard to push this approach even for mapping activities inside Mapbox.

Read detailed explanation about suggested mapping of SPI-junctions here - https://github.com/mapbox/mapping-guides-internal/issues/7#issuecomment-343212860 👇 

![java openstreetmap editor 2017-11-09 16-42-54](https://user-images.githubusercontent.com/369696/32611808-45510d5c-c56f-11e7-9ab8-c0f105a6ad28.png)

**Comment by blinters** [comment] 2018-03-14 07:46
I am experiencing the same issue mentioned by @eFrysTon too!. Any updates?

**Comment by 1ec5** [comment] 2018-03-14 21:03
For what it’s worth, there appear to be [just over a thousand](http://overpass-turbo.eu/s/x1l) turn restriction relations containing multiple `via` ways. (The query isn’t foolproof; I see a lot of defective restriction relations in there.)

**Comment by eFrysTon** [comment] 2018-03-14 21:11
Well, may main point was that the graphic turn restriction editor in iD is now creating them with a single click without it even being noticeable that it's a multi-way via restriction or any indication that support for these is still lackluster in available routing engines. Which means they are likely to proliferate in the future.

**Comment by danpat** [comment] 2018-03-14 21:25
@eFrysTon the holdup here is that the implementation is not trivial, and is relatively low priority when there aren't that many of these things out there yet.

The way OSRM models the road network as a graph makes it easy to support via-node restrictions (we simply delete an edge and the turn is no longer possible).  For via-single-way restrictions, some "tricks" have been implemented, but can't be extended to support the multiple via way restrictions.

Supporting multi-via-way restrictions very likely requires some quite complicated graph transformation/expansion around intersections with multi-via-way restrictions.

As always, pull requests implementing the feature from the community are very welcome :-)

**Comment by yaofu1986** [comment] 2018-04-15 16:29
Hi, I have a maybe silly question: is there any via-way(s) restriction in real-world road network? (I don't have a driving license yet :( )

I mean it seems most of via-ways restriction in OSM is a side product caused by a single physical intersection being divided into multiple OSM nodes.

For example, a classic # shape road, to disable a u-turn then a via-ways restriction is needed. But if we can treat these 4 nodes as a "big intersection node", then a simple "via-big-node" restriction should be sufficient.

But of course, if there really has some kind of via-way(s) restriction in real-life then this "big intersection" approach will be insufficient.

**Comment by miklcct** [comment] 2018-06-14 15:19
I have modelled this forbidden route as a restriction of multiple via ways:

https://www.openstreetmap.org/relation/7139227#map=17/22.27908/114.18234

Is there any better method for that?

**Closed** 2020-12-20 21:59 UTC
Labels: Feature Request
