### ISSUE TITLE
osrm-contract segfaults

### ISSUE THREAD

**Issue by kolstad** [Project-OSRM/osrm-backend#2618] opened 2016-07-03 12:53 UTC
This report replaces #2534 which I have closed (I hope).

After a successful 4+ hour run of osrm-extract, the osrm-contract program fails in just over five seconds with a segmentation fault.  I have attached a log that I hope has plenty of data in it.  Please let me know if you need more.

RK
[b.txt](https://github.com/Project-OSRM/osrm-backend/files/345035/b.txt)

**Comment by danpat** [comment] 2016-07-03 14:02
@kolstad Can you re-compile in debug mode and try again?

Do: `cmake -DCMAKE_BUILD_TYPE=Debug ..` from your build dir, then `make`

This should give us some line numbers when you run `gdb`.

Just to confirm, these aren't old `.osrm` files?  The output of `osrm-extract` is generally not usable with a different version of `osrm-contract`.

**Comment by kolstad** [comment] 2016-07-03 16:27
Here's the program run with gdb compiled with debugging.  Just a bit more output.

These are fresh files from yesterday's and today's compiles.

Thanks for any ideas you might have.

RK
[a2.txt](https://github.com/Project-OSRM/osrm-backend/files/345169/a2.txt)

**Comment by danpat** [comment] 2016-07-03 17:00
@kolstad Hmm, thanks for the updated backtrace - that points at some code that was changed very recently (in the last few days), so there's probably a bug.  I'll see if I can re-produce the problem.

**Comment by kolstad** [comment] 2016-07-08 20:41
I'll be very  happy to help test this stuff on north-american-latest.  My current status is that even
the first step won't run to completion any more :( .

RK

**Comment by danpat** [comment] 2016-07-08 22:15
@kolstad I've tried to reproduce this problem but I can't.

I did the following:

1. Grab `north-america-latest.osm.pbf` from GeoFabrik
2. Grab `master` from `osrm-backend`
3. Compile
4. Run `osrm-extract -p ../profiles/car.lua north-america-latest.osm.pbf`
5. Run `osrm-contract north-america-latest.osrm`

I'm doing this on a machine with 120GB of RAM (Amazon EC2 r3.4xlarge) and it takes about 30 minutes to run `osrm-extract`, then another hour to run `osrm-contract`.  The error you're seeing is happening right at the beginning of what `osrm-contract` is doing.

Can you please *confirm* that you're using `osrm-extract` *AND* `osrm-contract` together from the same code version? Particularly on `master`, there are constant changes happening, and if you're using an old `.osrm` file generated with a previous build of `osrm-extract`, then you can expect random errors to occur.

I notice in your logfiles that you're downloading `master.zip`, then running just `osrm-contract`.  This will not work if your `.osrm` files are old.

**Comment by kolstad** [comment] 2016-07-08 22:18
Honestly, I've tried to follow the directions perfectly -- never more than
12 hours between dowloading software, etc.

I don't have 120GB, I fear, on my cloud machine.  I'll follow your
directions again (tomorrow) and guarantee that everything is in sync. I
wouldn't be surprised if the issue here is slightly limited RAM/swap/Disk.

Please advise how I grab the latest master (unless it's obvious).

Expect to hear back within 24 hours.

RK

  ====================================================================
            /\      Rob Kolstad                                 Delos
     /\    /  \     rob.kolstad@gmail.com   15235 Roller Coaster Road
    /  \/\/    \    +1 719 481 6542        Colorado Springs, CO 80921
   /    \ \     \                              Phone: +1 719 481 6542
  ====================================================================

**Comment by danpat** [comment] 2016-07-08 22:22
@kolstad `git clone git@github.com:Project-OSRM/osrm-backend.git` is how I do it.

The `extract` and `contract` processes are very data/CPU heavy.  As long as you stick with 64bit Intel machines and the same OS version if possible, it can be worth renting an Amazon machine temporarily to save yourself some time (between differing architectures/OS versions, the data files can become incompatible).  You can rent them by the hour, so processing `north-america-latest.osm.pbf` can be done for a couple of dollars.

If you don't have an SSD in your VM then processing will be extremely slow.  If you can rent a big machine with lots of RAM (like I've done for this), then you can do everything in memory and it gets a lot faster.

**Comment by kolstad** [comment] 2016-07-08 22:24
processing remotely involves sending back files -- and even databses if
you're building map tiles -- that seem prohibitively large.

I spent $100 on the LUA memory leak problem, but I'll try not to be gun shy
doing it again :) .  I'm on Linode and they make it pretty easy to go up
and down.

RK

  ====================================================================
            /\      Rob Kolstad                                 Delos
     /\    /  \     rob.kolstad@gmail.com   15235 Roller Coaster Road
    /  \/\/    \    +1 719 481 6542        Colorado Springs, CO 80921
   /    \ \     \                              Phone: +1 719 481 6542
  ====================================================================

**Comment by danpat** [comment] 2016-07-08 22:50
@kolstad For processing `north-america-latest.osm.pbf` quickly, I *think* you can probably do it all in RAM on a 64GB machine.  I'm only using a 120GB machine because I'm dealing with `planet.pbf` a lot.

If $$$ are important to you, then I would stick to tagged releases, rather than using `master` which often contains unstable code.  Importantly, if you update your version, you must re-run `osrm-extract` *and* `osrm-contract`, you can't just do one.

**Comment by kolstad** [comment] 2016-07-09 21:07
With the latest software:

kolstad@ubuntu:~/osrm$ osrm-extract -v
[info] v5.3.0

kolstad@ubuntu:~/osrm$ osrm-contract -v
[info] v5.3.0

I was able to perform the builds exactly as you specified!

 TTTTTTT
    T      H    H     AA     N    N   K    K
    T      H    H    A  A    NN   N   K   K
    T      HHHHHH   A    A   N N  N   KKKK
    T      H    H   AAAAAA   N  N N   K  K
    T      H    H   A    A   N   NN   K   K
    T      H    H   A    A   N    N   K    K



   Y   Y    OOOO    U    U
    Y Y    O    O   U    U
     Y     O    O   U    U
     Y     O    O   U    U
     Y     O    O   U    U
     Y      OOOO     UUUU

I believe that in global geography we are neighbors -- I am in north
central colorado.  Do come by and see the castle when you're heading out in
this
direction!

May I suggest that you augment the quick-start guide on the main
git page with information that has data like this:

* the 1.5 MB zip file creates osrm-backend-master/, a directory with
  954 files which consume just under 8 MB of disk space. It is in
  this directory that one performs the build sequence which requires
  about 7.5 minutes on a moderate 8-core system.

* Larger maps require plenty of disk space. North America, e.g., requires
  7.3 GB for the raw data from geo-fabrik. Once all the index files are
  created, the two dozen files (including the map) require 38.3 GB.

* osrm-extract requires the stxxl file of size XXX (I used 100GB which
  appears to be way more than is needed) and RAM+Swap of XXX for
  a large map like North America. One particular build for North America
  required 176 minutes  of CPU time across 104 minutes of real time (on
  an 8 core modern processor with SSDs).

* osrm-contract requires the stxxl of size at least 3GB when running
  with RAM+Swap of 23GB + 150GB.  I don't know how much of the
  swap was used. To contract North America required 985 minutes of CPU
  across 131 minutes of CPU time (8 cores).

These things set expectations so folks don't sit watching a blinking cursor
for ten minutes wondering, "Is it doing anything/".

>> If there's any way to detect when stxxl is full vs. out of RAM/swap,
     it'd be really terrific to emit prescriptive messages like "You need
more
     swap" or "increase the allocation in your .stxxl file".

Thanks again for seeing this through.

---------------------------------------- QUESTION
------------------------------------
Are you also involved in the tile server?
-----------------------------------------------------------------------------------------------

RK

PS:  I'm still missing a LUA library named LUAJIT and, I see after checking
the log, Doxygen (which I haven't tried to load). I really tried to get
LUAJIT
loaded, but failed.

  ====================================================================
            /\      Rob Kolstad                                 Delos
     /\    /  \     rob.kolstad@gmail.com   15235 Roller Coaster Road
    /  \/\/    \    +1 719 481 6542        Colorado Springs, CO 80921
   /    \ \     \                              Phone: +1 719 481 6542
  ====================================================================

**Comment by danpat** [comment] 2016-07-11 14:25
Yeah, having more insight to how much STXXL gets used would be helpful.  I went digging at one point but couldn't find anything (peak usage, etc).

This ticket has been sitting around for a while, it would be great if someone has time to implement it: https://github.com/Project-OSRM/osrm-backend/issues/2445

Nothing else actionable here, closing.

**Closed by danpat** 2016-07-11 14:25 UTC
Labels: Bug Report
