### ISSUE TITLE
Use Bridleways when explicitly allowed to

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3335] opened 2016-11-17 13:08 UTC
As reported in https://github.com/mapbox/mapbox-directions.js/issues/109:

We don't route over `highway=bridleway` + `foot=yes` or `bicycle=yes`.

Example way: https://www.openstreetmap.org/way/32713960#map=19/29.62293/-99.20729&layers=D
Bridleways in OSM: http://wiki.openstreetmap.org/wiki/Tag:highway%3Dbridleway

The OSM Wiki makes it clear there are country-specific regulations.
Together with explicit yes-tags we should route over them.

Tasks:
- [x] add Cucumber tests for routability and speeds with and without explicit yes-tags - `features/{bicycle, foot}access.feature`, https://github.com/Project-OSRM/osrm-backend/pull/3348
- [ ] add support to profiles - `profiles/{bicycle, foot}.lua`
- [ ] check other tags we currently don't route over but should route over when there are explicit yes-tags

http://wiki.openstreetmap.org/wiki/Key:access

**Comment by MoKob** [comment] 2016-11-22 09:06
@daniel-j-h While @karenzshea has added some tests (that work without modification), I'd be really interested to see what has been broken here.
From the OSM data, the path in question is a single way in OSM data. This includes both the part that is routed over and the part that isn't.
Given that we break them into different parts, I'd be curious to why a single part of that path might end up  routed over, and another one didn't.

Has anyone been able to reproduce the issue in question on an extract? In the example?

**Comment by daniel-j-h** [comment] 2016-11-22 10:00
Hrm this was not what I expected, sorry for the issue description then.

I can put reproducing this locally with the bike and walk profile on my plate.

**Comment by daniel-j-h** [comment] 2016-11-22 10:10
For the record testing this on both our cycling and walking stacks works now

![route](https://cloud.githubusercontent.com/assets/527241/20519667/1b10cb12-b0a4-11e6-8a24-4d87629e67a2.png)


even though the way in question was last edited a month ago - the path going east  7 days ago.

**Comment by daniel-j-h** [comment] 2016-11-22 10:53
Okay I can't reproduce this locally - @MoKob threw in the idea of a broken CH order. Here's what I used to run the pipeline in a loop and detecting changes in duration.

```bash
#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

# Run this script in a loop to detect the unroutable bridleway behavior found in #3335.
# Returns non-zero exit code on failure.

./osrm-extract -p ../profiles/bicycle.lua osrm-issue-3335.osm.pbf  &> /dev/null
./osrm-contract osrm-issue-3335.osrm  &> /dev/null

./osrm-routed osrm-issue-3335.osrm  &> /dev/null &
readonly routed=$!
sleep 0.1

readonly duration=$(http 'http://localhost:5000/route/v1/cycling/-99.20829,29.62307;-99.20656,29.62273' | jq '.routes[0].duration')
kill ${routed}

if [ "${duration%.*}" != "48" ]; then
    echo "Gotcha - broken CH order; keep datasets!"
    exit 1
fi
```

I did this on a dataset cut to the area in question, but as I said can't reproduce the issue so far ..

**Comment by TheMarex** [comment] 2016-11-23 10:15
Capturing from chat:

- We added tests to capture this https://github.com/Project-OSRM/osrm-backend/pull/3348
- There is a low likelihood that is was caused by some deeper problems with the routing
- If we see this again we should investigate more deeply

Closing for now.

**Closed by TheMarex** 2016-11-23 10:15 UTC
Labels: Profile, Starter Task
