### ISSUE TITLE
OSRM Profile used

### ISSUE THREAD

**Issue by eltonramos** [Project-OSRM/osrm-backend#5275] opened 2018-11-19 01:42 UTC
Hi.
Hi, I'm using osrm
but the results are not the same as the sample address
http://map.project-osrm.org/

in your example
![image](https://user-images.githubusercontent.com/20299808/48681768-93f3a580-eb8b-11e8-8a8e-71df3a5794df.png)

on my server using the profile car.lua
![image](https://user-images.githubusercontent.com/20299808/48681770-9e15a400-eb8b-11e8-9f8c-7f63abc21b25.png)

Is there a profile you use other than the available pattern?

tks
att

**Comment by systemed** [comment] 2018-11-19 12:55
dupe of https://forum.openstreetmap.org/viewtopic.php?id=64523

**Comment by daniel-j-h** [comment] 2018-11-21 14:30
https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server

**Closed by daniel-j-h** 2018-11-21 14:30 UTC
