### ISSUE TITLE
Getting distance cost table using node binding

### ISSUE THREAD

**Issue by carlosen14** [Project-OSRM/osrm-backend#5208] opened 2018-09-17 17:43 UTC
Looking into the docs, the returning object from a table function, it says that there will be 

> Returns Object containing `durations`, `sources`, and `destinations`.

Using the http method you get that and also distance, using the `annotation `flag.

Now i will test the v5.18 version because i am actually using this on the web server for http requests. And i tried to run v5.19 but throws an error saying 

> File is incompatible with this version of OSRM: /path/mexico-latest.osrm.cells prepared with OSRM 5.18.0 but this is v5.19.0 (at include/storage/tar.hpp:204)

I am using `MLD` algorithm.
Question.. Is v5.19 returning distance costs table in the result?

thanks!

**Comment by carlosen14** [comment] 2018-09-17 17:46
Do i have to modify car.lua file to set from `weight_name = 'routability'` to `weight_name = 'distance'`?

**Comment by chaupow** [comment] 2018-09-27 12:11
> Do i have to modify car.lua file to set from weight_name = 'routability' to weight_name = 'distance' and then renerate .osrm map files?

No that is not neccessary. The `weight_change` in profile will change the behaviour on what is _minimized_ when finding shortest paths. Whether the table service returns distance or durations is not related to that.

> Question.. Is v5.19 returning distance costs table in the result?

Distance costs [were released with v5.18](https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.18.0) so you should be able to get distances with 5.18.
You can find the docs for 5.18 [here](https://github.com/Project-OSRM/osrm-backend/blob/v5.18.0/docs/http.md#table-service) and it also includes docs on how to use the `annotations` flag

> File is incompatible with this version of OSRM: /path/mexico-latest.osrm.cells prepared with OSRM 5.18.0 but this is v5.19.0 (at include/storage/tar.hpp:204)

I have to admit I don't quite understand what you're trying to do here ☝️ 
It sounds like you preprocessed the data with 5.18 but run your engine on 5.19 using the old preprocessed data. You can either run preprocessing again with 5.19 or switch back to using 5.18.
Was there something that did not work with 5.18 and that you're trying to achieve with 5.19.?

---
Unrelated: We're working on improving distances tables in 5.20. so stay tuned 😎

**Comment by carlosen14** [comment] 2018-09-27 14:11
Thanks for your answer. 

Ok it is my bad for not saying i am working with NodeJS bindings, not HTTP. [Here](https://github.com/Project-OSRM/osrm-backend/blob/5.18/docs/nodejs/api.md#table) it says that `function table` will only return `durations`, `sources`, and `destinations`. 

> No that is not necessary. The weight_change in profile will change the behaviour on what is minimized when finding shortest paths. Whether the table service returns distance or durations is not related to that.

I thought this was a possibility because in car.lua says `routability`, and `distance` is already commented.

> I have to admit I don't quite understand what you're trying to do here ☝️

Well, i mean that I am actually using v5.18, knowing v5.19 is actually the newest. I prepared the map files using v5.18, but I couldn't use Node binding v5.19 because it throws an error saying that I am not able to load map files prepared with a older OSRM version. I don't know if I am able to use an even older OSRM version, but a newer is not possible, so I wasn't able to test if v5.19 was giving the distance table in route function.

Of course I am waiting for v5.20, I already read a few days ago that user Danpat already achieved that distance cost table for this version, I couldn't find it to post it, but it said it was some milestone for this.

For now, I am generating the cost table one by one and getting distance and duration using `route` function.

**Comment by chaupow** [comment] 2018-09-28 20:17
> Ok it is my bad for not saying i am working with NodeJS bindings, not HTTP

Ok I can reproduce it now 😕
I will look into this. This looks like a bug.

>  I don't know if I am able to use an even older OSRM version

If you need distances in matrices I am afraid you might not 😞 Let me get back to you!

**Comment by carlosen14** [comment] 2018-09-28 20:54
> This looks like a bug.

I thought this was normal due some functions API requirements.

> If you need distances in matrices I am afraid you might not

No problem, i achieved this by requesting one by one.

Actually I ended up working with tag v5.20-alpha-2, because i generate my maps with docker `osrm/osrm-backend:latest`  is using this 🤨, it might be unstable but it is working, and that's enough!

Thanks for your time!

**Comment by chaupow** [comment] 2018-09-28 21:07
>  it might be unstable but it is working, and that's enough!

Ok cool. Otherwise, I looked into this a bit further and if you use the node bindings with `npm install osrm@5.18.0`, it should work. If you need it, give it a try :) 

Will close this now.

**Closed by chaupow** 2018-09-28 21:07 UTC
Labels: Bug Report
