### ISSUE TITLE
OSRM-routed hanging

### ISSUE THREAD

**Issue by SD-OSRM** [Project-OSRM/osrm-backend#4090] opened 2017-05-25 12:07 UTC
Hi,

We have the problem with OSRM-routed for Linux (virtual server with Ubuntu 16.04).
Two instances of OSRM-routed are launched on different ports.
One instance works fine, however another one freezes every several days, probably because it receives much more requests.

We tried 5.7.0 and 5.5.0 OSRM version. It did not help.
Could you please advise what can we do to prevent OSRM-routed from hanging?
After hanging all requests to the service fail by timeout.

Thank you!

**Comment by TheMarex** [comment] 2017-05-29 12:13
Why are you running two instances of `osrm-routed` on two different ports?

**Comment by SD-OSRM** [comment] 2017-05-29 12:39
We have two types of clients - A and B.
There are much more requests from B-type clients than from A-type clients.
We tried to launch only one OSRM-routed instance, however in this case response to A-type clients is significantly slower and probability of the timeout is higher.
Thus, we decided to launch two instances of OSRM-routed on different ports. One instance for requests from A-type clients and another instance for requests from B-type clients. Requests from A-type clients are processed much faster in this case.
Such a scheme works fine on Windows OS. 
We faced the problem only on Ubuntu OS.

**Comment by emiltin** [comment] 2017-05-29 12:43
osrm-routed is not intended for production. consider instead node-osrm https://github.com/Project-OSRM/osrm-backend/blob/master/docs/nodejs/api.md

**Comment by daniel-j-h** [comment] 2017-06-02 13:44
Can you provide more details here
- Are you using the shared memory option aka `osrm-datastore`?
- Do you see v5.7 or v5.5 hanging?
- Do you see specific requests in the logs you can show when it starts to hang?

**Comment by anthologist** [comment] 2017-06-05 12:22
Kind of different, but hanging here too (I just use one instance, not like OP):
Ubuntu 16.04, OSRM 5.7, I followed the guide and run:
osrm-extract file.osm.pbf -p profiles/car.lua
osrm-contract file.osrm
osrm-routed file.osrm

The last command hangs on:
[info] load names from: "file.osrm.names"

Htop says that the process stays in D status, much memory is used but no CPU.

**Comment by daniel-j-h** [comment] 2017-06-05 16:12
Can you try and reproduce this with a file as small as possible and then share with us for to debug? 

Otherwise what you have to do is build osrm in debug mode (`cmake .. -DCMAKE_BUILD_TYPE=Debug`), run the pipeline again, and then attach a debugger (gdb) and show us the backtrace (bt).

**Comment by anthologist** [comment] 2017-06-06 10:13
@daniel-j-h Ok, I tried it with just Berlin and everything works good. Do you think it's just a matter of time to load names or the big one may be corrupt? (The big one was Europe+North America)

**Comment by daniel-j-h** [comment] 2017-06-06 12:14
Depends on if it hangs forever or continues after a while.

Also how do you concatenate Europe and North America? I hope you already concatenate OSM files because modifying OSRM files will lead to undefined behavior.

**Comment by anthologist** [comment] 2017-06-06 13:30
Yes, I merged the two pbf files before with osmosis.
I'll update you when I discover if it continues after a while.

**Closed** 2017-06-07 10:55 UTC
