### ISSUE TITLE
Implement MLD path unpacking

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3759] opened 2017-02-28 21:50 UTC
Breaking out of https://github.com/Project-OSRM/osrm-backend/issues/3351:

High-Level Unpacking algorithm:
- Top-Down: For a pair of border vertices `i` and `j` at level `l` find shortest path at level `l-1` only using the cell matrices of `l-1`.
- Add resulting edges of the shortest path to a stack
- Unpack pair from the queue until we hit level 0 at which we need to do a search on the base graph
- Assemble resulting route on the base graph and return result as list of Edge-Based-Edge ids

Implementation brain dump:

- Vector of NodeIDs containing the final path
- Stack that contains `std::tuple<LevelID, NodeID, NodeID>`
- Initialization: Put unpacked path on stack in reverse order as edge pairs. The level of each edge is `min(query_level(s, t, edge_start_node), query_level(s, t, edge_target_node))`
- Take an arc from the stack check if its a boundary arc:
   - If yes it is already unpacked and the target node  to the final path.
   - If no it is a clique arc, we need to do the actual clique edge unpacking work.

Unpacking an edge:
  - Goal: Replace the clique edge on level `l` in cell `C` through a list of clique edges and border edges on level `l-1`.
  - For that we need to execute a bidirectional dijkstra search in the graph implied by the clique arcs of all subcells of `C` and their boundary edges
   - For that we need a custom dijkstra implementation like here: https://github.com/Project-OSRM/osrm-backend/pull/3738/files#diff-756eb99f3ffc32006906e2d9c2455968R93
   - Add all edges of the found path back to the stack in reverse order

/cc @oxidase

**Comment by oxidase** [comment] 2017-03-05 19:09
I have implemented path unpacking for customization checks in mld/customization branch for 1-to-1 compare with respect to CH algorithm. At the moment performance comparison is not possible because contractor in the branch skips contraction. 
Here some visual representation of MLD search spaces (inserted ebg nodes, green->cyan is the forward heap, read->violet is the reverse heap, yellow node is the middle point):
* Munich -> Stuttgart https://gist.github.com/oxidase/c0a7e4657c32660dcc87d5357020badb
  MLD routing 0.038239 seconds, unpacking 0.007025 seconds
* Munich -> Ingolstadt https://gist.github.com/oxidase/5203ef1840f68d46a313cc6515841e5a
  MLD routing 0.0173 seconds, unpacking 0.006534 seconds

There are at least two possibilities for performance improvement:
* heap refactoring as ~50-75% time spent in binary heap methods #3764 
* upper bound usage makes forward and reverse searches as two full range searches from start to target. The current implementation neglects bi-directional search speedup. As far as i understand it is needed because of multiple starting and target points can be added to heaps. @TheMarex please could you clarify if it can be refactored or it is made by design?

**Comment by oxidase** [comment] 2017-03-17 14:56
Closed via #3788

**Closed by oxidase** 2017-03-17 14:56 UTC
Labels: MLD
