### ISSUE TITLE
Segmentation faults on demo server

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2649] opened 2016-07-12 08:29 UTC
We are seeing segmentation faults on the demo server. I just merged https://github.com/Project-OSRM/osrm-backend/pull/2646 to get the requests that are probably causing these.

I'm going to re-run building osrm-backend on the server. Someone needs to take a look at the crashing requests later. This is a blocker for 5.3.0

/cc @daniel-j-h @danpat @MoKob

**Comment by daniel-j-h** [comment] 2016-07-12 09:05
I'll have a look today.

**Comment by daniel-j-h** [comment] 2016-07-13 09:32
Nothing so far. Last hiccup was on 07/06/2016 12:14:57.

I'm not seeing the crashing request, but seems like a ton of tile requests, as in

    http://router.project-osrm.org/tile/v1/car/tile(8673,4728,14).mvt

around this area. Looks like somewhere in Norway (60.31606836555201, 10.56884765625).

**Comment by MoKob** [comment] 2016-08-31 08:59
@TheMarex was this the map-matching you fixed or a different issue?

**Comment by MoKob** [comment] 2016-08-31 09:00
Or possibly the via-route issue with u-turns enabled?

**Comment by MoKob** [comment] 2016-08-31 09:03
From voice with @daniel-j-h not reproducible anymore, closing here.

**Closed by MoKob** 2016-08-31 09:03 UTC
Labels: Bug Report
