### ISSUE TITLE
indicate ferry parts of route

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#283] opened 2012-06-01 12:47 UTC
just like pushing of bikes should be indicated with a different color on the route, it might be useful to indicate ferries and trains on the route?

**Comment by Stalfur** [comment] 2015-06-29 09:58
The text field should really say it is by ferry, the first 200 meters in step 10 in [this route](http://www.openstreetmap.org/directions?engine=osrm_car&route=-19.9861%2C23.4224%3B-18.8167%2C22.4209#map=8/-19.368/22.606) are by ferry but that is not indicated in the text field itself.

Perhaps it should be split up so "10. 200 meters by ferry" would be displayed.

**Comment by emiltin** [comment] 2015-06-29 13:13
The travel mode is already send to the front end. On www.ibikecph.dk we use this to tell the user where the bike should be pushed, and when you're going with a ferrry.

**Comment by Stalfur** [comment] 2015-06-29 13:30
So this is a problem on OSM.org with display?

**Comment by Stalfur** [comment] 2015-06-30 00:02
According to https://github.com/openstreetmap/openstreetmap-website/issues/1000 then OSRM itself doesn't publish ferry details?

**Comment by TheMarex** [comment] 2015-07-01 08:48
It is published:

```
curl http://router.project-osrm.org/viaroute?z=14&output=json&geometry=false&instructions=true&loc=-19.9861,23.4224&hint=tiRGDAiJvwwAAAAADwAAADUAAAB-AAAAQAAAAC3bugMAAAAAfwnP_otlZQEEABEA&loc=-18.8167,22.4209&hint=S1zhCcU7wgwAAAAAewAAAAUBAACIBAEArYcAAOk8hAYAAAAAj-fg_pQiVgG2ABEA&checksum=2214934300
```

```
{
    "found_alternative": false,
    "hint_data": {
        "checksum": 2214934300,
        "locations": [
            "tiRGDAiJvwwAAAAADwAAADUAAAB-AAAAQAAAAC3bugMAAAAAfwnP_otlZQEEABEA",
            "S1zhCcU7wgwAAAAAewAAAAUBAACIBAEArYcAAOk8hAYAAAAAj-fg_pQiVgG2ABEA"
        ]
    },
    "route_instructions": [
        [
            "10",
            "",
            123,
            0,
            26,
            "122m",
            "SW",
            225,
            1
        ],
        [
            "7",
            "",
            111,
            2,
            13,
            "110m",
            "E",
            103,
            1
        ],
        [
            "1",
            "",
            77,
            3,
            9,
            "77m",
            "SE",
            115,
            1
        ],
        [
            "3",
            "Pulane Rd",
            49,
            4,
            6,
            "49m",
            "SW",
            219,
            1
        ],
        [
            "7",
            "Tsaro Street",
            232,
            5,
            27,
            "231m",
            "SE",
            134,
            1
        ],
        [
            "3",
            "Tsheko Tsheko Rd (A3)",
            5999,
            9,
            274,
            "5999m",
            "SW",
            225,
            1
        ],
        [
            "1",
            "A3",
            90908,
            44,
            4142,
            "90907m",
            "SW",
            239,
            1
        ],
        [
            "3",
            "A35",
            291960,
            332,
            13674,
            "291959m",
            "NW",
            330,
            1
        ],
        [
            "1",
            "",
            464,
            1090,
            39,
            "464m",
            "N",
            2,
            1
        ],
        [
            "1",
            "",
            6004,
            1095,
            624,
            "6004m",
            "N",
            352,
            2
        ],
        [
            "1",
            "",
            73,
            1122,
            6,
            "72m",
            "SE",
            114,
            1
        ],
        [
            "1",
            "",
            345,
            1123,
            29,
            "345m",
            "SE",
            114,
            1
        ],
        [
            "1",
            "",
            95,
            1125,
            8,
            "95m",
            "SE",
            124,
            1
        ],
        [
            "1",
            "",
            147,
            1126,
            12,
            "146m",
            "SE",
            124,
            1
        ],
        [
            "1",
            "",
            2989,
            1127,
            250,
            "2988m",
            "SE",
            124,
            1
        ],
        [
            "1",
            "",
            203,
            1132,
            17,
            "203m",
            "SE",
            133,
            1
        ],
        [
            "1",
            "",
            6198,
            1133,
            519,
            "6198m",
            "SE",
            133,
            1
        ],
        [
            "1",
            "",
            79813,
            1144,
            12,
            "79812m",
            "E",
            106,
            1
        ],
        [
            "15",
            "",
            0,
            1327,
            0,
            "0m",
            "N",
            0
        ]
    ],
    "route_name": [
        "A3",
        "A35"
    ],
    "route_summary": {
        "end_point": "",
        "start_point": "",
        "total_distance": 485789,
        "total_time": 26344
    },
    "status": 0,
    "status_message": "Found route between points",
    "via_indices": [
        0,
        1328
    ],
    "via_points": [
        [
            -19.986048,
            23.422348
        ],
        [
            -18.815088,
            22.422165
        ]
    ]
}
```

The problem is that the instruction gets merged with a longer segment after it because there is no turn and the street name is the same.

**Closed as completed** 2016-12-13 14:33 UTC
Labels: Feature Request

**Comment by Stalfur** [comment] 2016-12-13 15:10
> (Also check the satellite imagery there, it's beautiful)

The Okavango Delta is one of the [Seven Natural Wonders of Africa](https://en.wikipedia.org/wiki/Seven_Natural_Wonders_of_Africa)

**Comment by daniel-j-h** [comment] 2016-12-14 08:33
@emiltin at least not on the way http://taginfo.openstreetmap.org/tags/route=ferry#combinations some people seem to code it into the name as in

    Ferry XA  A <-> B
