### ISSUE TITLE
SharedMonitor hangs in `notify_all` on linux

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3911] opened 2017-04-06 13:22 UTC
Using boost 1.63 on Arch Linux the following steps will make `osrm-datastore` hang:

- Checkout https://github.com/Project-OSRM/osrm-backend/pull/3766
- Compile in debug mode (assertions)
- Run `cucumber features/guidance/roundabout.feature:687` three times
- First two times should crash, third time will timeout
- Check for running `osrm-datastore` process

This work if I disable `USE_BOOST_INTERPROCESS_CONDITION` which enables using Michael's condition variable implementation.

/cc @oxidase

**Comment by daniel-j-h** [comment] 2017-04-06 14:42
Can reproduce in a nix shell with glibc-2.25.

**Comment by TheMarex** [comment] 2017-04-06 14:45
This was most likely introduced by https://sourceware.org/git/?p=glibc.git;a=blob;f=NEWS;h=3590878a98f1a90b3df297e2e74b8b13dbb0487c;hb=HEAD#l237 which reimplements the `pthread_cond_broadcast` code. This is what `boost::interprocess` uses under the hood on linux.

Workaround is commenting out https://github.com/Project-OSRM/osrm-backend/blob/master/include/storage/shared_monitor.hpp#L15

**Comment by TheMarex** [comment] 2017-04-07 15:31
This is probably a glibc bug, will not hit us until Ubuntu 17.10, moving to next release.

**Comment by oxidase** [comment] 2017-04-23 19:46
Reported bug https://sourceware.org/bugzilla/show_bug.cgi?id=21422 with a test code that reproduces the issue with glibc 2.25 without OSRM code.

**Comment by oxidase** [comment] 2017-04-25 13:32
The bug ticket was rejected as invalid because behaviour of `pthread_cond_wait` in the POSIX standard for the particular situation is not defined. Proposed solutions
> one approach would be to catch signals and use POSIX' cancellation to cancel the pthread_cond_wait; another option might to use nonblocking synchronization such as C11 atomics. 

* catching signals will not allow to cancel waiting in case of OOM SIGKILL
* c++11 atomic primitives can be realized with busy wait

At the moment i don't see a possibility to use pthread_cond wth glibc 2.25, one possibility would be to use a semaphores queue another a busy-wait loop with c++11 atomics

**Comment by TheMarex** [comment] 2017-04-25 13:55
@oxidase I think we should enable the semaphore queue on all OS by default. That at least guarantees consistent behavior.

I think it is problematic that the glibc devs put this behavior change down as `WONTFIX`, but at least they are aware of it now and there is a paper trail.

**Comment by oxidase** [comment] 2017-05-08 15:38
Closed via  #4020

**Closed by oxidase** 2017-05-08 15:38 UTC
Labels: Bug Report
