### ISSUE TITLE
It seems like OSRM doesn't support country specific defaults according to osm wiki

### ISSUE THREAD

**Issue by d1g** [Project-OSRM/osrm-backend#1633] opened 2015-08-29 08:44 UTC
http://wiki.openstreetmap.org/wiki/Key:access is incomplete list for [bicycle restrictions](https://github.com/Project-OSRM/osrm-backend/blob/fd6daa580a7d3c7e2074a9c6ca1da41268274d26/features/bicycle/access.feature)

http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions is way better resource, please review access-relevant code again.

OSRM should support country-specific rules, otherwise routing results will be questionable at very least and illegal/useless in the worst case.

**Comment by TheMarex** [comment] 2015-08-29 10:15
Duplicate of https://github.com/Project-OSRM/osrm-backend/issues/333

**Closed by TheMarex** 2015-08-29 10:15 UTC
