### ISSUE TITLE
osrm-contract: 90% => killed

### ISSUE THREAD

**Issue by tds4u** [Project-OSRM/osrm-backend#4580] opened 2017-10-06 05:24 UTC
Everytime I want to **contract** bicycle I receive "Killed" after about 90%.
**Extracting** for car, bicycle and foot without problems AND without extra swap space via fallocate.

Hardware:
```
Processor: Intel(R) Xeon(R) CPU E5-2630 v4
Threads: 40
Memory: 256GB DDR4 ECC RAM
Swap: 8GB as partition + 64GB with fallocate
Disk: /dev/sda2       1.8T  159G  1.6T  10% /
```
Output:
```
cd /scripts/pbf/bicycle/
root@server1:/scripts/pbf/bicycle# osrm-contract planet-latest.osrm
[info] Input file: planet-latest.osrm
[info] Threads: 40
[info] Reading node weights.
[info] Done reading node weights.
[info] Loading edge-expanded graph representation
[info] merged 2392002 edges out of 1785558812
[info] initializing node priorities... ok.
[info] preprocessing 391530481 (90%) nodes...
[info] . 10% . 20% . 30% . 40% . 50% . 60% .[renumbered] 70% . 80% . 90% Killed
```

How can I help you to find the error? gdb is not really working with my build.

**Comment by daniel-j-h** [comment] 2017-10-06 09:28
First thing I would check is `dmesg` - maybe the Linux OOM killer is taking you out here.

If not then we need more details:
- Are you running the default profile?
- Which OSRM version?
- STXXL or not?

**Comment by tds4u** [comment] 2017-10-06 12:46
OSRM version v5.12.0 - I think without STXXL (how can I check this)?
Default profiles. Profile car was working till the end. Bicycle and foot not.

OOM sounds interesting :-(
```
[317356.273343] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[317356.273344] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[317356.273345] Node 1 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[317356.273346] Node 1 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[317356.273347] 5641 total pagecache pages
[317356.273348] 2564 pages in swap cache
[317356.273350] Swap cache stats: add 121773048, delete 121769312, find 18811813/24217786
[317356.273351] Free swap  = 0kB
[317356.273351] Total swap = 132812088kB
[317356.273352] 67079861 pages RAM
[317356.273353] 0 pages HighMem/MovableOnly
[317356.273354] 1069410 pages reserved
[317356.273354] 0 pages hwpoisoned
[317356.273355] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[317356.273366] [ 1611]     0  1611     3005      375      11       3      782             0 haveged
[317356.273369] [ 1630]     0  1630    12171      268      24       3      944         -1000 systemd-udevd
[317356.273371] [ 1837]     0  1837     7416      402      18       3       69             0 cron
[317356.273373] [ 1838]   105  1838    11309      432      27       3      120          -900 dbus-daemon
[317356.273375] [ 1843]     0  1843    62529      437      28       3      517             0 rsyslogd
[317356.273376] [ 1846]     0  1846     1054      293       8       3       34             0 acpid
[317356.273378] [ 1849]     0  1849    11667      487      26       3      144             0 systemd-logind
[317356.273380] [ 2140]     0  2140     3634      278      12       3       39             0 agetty
[317356.273382] [31787]  1000 31787    16216      326      34       3      242             0 systemd
[317356.273384] [31788]  1000 31788    57556       11      45       3      450             0 (sd-pam)
[317356.273386] [32019]     0 32019     8523      345      21       3       67             0 inetd
[317356.273387] [39053]     0 39053     7087      419      18       3      195             0 screen
[317356.273390] [39054]     0 39054     5000      447      14       3      162             0 bash
[317356.273391] [10671]     0 10671    79237      353      55       3      433             0 packagekitd
[317356.273393] [10685]     0 10685    71551      216      43       4      202             0 polkitd
[317356.273395] [30486]     0 30486     4678        1      14       3       43             0 daemon
[317356.273396] [30487]     0 30487     5004      437      14       3      130             0 aacraid-statusd
[317356.273398] [26207]     0 26207    29924     1953      62       4      112             0 systemd-journal
[317356.273400] [35691]     0 35691    12986      653      29       4     2123             0 munin-node
[317356.273402] [16758]     0 16758     7351     3108      20       3        0             0 atop
[317356.273405] [28616]     0 28616    24835      245      51       3      207             0 sshd
[317356.273406] [28671]  1000 28671    24835      409      50       3      200             0 sshd
[317356.273408] [28678]  1000 28678     4972      389      14       3      141             0 bash
[317356.273410] [28737]  1000 28737    13756      394      31       3      112             0 su
[317356.273411] [28740]     0 28740     4991      486      14       3       73             0 bash
[317356.273413] [29073]     0 29073    17486      307      38       4      182         -1000 sshd
[317356.273416] [ 5763]     0  5763 100148382 65486611  192754     386 33125402             0 osrm-contract
[317356.273418] [ 6760]   114  6760    67183      430     127       3    31289             0 /usr/sbin/amavi
[317356.273419] [ 6761]   114  6761    67183      430     127       3    31289             0 /usr/sbin/amavi
[317356.273422] [11595]   117 11595   713319      452     144       5    12604             0 named
[317356.273424] [13470]     0 13470     1460       39       7       3       22             0 sleep
[317356.273425] [13826]     0 13826    13239      467      29       4       34             0 cron
[317356.273427] [13856]   119 13856     2792      340       9       3       57             0 sh
[317356.273429] [13857]   119 13857     2792      363      10       3       58             0 munin-cron
[317356.273431] [13859]   119 13859    45940     3221      79       3     1976             0 munin-update
[317356.273432] [13969]     0 13969    12986      877      29       4     1805             0 /usr/sbin/munin
[317356.273434] [14007]   119 14007    46637     3563      79       3     1782             0 /usr/share/muni
[317356.273436] [14008]     0 14008    12986     1088      29       4     1624             0 /usr/sbin/munin
[317356.273438] [14913] 65534 14913    29212     3745      32       3        0             0 ntp_2001:1640:1
[317356.273439] Out of memory: Kill process 5763 (osrm-contract) score 966 or sacrifice child
[317356.273591] Killed process 5763 (osrm-contract) total-vm:400593528kB, anon-rss:261944668kB, file-rss:1776kB, shmem-rss:0kB
[317366.930456] oom_reaper: reaped process 5763 (osrm-contract), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
What to do now? Increasing Swap on disk?

**Comment by daniel-j-h** [comment] 2017-10-06 14:15
Yeah you get oom killed - 256 GB RAM sound more than enough, though? Is this the default bike profile? @emiltin do you have numbers for the bike profile?

**Comment by tds4u** [comment] 2017-10-06 14:20
I'm using the default profiles at all. The car profile worked. Bicycle and foot not. I also tested with 256GB RAM plus 128GB Swap - same results. Strange is that killing happended ~70% with 128GB Swap and ~90% with 64GB Swap.

**Comment by emiltin** [comment] 2017-10-06 16:11
sorry we only work with smaller extracts

**Comment by tds4u** [comment] 2017-10-07 05:40
Okay, then I am available for testing the planet.pbf ;-)
PS: Full import of planet.pbf into PostgreSQL using max. 120GB of RAM in about 20h.

**Comment by danpat** [comment] 2017-10-08 04:24
@tds4u Here at Mapbox, we process (or at least, did until recently) the whole planet using the bike and walk profiles.  We ran it on AWS machines with 244GB of RAM.

However, we've recently stopped - we now pre-split the `planet.pbf` file into continents, and process them separately.  This requires smaller machines, and can be run in parallel.  There is no need to create one giant dataset for disconnected continents - there are no routes between them.  This *does* require a front-end proxy that can route requests to the proper dataset, but overall, it's a more effective approach than doing the whole planet.

Recent changes in OSRM have added to memory needs a bit (exclude flags, and a couple of other changes).  These may have pushed the bike/walk max memory needs for the planet over the 250GB mark - I don't know for sure, we haven't tested it explicitly.

**Comment by tds4u** [comment] 2017-10-08 08:40
Maybe you're right. But Europe, Asia und Africa - North, Middle and South America are connected. So it would be only a splitting into two files. Here in Germany we have man people from outer Europe who want to drive in their native country, e.g. to Asia or Africa. We can't split :-/

**Comment by TheMarex** [comment] 2017-10-08 21:30
The exclude flags should not have impacted OSM bike and walk, at least not in any significant way. This might be related to https://github.com/Project-OSRM/osrm-backend/issues/4584 - could be the contraction has a performance regression that only triggers for walk/bike (different contraction order).

> Maybe you're right. But Europe, Asia und Africa - North, Middle and South America are connected.

Yeah that is the "conditional" split we are using. 😉

**Comment by ZupoLlask** [comment] 2017-10-08 21:55
I'm getting the same kind of problem after v5.7.3...

It seems .stxxl is no longer used in v5.12.0 and newer versions. Can you please confirm this?

**Comment by oxidase** [comment] 2017-10-09 09:08
@ZupoLlask STXXL is still used but not enabled by default since v5.12.0. You can re-enable with `-DENABLE_STXXL=On` cmake argument

**Comment by tds4u** [comment] 2017-10-10 08:42
Tested with new release v5.13:
```
abc@xyz:/scripts/pbf/car# osrm-contract planet-latest.osrm
[info] Input file: planet-latest.osrm
[info] Threads: 40
[info] Reading node weights.
[info] Done reading node weights.
[info] Loading edge-expanded graph representation
[info] merged 820920 edges out of 1174255310
[info] initializing node priorities... ok.
[info] preprocessing 263242457 (89.6399%) nodes...
[info] . 10% . 20% . 30% . 40% . 50% . 60% .[renumbered] 70% . 80% . 90%
[info] Getting edges of minimized graph . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] initializing node priorities... ok.
[info] preprocessing 29881356 (10.1753%) nodes...
[info] [renumbered]. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Getting edges of minimized graph . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] initializing node priorities... ok.
[info] preprocessing 29881356 (10.1753%) nodes...
[info] [renumbered]. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Getting edges of minimized graph . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] initializing node priorities... ok.
[info] preprocessing 29881356 (10.1753%) nodes...
[info] [renumbered]. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Getting edges of minimized graph . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] initializing node priorities... ok.
[info] preprocessing 29881356 (10.1753%) nodes...
[info] [renumbered]. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Getting edges of minimized graph . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Contracted graph has 1722321902 edges.
[info] Contraction took 26802.3 sec
[info] Preprocessing : 26954.8 seconds
[info] finished preprocessing
[info] RAM: peak bytes used: 111503609856
abc@xyz:/scripts/pbf/car# cd ../bicycle/
abc@xyz:/scripts/pbf/bicycle# osrm-contract planet-latest.osrm
[info] Input file: planet-latest.osrm
[info] Threads: 40
[info] Reading node weights.
[info] Done reading node weights.
[info] Loading edge-expanded graph representation
[info] merged 2391996 edges out of 1785558668
[info] initializing node priorities... ok.
[info] preprocessing 391530416 (90%) nodes...
[info] . 10% . 20% . 30% . 40% . 50% . 60% .[renumbered] 70% . 80% . 90% Killed
abc@xyz:/scripts/pbf/bicycle#
```

**Comment by danpat** [comment] 2017-10-10 15:52
@tds4u Is anything else happening on this box?  You can expect `osrm-contract` to use a lot of memory, but if something else starts up and *also* uses a lot of RAM while the contract process is running, the OOM killer may choose the biggest user to kill (I'm not sure what the OOM killer strategy is).

**Comment by tds4u** [comment] 2017-10-11 04:21
No, the server ist an extra server for GIS related things. No other users. Stopped nearly all services to have more physical RAM. When I start contracting free RAM is about 245GB physical and 128GB swap.
Should I try to re-compile with STXXL enabled? Would this help?

**Comment by xydinesh** [comment] 2017-10-12 16:53
@tds4u #4584 might help you. Sounds like STXXL is helpful too.

```
osrm-extract data.osm.pbf -p profile.lua
osrm-partition data.osrm
osrm-contract data.osrm
osrm-routed data.osrm -a MLD
```

**Comment by daniel-j-h** [comment] 2018-05-08 09:36
Closing as not actionable. You have to get more memory :)

**Closed by daniel-j-h** 2018-05-08 09:36 UTC
