### ISSUE TITLE
Incorrect snapping. 

### ISSUE THREAD

**Issue by iaroslavzif** [Project-OSRM/osrm-backend#7005] opened 2024-07-22 13:19 UTC
Hello!

The profile is not snapping to the closest point from which the location can be accessible. In fact it snaps to nearest location, which sometimes is not direct linked to the destination. 

https://map.project-osrm.org/?z=17&center=59.500673%2C24.817783&loc=59.500782%2C24.814150&loc=59.495550%2C24.826905&hl=en&alt=0&srv=0

![Captură de ecran din 2024-07-22 la 16 18 50](https://github.com/user-attachments/assets/741e931d-9f42-4f71-8635-5db61ff069ef)

Thank you!

**Comment by jcoupey** [comment] 2024-07-29 20:49
> In fact it snaps to nearest location

That is the expected behavior.

The car profile naturally discards the service road because it is marked as private. So when pointing to "the closest point from which the location can be accessible", you're actually using additional information that OSRM does not have: namely that you'd expect to use the private road, by car? or maybe foot?

If you find the snapping logic limiting, a workaround would be to use the `nearest` endpoint to get a *list* of candidates (not only the closest one), then decide on which one you want to stand for your original location.

**Comment by iaroslavzif** [comment] 2024-07-30 06:26
Hi jcoupey. 

Indeed looks like an expected behaviour but it's not alright at all. It just snap to the closest open for car one from which the location is just not reachable....
You can use nearest, but in that case the car (if talking about car.lua) has to come to the point where the last routable segment meet the non routable/without car access (but open for walking etc.). 
The present logic creates a lot of disturbance and inconvenience, it's just to rudimental. 
Thank you!

**Comment by jcoupey** [comment] 2024-07-30 10:00
> the location is just not reachable

Here "reachable" only has a relevant meaning as defined by the profile. If using a car profile, the "Tuulekivi tee" way that can only be taken by foot is out of consideration as far as OSRM is concerned.

I'm not saying this is perfect, just that snapping in a "natural" way as you expect would involve a much more complex logic, maybe you need a multi-modal engine to account for car/foot switches. Or you want to first use `nearest` with a foot profile, then decide on the best "car routable" candidate location based on that.

**Comment by iaroslavzif** [comment] 2024-08-01 09:00
Thank you jcoupey!

Do you know by chance if there have been approaches to tackle this "issues" before. And if yes, at what extend. 

Thank you!

**Comment by iaroslavzif** [comment] 2024-08-13 09:16
Hi jcoupey!

You can see here another exemple: https://map.project-osrm.org/?z=16&center=58.246115%2C22.477094&loc=58.243998%2C22.473096&loc=58.254730%2C22.481804&hl=en&alt=0&srv=0

![Captură de ecran din 2024-08-13 la 12 15 54](https://github.com/user-attachments/assets/93e78b7d-7c7f-4cff-a99d-56a11007740e)


Thank you!

**Comment by jcoupey** [comment] 2024-08-20 09:38
> Do you know by chance if there have been approaches to tackle this "issues" before. And if yes, at what extend.

The closest I've heard about related to this is [doorways](https://thegeomob.com/podcast/episode-224). The fact that they're spinning a company for just that problem is in itself a hint that solving it is not a trivial task.

I think you can't reasonably expect OSRM to solve this as the `nearest` service is "just" a closest snapping. Your best bet is to use some snapping distance threshold as an indicator that you have extra work to do.

**Closed by jcoupey** 2024-08-20 09:38 UTC

**Comment by iaroslavzif** [comment] 2024-08-26 06:05
Thank you jcoupey!

I will have a look on it. 

Have a great day,
Iaroslav!
