### ISSUE TITLE
Problems with close points

### ISSUE THREAD

**Issue by alebh** [Project-OSRM/osrm-backend#1479] opened 2015-05-15 18:27 UTC
I have some problems routing close points
http://osrm.at/cn9

**Comment by woodbri** [comment] 2015-05-15 19:47
This appears to be a duplicate of #1474 but another good example of the problem.

**Comment by woodbri** [comment] 2015-05-18 15:55
This looks like it is working correctly on map.project-osrm.org now on develop after revering 11c6713

**Comment by TheMarex** [comment] 2015-05-18 16:21
Nice. Marking this as fixed.

**Closed by TheMarex** 2015-05-18 16:21 UTC
