### ISSUE TITLE
Configurable max search radius

### ISSUE THREAD

**Issue by ghoshkaj** [Project-OSRM/osrm-backend#4719] opened 2017-12-05 15:55 UTC
Similar to `max_locations` for the `nearest` service, we should be able to configure the max search radius as an engine config parameter.

**Comment by daniel-j-h** [comment] 2017-12-05 16:03
Tasks:
- [ ] add max radius to the engine config [here](https://github.com/Project-OSRM/osrm-backend/blob/353829a4cc3c060ce5e58bbaf5ffc94b6f5cb265/include/engine/engine_config.hpp#L82-L91)
- [ ] add cmd line option to osrm-routed [here](https://github.com/Project-OSRM/osrm-backend/blob/353829a4cc3c060ce5e58bbaf5ffc94b6f5cb265/src/tools/routed.cpp#L119-L136)
- [ ] expose max radius to node bindings [here](https://github.com/Project-OSRM/osrm-backend/blob/353829a4cc3c060ce5e58bbaf5ffc94b6f5cb265/include/nodejs/node_osrm_support.hpp#L179) and [here](https://github.com/Project-OSRM/osrm-backend/blob/353829a4cc3c060ce5e58bbaf5ffc94b6f5cb265/src/nodejs/node_osrm.cpp#L75-L80)
- [ ] check in plugin like we do with max radius [here](https://github.com/Project-OSRM/osrm-backend/blob/353829a4cc3c060ce5e58bbaf5ffc94b6f5cb265/src/engine/plugins/nearest.cpp#L33-L40)

**Comment by daniel-j-h** [comment] 2017-12-05 18:22
Oh actually duplicate of https://github.com/Project-OSRM/osrm-backend/issues/4326 😅 Can you close both issues when you're done here?

**Comment by ghoshkaj** [comment] 2017-12-05 18:40
Eeeks! Yes! Will close both when I'm done!

**Closed** 2017-12-20 15:52 UTC
