### ISSUE TITLE
Requests timing out

### ISSUE THREAD

**Issue by ltsstar** [Project-OSRM/osrm-backend#3547] opened 2017-01-09 20:59 UTC
I am currently (just) using a script that calculates hundredthousands of routes using OSRM.
What I recently encountered is, that the OSRM backend fails on some routes, even though they appear completely legit.

I reproduced some routes on the demo server and encountered the same problem:
For instance, see this:[http://map.project-osrm.org/?z=13&center=50.940204%2C6.460218&loc=50.908256%2C6.407245&loc=50.965147%2C6.460674&hl=en&alt=0](
http://map.project-osrm.org/?z=13&center=50.940204%2C6.460218&loc=50.908256%2C6.407245&loc=50.965147%2C6.460674&hl=en&alt=0)

with the corresponding request:[https://router.project-osrm.org/route/v1/driving/6.407245,50.908256;6.460674,50.965147?overview=false&alternatives=true&steps=true&hints=;](
https://router.project-osrm.org/route/v1/driving/6.407245,50.908256;6.460674,50.965147?overview=false&alternatives=true&steps=true&hints=;)

**Comment by TheMarex** [comment] 2017-01-09 22:04
@ltsstar can you compile in `Debug` mode and see if an assertion triggers? We currently have a number of errors on the demo server triggered by requests that trigger faulty assertions.

**Comment by ltsstar** [comment] 2017-01-10 09:44
compiling in Debug mode and running osrm-contracts results in an assertion error in coordinate_extractor.cpp: [https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/coordinate_extractor.cpp#L429](
https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/guidance/coordinate_extractor.cpp#L429)

**Comment by kidjohnson** [comment] 2017-01-10 10:21
I'm not completely sure if the problem is the same, but i am facing a problem in all the requests that i make, doesn't matter what i am requesting.

The examples from the documentation are throwing internal server error :
(Table)
http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219

&
(Route)
http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false

Also, the demo http://map.project-osrm.org/?z=13&center=38.927633%2C-77.046604&loc=38.949397%2C-77.062912&loc=38.917082%2C-77.063427&hl=en&alt=0 throws : 

**No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://map.project-osrm.org' is therefore not allowed access. The response had HTTP status code 500.**

**Comment by oxidase** [comment] 2017-01-10 14:21
@ltsstar the whole area is separated from the road network by nodes like http://www.openstreetmap.org/node/278734454. It is also not a small component, so it is not ignored for snapping the start point and is routable internally 
<details>
 <summary>http://localhost:5000/route/v1/driving/6.407245,50.908256;6.417625,50.907769.json</summary>
{
    "code": "Ok", 
    "routes": [
        {
            "distance": 1072.3, 
            "duration": 81, 
            "geometry": "_avuH{ibf@Fh@ILiCqJKu@Fm@`Saa@\\sAwFyJ@k@[?eB_D", 
            "legs": [
                {
                    "distance": 1072.3, 
                    "duration": 81, 
                    "steps": [], 
                    "summary": ""
                }
            ]
        }
    ], 
    "waypoints": [
        {
            "hint": "-wQAgP0EAIAAAAAAAAAAAAwAAAAAAAAAGQAAANsDAACQAgAACwAAgMnCYQA8zQgDTcRhAGDMCAMAAAEBjUCmSQ==", 
            "location": [
                6.406857, 
                50.908476
            ], 
            "name": ""
        }, 
        {
            "hint": "IQIAgNYCAIAAAAAAMQAAAAMAAAAHAAAAAAAAAAACAAACAgAACwAAgC3tYQBFyggD2exhAHnKCAMBAAEBjUCmSQ==", 
            "location": [
                6.417709, 
                50.907717
            ], 
            "name": ""
        }
    ]
}
</details>

Profile modification is needed to unconditionally allow routing via private gates.

@danpat This is a use case for  https://github.com/Project-OSRM/osrm-backend/tree/opening_hours with `access` tag where penalties should be set to "infinite" value if condition is false to separate the area from the road network.

**Comment by daniel-j-h** [comment] 2017-01-12 11:57
Closing here. The original comment was about not routing over a private node:
http://www.openstreetmap.org/node/278734454#map=16/50.9095/6.4325

@oxidase is currently building an opening hour grammar parser for these conditional restrictions:
- https://github.com/Project-OSRM/osrm-backend/pull/3415
- https://github.com/Project-OSRM/osrm-backend/issues/3414

If you unconditionally route over those check `profiles/car.lua` and adapt the access tags appropriately.

**Closed by daniel-j-h** 2017-01-12 11:57 UTC
Labels: Bug Report
