### ISSUE TITLE
Algorithm speed improvement, maps searched 2 times for the same id

### ISSUE THREAD

**Issue by xlaussel** [Project-OSRM/osrm-backend#5876] opened 2020-11-03 12:49 UTC
Hi,

I am trying to use OSRM as a library (I want to use it into a high speed public transportation trip planner that I am curently developing). I did a POC and it works well.
I did look at the core algorithms for CH, pass  it through a profiler, and I see that there are some easy changes that could improve the speed of all the algorithms:

The node_index into the query_heap is often searched 2 times for the same NodeID. The node_index is a map so the search is costly and it could save a lot of time to save the result and reuse it. The counterpart is that it would break a little the interface of QueryHeap, exposing more things.

I can do the work for this optimization if you want. How is the process?

More complicated, I think also that it is possible to write dedicated optimized data structures to use in place of the std and boost ones.

**Comment by akashihi** [comment] 2020-11-16 09:37
>I can do the work for this optimization if you want. How is the process?

The process is pretty simple:  make a PR and we will review/merge it :) Thanks for looking into that issue

**Comment by xlaussel** [comment] 2020-11-24 11:51
> > I can do the work for this optimization if you want. How is the process?
> 
> The process is pretty simple: make a PR and we will review/merge it :) Thanks for looking into that issue

I did the changes on a branch forked from master but I cannot make a pull request: I don't have the right to push my branch. How can I proceed? (Sorry but I am a newbie in open source projetcs)

**Comment by akashihi** [comment] 2020-11-24 13:12
could you please share a link to your branch? I'll help you with rest

**Comment by xlaussel** [comment] 2020-11-24 13:16
Hi Denis,
Thank you for answering. What do you mean by "share a link to your branch" ? I can't push my branch so it is only present on my local repository.

Regards,Xavier Laussel06.10.10.64.69 

    Le mardi 24 novembre 2020 à 14:12:16 UTC+1, Denis Chapligin <notifications@github.com> a écrit :  
 
 


could you please share a link to your branch? I'll help you with rest

**Comment by jcoupey** [comment] 2020-11-24 14:02
@xlaussel you need to fork the project, make changes on your own fork (where you'll be able to push any branch). Then you'll have the ability to open a PR to request a merge from you fork's branch into `master` from the original repo.

**Comment by akashihi** [comment] 2020-11-24 14:11
@xlaussel as @jcoupey said, you need to make your own fork on github first, you can do it by clicking _fork_ button on the top right corner of OSRM backend repository  page on github. 

As you already cloned your code locally, it will require more efforts to upload your changes to your own fork. I don't remember commands properly, but it should be something like
```
git remote add myfork https://github.com/user/repo.git
git push myfork branch

```
You will need to replace _https://github.com/user/repo.git_ with address of your fork and _branch_ with name of your branch

**Comment by xlaussel** [comment] 2020-11-24 15:44
Thank you. It is done and the Pull Request also.
Xavier Laussel06.10.10.64.69 

    Le mardi 24 novembre 2020 à 15:11:36 UTC+1, Denis Chapligin <notifications@github.com> a écrit :  
 
 


@xlaussel as @jcoupey said, you need to make your own fork on github first, you can do it by clicking fork button on the top right corner of OSRM backend repository page on github.

As you already cloned your code locally, it will require more efforts to upload your changes to your own fork. I don't remember commands properly, but it should be something like
git remote add myfork https://github.com/user/repo.git
git push myfork branch


You will need to replace https://github.com/user/repo.git with address of your fork and branch with name of your branch

**Comment by akashihi** [comment] 2020-12-13 21:11
@xlaussel Thank you Xavier! 

I just reviewed it and everything looks fine except `package-lock.json`. I really doubt it should be updated in that PR. Could you please take a look?

**Comment by jcoupey** [comment] 2020-12-21 08:36
Before going on with closing this ticket (now that #5894 has been merged), I'm curious to see whether we could get more insights on the results of the changes, e.g.:

- are `route` and `table` requests expected to see the same benefit here?
- can we get some estimate on the resulting speed-up, maybe simple before/after comparisons?

**Comment by xlaussel** [comment] 2020-12-28 10:11
> * requests expected to see the same



> Before going on with closing this ticket (now that #5894 has been merged), I'm curious to see whether we could get more insights on the results of the changes, e.g.:
> 
> * are `route` and `table` requests expected to see the same benefit here?

Yes, the change avoid also some lookup for these algorithms

> * can we get some estimate on the resulting speed-up, maybe simple before/after comparisons?

We need a big benchmark to evaluate this. I think that the benefit are releveant for big networks

**Comment by danpat** [comment] 2020-12-28 15:32
I'd expect *marginal* improvement for the `/route` service - a CH search, even across very long distances, only touches a few hundred edges.  This change might improve the graph search part by 2x, but it might be hard to notice - more time is spent doing coordinate lookup (RTree search) and guidance generation (path unpacking, turn-by-turn, serialization).

Where this should be more noticeable is in the `/table` service where there can be a lot more CH search being performed, in comparison to the other operations (coordinate lookup, response serialization).

**Comment by jcoupey** [comment] 2021-01-05 14:14
Since I'm a curious person, I did some benchmarking on my side, comparing builds at a3f1c2afb (parent commit on `master`) and 89a9bc9d7 (tip of the PR branch). I've used the python `requests` module to monitor elapsed time for various sizes of matrices requested over `osrm-routed`. In order to try getting a meaningful comparison, I've launched the same 100 random matrix requests in both cases and I'm reporting total computing times (and confirmed that actual matrices retrieved are identical).

Need to keep in mind that most requests are super fast so I'm not sure the impact I'm trying to measure here always overtakes on other environment factors.

## Regional-sized graph

Locations for `table` requests are drawn uniformly in the biggest bounding box I could fit inside Ile-de-France (french region). I'm also adding the number of occasions for which the matrix computation is fastest with the PR branch.

| Matrix size | Total time a3f1c2afb (s) | Total time 89a9bc9d7 (s)| Rate | Fastest with 89a9bc9d7 |
|-----------|-----------|-----------|-----------|-----------|
| 100 | 6.91 | 6.78 | -1.96% | 81 |
| 200 | 15.53 | 15.27 | -1.71% | 86 |
| 400 | 41.94 | 40.95 | -2.37% | 96 |
| 600 | 79.75 | 78.18 | -1.98% | 100 |
| 800 | 129.66 | 127.14 | -1.94% | 96 |
| 1000 | 190.64 | 187.14 | -1.83% | 97 |

This give a rough estimate on the impact. Differences in the last column is probably mostly due to the fact that for longer computing times, the differences show more easily over some "noise" in request duration.

## Nation-wide graph

Locations for `table` requests are drawn uniformly in the biggest bounding box I could fit inside France.

| Matrix size | Total time a3f1c2afb (s) | Total time 89a9bc9d7 (s)| Rate | Fastest with 89a9bc9d7 |
|-----------|-----------|-----------|-----------|-----------|
| 100 | 12.91 | 12.71 | -1.52% | 56 |
| 200 | 22.20 | 22.14 | -0.26% | 50 |
| 400 | 53.72 | 53.43 | -0.54% | 63 |
| 600 | 101.93 | 101.06 | -0.85% | 90 |
| 800 | 162.55 | 161.87 | -0.42% | 49 |
| 1000 | 231.90 | 230.82 | -0.46% | 56 |

I'm a bit puzzled here as based on previous comments I would have expected the impact to be more significant on a bigger network. Maybe this is related to the fact that although bigger, this network is much less dense in comparison to the previous one and the number of edges visited with CH searches is actually not bigger?

**Closed** 2021-01-08 09:43 UTC
