### ISSUE TITLE
Return distance for table queries

### ISSUE THREAD

**Issue by mantesat** [Project-OSRM/osrm-backend#1353] opened 2015-01-21 14:11 UTC
Would it be possible to add distances along with travel times to the matrix requests?

**Comment by TheMarex** [comment] 2015-02-03 22:20
Adding the distance should be doable in doable in the near future. The current M2M implementation needs some work however for this to be supported.
Note: This is not routing bases on shortest distance! Until we can support that it is still some time off.

**Comment by jornedeblaere** [comment] 2015-02-25 11:21
+1 for this feature request! This would be a huge breakthrough for me

**Comment by mantesat** [comment] 2015-03-02 11:36
Any news/timeframe/estimation for this?

**Comment by mattkrick** [comment] 2015-03-20 14:32
+1, I think there's a lot of value here for routing based on shortest time and displaying the distance.

**Comment by DennisOSRM** [comment] 2015-03-20 14:33
While we are asking for your patience at this point, please be assured that this is very much on our radar.

**Comment by MannusEtten** [comment] 2015-04-15 13:46
cool! i am looking also for the distance in this matrix so I can complete a OD-matrix :+1:

**Comment by rCarto** [comment] 2015-06-22 15:56
+1

**Comment by jellevictoor** [comment] 2015-07-23 09:57
What is the current status of this issue?

**Comment by zavan** [comment] 2015-10-23 06:58
That would be very welcome :smile:

**Comment by zavan** [comment] 2015-10-23 22:56
Guys, I wrote a NodeJS script based on OSRM NodeJS bindings that can serve both time and distance tables, if anywone is interested: https://gist.github.com/zavan/2aea4881922f9de2f371

**Comment by zavan** [comment] 2015-10-23 23:14
#1033 #1248 #544

**Comment by faheemmughal** [comment] 2015-12-18 11:16
+1

**Comment by RhinoDevel** [comment] 2016-01-08 11:13
You can find a [v4.9.0](https://github.com/Project-OSRM/osrm-backend/releases/tag/v4.9.0)-based branch including additional **distances in meters** [here](https://github.com/RhinoDevel/osrm-backend/tree/v4.9.0-meters).

Please take a look at the [changes made](https://github.com/Project-OSRM/osrm-backend/compare/v4.9.0...RhinoDevel:v4.9.0-meters).

The [table service](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api) response's `.distance_table` is changed this way (sample):

From [v4.9.0](https://github.com/Project-OSRM/osrm-backend/releases/tag/v4.9.0) (only 1/10 seconds distance values): `[ [ 0, 24302 ], [ 25352, 0 ] ]`
To [v4.9.0-meters](https://github.com/RhinoDevel/osrm-backend/tree/v4.9.0-meters) (1/10 seconds and **meters** distance sub-arrays): `[ [ [ ​0, ​0 ], [ ​24302, 45281 ] ], [ [ ​25352, ​47483 ], [ ​0, 0 ] ] ]`

The solution writes distances in meters during preparation into the OSRM data files. This should lead to better performance as the calculations done in [[NOT READY] General Many-To-Many plugin #1452](https://github.com/Project-OSRM/osrm-backend/pull/1452) during each table request.

Currently these distances in meters from data files are just used by table service, but they might be useful to improve performance of other services, too (viaroute, etc.).

Please let me know, if something is not right or a pull request is appreciated.

Enjoy! :-)

**Comment by zavan** [comment] 2016-01-08 18:08
@RhinoDevel Thank you very much!
Gonna give it a try today!

**Comment by alf** [comment] 2016-01-12 14:51
@TheMarex As far as I can understand the changes made by @RhinoDevel, it should now be possible to add distance tables with shortest path as weight without too much difficulty.

Is this feature on your radar? I can't find an issue for that.

**Comment by TheMarex** [comment] 2016-01-12 15:12
While @RhinoDevel implementation looks good the implementation increase memory usage dramatically and will not be merged into `develop`.
Not a priority for me at all right now, sorry.

**Comment by danpat** [comment] 2016-02-02 21:59
The distances could be calculated on the fly, but it would impact the query table performance a bit.  The approach that @RhinoDevel took was to pre-calculate distances, so there is relatively little runtime cost, but there is quite significant extra memory required.

The rough approach would be to add route unpacking to the ManyToMany routing plugin (`include/engine/routing_algorithms/many_to_many.hpp`).  Currently, it just accumulates the total weight and returns that.

During each routings step, the edges should be added to a stack.  Once a route is found, that stack can be unwound, turned into geometry, and then distances can be calculated.

This is how routing works in all the other plugins: not only is the duration found, but the actual route is returned.  The ManyToMany plugin doesn't do this because it doesn't need to, but if it also tracked the route, the logic from `include/engine/routing_algorithms/routing_base.hpp` could be copied/reused to unpack the path, get the coordinates and then calculate the route length.

This would necessarily slow down the table, as we'd be calculating great-circle lengths for every segment in each route.  It should be doable to make this a query-time flag and not pay this penalty if distances aren't required.

**Comment by jellevictoor** [comment] 2016-02-03 06:18
Thanks for your take on this matter @danpat, I'm just curious how it would affect tables of 7000*7000 or even 10000*10000. I like the @RhinoDevel solution since it's all precalced and it is fine for us. Could this be a prepare flag? 
--table = time (default)
--table = timedist (@RhinoDevel implementation)

**Comment by RhinoDevel** [comment] 2016-02-03 12:34
Instead of using a commandline flag adding or not adding the distances in meters could be decided during compile time, e.g. by a DEFINE.
All binaries (-extract, -prepare, -routed) would be automatically on the same page then.
Some work is necessary for that.

But for people in need of big distance tables containing meters (like @jellevictoor and me) there should be a (speed) advantage - in addition to the fact that the option @danpat wrote about is not implemented, yet.

I also wouldn't have to merge my "meters-mod" with every new official OSRM release version.. ;-)

Anyway this would add some complexity to the source code the OSRM team maintains
and I don't know how many people actually are in need of big distance tables containing meters.

**Comment by danpat** [comment] 2016-02-03 19:47
I'm in the process of removing some variables from the EdgeBasedNode (`forward/reverse_offset`, `forward/reverse_weight`).  This is going to free up some memory that we might be able to use for this feature.  *Maybe*.

@jellevictoor The main problem is that it can't really be a runtime flag - the pre-calculated values are baked into the data structure and that's fixed at compile-time.  @RhinoDevel 's suggestion of a compile-time `#define` would work, but I worry about having those sprinkled all throughout the code, it gets kind of messy.

In an ideal world, we'd have distance, time and "routing weight" all separate (we want to separate time and routing weight so that we can arbitarily penalize edges without affecting calculated ETAs), but getting that all to fit in reasonable amounts of memory is difficult :-(

**Comment by systemed** [comment] 2016-04-17 07:24
I've fixed this along the lines of @danpat's Feb 2 suggestion, i.e. by unpacking paths as part of `many_to_many.hpp`. It provides a new parameter to the `table` service (`distances=true`) which, when supplied, adds a `metres_table` matrix to the JSON output. It seems to work well; I've briefly sanity-tested the resulting distances against the output from `viaroute` and they appear to be what I'd expect.

I'm running on 4.9.x so can't send it as a pull request against develop. And my C++ isn't great so you probably wouldn't want to integrate it unthinkingly anyway. ;) But I can put the new version of `many_to_many.hpp` in a gist, explain the changes there, and also list the (very few) changes elsewhere in the code. It's not too complex - I'd estimate it'd probably take a core OSRM developer half an hour to integrate, if that. Would that be helpful?

**Comment by RhinoDevel** [comment] 2016-04-18 06:44
@systemed That is good news, thanks! But I am still very interested in an official solution that does not need on-the-fly distance calculation. @danpat Any success in freeing up memory to store meters [as mentioned](https://github.com/Project-OSRM/osrm-backend/issues/1353#issuecomment-179427854)?

**Comment by risinglf** [comment] 2016-05-18 16:38
What is the current status of this issue?
@RhinoDevel and @danpat please give us good news!

**Comment by danpat** [comment] 2016-05-18 16:41
@risinglf patches are welcome :-)  AFAIK, nobody is working on it directly right now.

**Comment by systemed** [comment] 2016-05-18 18:20
Like I say, I'm happy to provide a gist which calculates on-the-fly, but it's coded against 4.9 so (given the changes in the API grammar, in particular) it would need someone to integrate it into 5.x.

**Comment by RhinoDevel** [comment] 2016-05-18 18:51
@danpat As there already are systemed's "low-memory/high-CPU" and my "high-memory/low-CPU" solutions available - what kind of patches would help?

**Comment by danpat** [comment] 2016-05-18 20:15
@RhinoDevel oh, that's easy - low-memory, low-CPU :-)

@systemed Have you measured the performance cost of your patch?

**Comment by RhinoDevel** [comment] 2016-05-18 20:27
@danpat :-) Is there still hope for freeing up some space in `EdgeBasedNode` that could be used for precalculated meters (see [your comment from Feb 3](https://github.com/Project-OSRM/osrm-backend/issues/1353#issuecomment-179427854) to really get to such a low-memory, low-CPU solution?

**Comment by danpat** [comment] 2016-05-18 20:50
@RhinoDevel I was mistaken about how much memory that would save.  It reduces the size of the data in the RTree (on disk), but doesn't have a significant memory effect.

**Comment by systemed** [comment] 2016-05-19 08:03
@danpat With a table of 33 destinations (cities in Colorado, custom bike profile), a call to `localhost:5000/table` goes up from 0.164s to 1.177s. That's overstating it slightly because I have some additional stuff patched in there, but not by much. The patch is, of course, an optional flag (`&destinations=true`).

**Comment by josefcs** [comment] 2016-07-03 22:56
Just a general thought, please correct me if I'm wrong:
Shouldn't the implementation of distances take at most twice the time and memory to make sense?
Because if the trick from #1831 can be applied (create a profile with only one speed), one gets the distances via this way.
So two calls with 0.2ms each are way better than one call with > 1s.

**Comment by danpat** [comment] 2016-07-04 07:12
@josefcs The problem is that the fast graph structure OSRM uses (contraction hierarchies) is optimized for a single metric - it can *only* route using a single metric decided on at pre-processing time.

You cannot do both shortest time and shortest distance calculations on the same CH.  We would need to create a second CH duplicating a bunch of data and optimizing it for shortest distance routing.  This would probably add multiple GB of additional RAM for large scale graphs.

**Comment by danpat** [comment] 2016-07-04 07:23
Wow, my previous answer is a bit random. It's late, I'll blame the beer.

@josefcs What you're suggesting is what @RhinoDevel made - more memory, very fast results.  The problem is that this extra memory use doesn't have much purpose elsewhere. It's a good solution if you need this, but a bit of a resource hog if you don't, and most people don't (we think).

**Comment by frodrigo** [comment] 2016-07-04 07:34
I'm doing this too, currently be recompute the distance matrix on by on using the via route. Add distance on matrix is useful for me too, but for sure this need to be an option.

**Comment by valeriob** [comment] 2016-07-04 07:44
I'm computing the matrix with distance and time with viaroute as well, but i recognize that doubling the amount of memory needed by osrm would be a no-go.

**Comment by josefcs** [comment] 2016-07-04 07:53
@danpat The reason asking was because I took a look at systemed's preliminary benchmark (https://github.com/Project-OSRM/osrm-backend/issues/1353#issuecomment-220254749) with 0.164s vs 1.177s and came to the conclusion, that might be two runs for distance and speed (for distance: only one speed with 3.6m/s, the rest is the same in the profile) is better than to change a lot of internal structure in osrm.

This way, the memory structure of osrm stays the same and people that need both results (like me) can get them with nearly double the time (two api calls).

**Comment by frodrigo** [comment] 2016-07-04 08:08
@josefcs no, you miss one point. Compute the distance of the fastest route is not the shorter distance.

**Comment by josefcs** [comment] 2016-07-04 12:20
@frodrigo Yes, you are right. I mixed that one up. For my case, it is ideal to have the shortest distance and fastest travel time (different routes). The other request/patches seem to be the fastest travel time and its distance (same route).

**Comment by PlassJ** [comment] 2016-08-11 09:18
+1

**Comment by shikharkhattar** [comment] 2016-08-11 10:37
+1

**Comment by niemeier-PSI** [comment] 2016-08-12 09:08
A fully functional version of the table service with distance support is available here: https://github.com/Project-OSRM/osrm-backend/pull/2764
The general approach is quite similar to what RhinoDevel did, but this one is based on *master*.
For more details the the description in that pull request.

**Comment by narzero** [comment] 2017-02-19 12:37
+1

**Comment by glifchits** [comment] 2017-09-14 22:12
Hey OSRM team, we think this feature would be useful as well. I'm wondering if returning distances in the table API are on the roadmap, given that there hasn't been a lot of recent activity on this issue.

**Comment by jeffginger** [comment] 2017-10-17 08:23
There was a fork where someone had developed the ability to get both distances and durations, I can't seem to find this now - could anybody help me out? 

Thanks in advance

**Comment by sandeepgadhwal** [comment] 2017-11-10 18:31
I just need distance not duration here can anyone help 

I am currently getting table response here by this query
 http://localhost:5000/table/v1/driving/-118.307399,34.090134;-118.306342,34.082808;-118.306342,34.0829?sources=0

which is : {"code":"Ok","durations":[[0,139.2,136.8]],"destinations":[{"hint":"woYAgLVmGYA0AAAAXQAAAAAAAAAAAAAANAAAAF0AAAAAAAAAAAAAAFkDAAC6xfL41SsIArnF8viWLAgCAACfBU9TUk0=","name":"Sierra Vista Avenue","location":[-118.307398,34.089941]},{"hint":"D2MZgBFjGYBWAgAAfwEAAAAAAAAAAAAAKwEAAMAAAAAAAAAAAAAAAFkDAAC5yfL4-A8IAtrJ8vj4DwgCAAB_Fk9TUk0=","name":"","location":[-118.306375,34.082808]},{"hint":"D2MZgBFjGYCHAgAATgEAAAAAAAAAAAAAQwEAAKgAAAAAAAAAAAAAAFkDAAC4yfL4VBAIAtrJ8vhUEAgCAAB_Fk9TUk0=","name":"","location":[-118.306376,34.0829]}],"sources":[{"hint":"woYAgLVmGYA0AAAAXQAAAAAAAAAAAAAANAAAAF0AAAAAAAAAAAAAAFkDAAC6xfL41SsIArnF8viWLAgCAACfBU9TUk0=","name":"Sierra Vista Avenue","location":[-118.307398,34.089941]}]}

I want distance instead of duration in the matrix what should i do.

**Comment by RhinoDevel** [comment] 2017-11-13 07:04
@sandeepgadhwal, this is not supported by OSRM, but you can use this: https://github.com/Project-OSRM/osrm-backend/pull/2764

**Comment by nicolo-paganin** [comment] 2017-11-30 17:31
+1 any news or update about this feature?

**Comment by sandeepgadhwal** [comment] 2017-12-08 20:41
I do not need the duration i just need distance matrix can somebody help me to get distance by this query http://localhost:5000/table/v1/driving/-118.307399,34.090134;-118.306342,34.082808;-118.306342,34.0829?sources=0

**Comment by frodrigo** [comment] 2017-12-08 20:46
@sandeepgadhwal No you can't with the actuel code of OSRM until some change will be made. Nevertheless, you can use this pull request #2764. Or change a profile to deals with distance in place of time. I made this here: https://github.com/Project-OSRM/osrm-profiles-contrib/tree/master/5/5

**Comment by sandeepgadhwal** [comment] 2017-12-08 20:53
@frodrigo what changes can i make in my https://github.com/sandeepgadhwal/osrm-backend/blob/master/profiles/car.lua profile i just need distance in place of duration can we keep speed constant at 1 meter per second so that i get seconds = meters in duration table. Any suggestion that we can determine distance instead of duration.

**Comment by xydinesh** [comment] 2017-12-14 17:29
+1 for returning distance.

**Comment by sashakh** [comment] 2017-12-14 18:17
Yet more +1

On Dec 14, 2017 7:29 PM, "Dinesh Weerapurage" <notifications@github.com>
wrote:

+1 for returning distance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Project-OSRM/osrm-backend/issues/1353#issuecomment-351780742>,
or mute the thread

**Comment by hopewise** [comment] 2017-12-25 09:47
Hi,
As I will be using table service to feed the algorithm that solves vehicle routing  problem, I will only need the `durations` without `destinations`, is this possible? to exclude `destinations` in result as its not needed?

**Comment by jgabriels** [comment] 2018-02-20 01:50
I would also like to vote for this feature to be added.
I also would honestly like to know what the use case even is for a table with durations but no distances.
To me, if you were going to include only one, only returning distances makes a lot more sense.

**Comment by systemed** [comment] 2018-02-20 08:36
> I also would honestly like to know what the use case even is for a table with durations but no distances.

Most VRP applications, which optimise deliveries within time constraints. Typically you'll take a duration matrix and feed it into a solver such as jsprit or something built with Google's OR Tools. Distance is additionally useful here if you have a fuel constraint, but duration is the main use case.

**Comment by danpat** [comment] 2018-02-20 17:30
@dskrvk The reason that OSRM currently isn't returning this data is because it *doesn't* keep track of distances between points - the routing graph only stores *time* (and/or *weight*), and in order to return distances, the full path between points currently needs to be unpacked and distances re-calculated.

One of the reasons that the `table` plugin is so fast is that it *does not need to unpack* paths in order to return the time between points.  There are basically three options to make it happen:

  1.  Unpack paths and calculate distances - this will make the `table` request much slower.
  2.  Store the distances alongside the paths - this will make OSRM use a lot more memory.
  3.  Implement a caching scheme for path unpacking that will hopefully make (1) reasonably performant.

There is some work towards (3) happening over in https://github.com/Project-OSRM/osrm-backend/pull/4876 - we hope to get this into the mainline soon-ish.  The results look promising, caching of path unpacking is quite effective with CH/MLD.

If you prefer the additional memory usage approach, you can follow the work done in https://github.com/Project-OSRM/osrm-backend/pull/2764 - I don't think we'll mainline this yet, unless we can figure out a good way to make it a runtime configuration option.

**Comment by jmarca** [comment] 2018-03-12 02:58
For my use case---sourcing an all-to-all distance and duration matrix for feeding into Google OR-tools pdptw solver---I'm willing to pay the cost of getting duration and distance using individual queries, because the solver takes so long to run compared to getting the data one OD pair at a time.  At the same time, it is so tantalizing to know that I can get *half* the data I need from the many-to-many query in much less time.  I took a look at the #4876 branch, but to be honest my C++ is pretty darn rusty and I can't really contribute much right now.  So I'm just a cheerleader waving my pompoms and saying Go Team right now, but getting distance and duration from the Table API would be super awesome. <emoji for pompoms>.

**Comment by cglacet** [comment] 2018-04-03 09:47
I'm not sure to understand how this is really different from durations, both metrics behave the same.

It seems to me that it might not even need supplementary work depending on what users want. For example, if I just want to retrieve the distance associated with the shortest path in the duration graph, then you can use the exact same protocol to answer both distance and duration request (as they both rely on the same graph and have the same shortest path). 

I don't know what technique you are currently using for durations requests, but let say you use a landmark cover. If you want to have both duration and distance working, then you still keep your current cover and simply add a second metric to your graph (all edges will have a distance and a duration), your landmarks will only cover the duration (same as before). When you have a new request for nodes (u,v), you do the same landmark search as before. Let suppose that landmark w is found to be on the path u->v (w has been selected as u->w->v is contained in a shortest path from u to v). You then return duration(u,w)+duration(w,v) (just as you did before) and/or distance(u,w)+distance(w,v). 

- It is not harder than before to build your landmark cover (the cover is the same set as before).
- There is a factor 2 overhead in the preprocessing as you still do a BFS but now with two metrics. 
- For query response time you have no overhead (as you only select a single landmark in the same set as before and just return two values)

On the other hand, if the user want to have both the shortest path in terms of distance and duration, then you simply duplicate everything and you therefore have two distinct graphs (distance/duration), with two landmark covers and you run two distinct BFS to get your landmark distances. Answering a request will probably takes twice longer as before unless the landmark cover for distances is significantly larger than the one for durations. Overall the overhead probably is a factor 2 on preprocessing time/memory usage and query time (if the user query both services), there is no overhead for query time if the user only request the duration.

Unless you are using a very strange/convoluted technique to query durations I really feel like this is a question of days to implement this (at least for the first version I explained).

**Comment by chaupow** [comment] 2018-04-03 10:01
heyhey. I am aware this is a super hot topic 😄🔥 

@cglacet regarding some of your questions

> I'm not sure to understand how this is really different from durations, both metrics behave the same.

@danpat basically already answered this question:

> @dskrvk The reason that OSRM currently isn't returning this data is because it doesn't keep track of distances between points - the routing graph only stores time (and/or weight), and in order to return distances, the full path between points currently needs to be unpacked and distances re-calculated.

So that the is main difference between durations and distances. Unpacking is expensive. 😞

>  Overall the overhead probably is a factor 2 on preprocessing time/memory usage and query time

OSRM can probably do a factor 2 on query time, but a factor 2 on preprocessing time / memory is something we'd need to consider well. OSRM already consumes a lot of memory and people struggle getting the right hardware to run OSRM. Preprocessing can take up to 6h for a continent. So resulting in 12h is not something we can just do. 

If memory is no problem, there is a working branch by @niemeier-PSI that computes `distances` in the matrix https://github.com/Project-OSRM/osrm-backend/issues/1353#issuecomment-239397980

> Unless you are using a very strange/convoluted technique to query durations I really feel like this is a question of days to implement this (at least for the first version I explained).

We're (and especially @ghoshkaj ) are working on this to get it right with preserving query time, preproc time and memory as best as possible. Please give her and us time to do this right 🙂  Coding is hard, there are many pitfalls and we're doing our best 💪 ❤️

**Comment by cglacet** [comment] 2018-04-04 12:01
If you guys are interested, I found a way to cheat a little bit. You can use the route service (which returns distances and durations) to simulate a table matrix. It's a bit awkward, but it works.

The solution I currently use allow to retrieve a matrix of size 15 at most in a single request to OSRM (maybe 17 if you don't need high precision coordinates).

## Goal
The strategy is to build a route that goes through all (non-ordered) pairs of coordinates in the matrix. For example, if you have _n=4_ coordinates _{c1,c2,c3,c4}_ you need to build a route in which appear all (non-ordered) pairs of coordinates, ie. a route that contains _{c1,c2}, {c1,c3}, {c1,c4}, {c2,c3}, {c2,c4}, {c3,c4}_. By non-ordered I mean that if the route contains at some point `"..., c3, c1,..."` then the pair _{c1,c3}_ **is** present in the route. (Remark: With _n=4_, the total number of (non-ordered) pairs is n*(n-1)/2, here 6.) In this particular example, if you want to build a route that contains these 6 patterns, then you will have repetitions (because n is even): `"c1, c2, c3, c1, c4, c3, c4, c2"` (here the repetition is _{c3,c4}_, it appears 2 times `"...,c4, c3, ..."` and  `"...,c3, c4, ..."`). This is not a problem, this is just 'not optimal' as we will pass too many route legs to the route service (but it is optimal in the sense that no path without repetition can be done for n=4).

## Solution
The algorithm has two parts (_n is odd_ and _n is even_), they both are based on the same principle: using disjoint hamiltonian paths to cover most edges of the graph (all when n is odd). You can find details on the [technique for an _odd n_ here](https://math.stackexchange.com/questions/16933/generating-a-eulerian-circuit-of-a-complete-graph-with-constant-memory). Once you understand that technique (I really suggest you take a bit of time to do so because it's a very nice technique), then the _n is even_ part will be easy as we will build a simpler (but not as nice) version of this strategy. 

### When _n_ is odd
It exists a set of hamiltonian path that cover the graph (the set of edges of our hamiltonian paths is exactly equal to the set of edges of the graph). The stackoverflow post explains a nice way to build hamiltonian paths that can be merged to have an eulerian tour (the idea is to have a fixed node that will serve as a bridge between all paths).

### When _n_ is even
The solution can't be optimal (there is no eulerian tour of a graph that contains more than 2 odd degree nodes). In this case we can still find a solution that is easy to build and only have _n/2_ repetitions (one can probably find a better solution, but I was lazy and this one is particularly simple to implement). The idea is to use the same zig-zaggy path as in the odd solution (first node, last node, second node, penultimate node, ...) but with all nodes in it (no fix point), and then rotate the zig-zag _n/2_ times to build _n/2_ hamiltonian paths that are then merged to give the final tour (not eulerian). With this solution, the unnecessary edges are all the edges between the hamiltonian paths, and thus there are _n/2_ edges that are repeated in the tour. This solution is fine for me right now, but if you find a nicer solution I would be happy to hear it :) (if you are even lazier than I am you could even implement an _even version_ where you simply add a fake coordinate and then build an eulerian tour). 

## Implementation example (python)
I added[ my source for the tour construction here](https://github.com/cglacet/clique-tour) in case someone would like to modify them. If you just want to use them, then you need to run `pip install clique_tour`. Then you can have script that will send requests to your OSRM server (here the demo server): 

```python
import clique_tour, requests, json
import numpy as np

osrm_route_service = "http://router.project-osrm.org/route/v1/driving/"

def main():
    test_coordinates = [
        "60.70278,31.6386",
        "60.92565,33.94732",
        "61.28789,32.23765",
        "65.90314,37.6431",
        "66.9574,34.18027",
        "67.5304,31.95617",
        "67.63406,33.14132"
    ]
    sample_size = len(test_coordinates)
    print("Testing with {} coordinates".format(sample_size))
    eulerian_tour = clique_tour.build(sample_size)
    fake_route = ";".join([ test_coordinates[i] for i in eulerian_tour ])
    address = osrm_route_service + fake_route
    print("Requesting osrm at \n\t{}".format(address))
    r = requests.get(address, params={}, timeout=None)
    data = json.loads(r.text)
    if data['code'] == "Ok":
        route = data["routes"][0]
        legs = route["legs"]
        eulerian_tour_distances = [ leg["distance"] for leg in legs]
        eulerian_tour_durations = [ leg["duration"] for leg in legs]

        distances = np.zeros((sample_size,sample_size))
        durations = np.zeros((sample_size,sample_size))
        for i in range(len(eulerian_tour)-1):
            u = eulerian_tour[i+1]
            v = eulerian_tour[i]
            # get distances/durations for all edges and fill the matrix
            distances[u,v] =  eulerian_tour_distances[i]
            distances[v,u] =  eulerian_tour_distances[i]
            durations[u,v] =  eulerian_tour_durations[i]
            durations[v,u] =  eulerian_tour_durations[i]

        print("Distance matrix: \n\t{},\n Duration matrix: \n\t{}".format(distances,durations))

if __name__ == "__main__":
    main()
```

Which outputs:
```bash
Testing with 7 coordinates
Requesting osrm at
	http://router.project-osrm.org/route/v1/driving/60.70278,31.6386;67.5304,31.95617;60.92565,33.94732;66.9574,34.18027;61.28789,32.23765;65.90314,37.6431;67.63406,33.14132;60.92565,33.94732;60.70278,31.6386;61.28789,32.23765;67.5304,31.95617;65.90314,37.6431;66.9574,34.18027;67.63406,33.14132;61.28789,32.23765;60.92565,33.94732;65.90314,37.6431;60.70278,31.6386;66.9574,34.18027;67.5304,31.95617;67.63406,33.14132;60.70278,31.6386
Distance matrix:
	[[      0.   597848.5  111905.3 1424042.5 1327335.6  908101.5  981078.8]
 [ 597848.5       0.   579581.6  938840.5 1397277.6  883615.5 1051166.7]
 [ 111905.3  579581.6       0.  1374843.5 1432621.7  916834.9 1084560.8]
 [1424042.5  938840.5 1374843.5       0.   902239.6  983268.3  905651.4]
 [1327335.6 1397277.6 1432621.7  902239.6       0.   515612.   438002.3]
 [ 908101.5  883615.5  916834.9  983268.3  515612.        0.   197313.8]
 [ 981078.8 1051166.7 1084560.8  905651.4  438002.3  197313.8       0. ]],
 Duration matrix:
	[[     0.   74002.1  14669.4 144092.3 120643.   80559.3  96219.7]
 [ 74002.1      0.   71016.5  82867.2 108230.5  63790.4  83739.4]
 [ 14669.4  71016.5      0.  132550.5 136620.   87058.8 109406.6]
 [144092.3  82867.2 132550.5      0.   85250.8  75562.9  79776. ]
 [120643.  108230.5 136620.   85250.8      0.   47162.4  46454.5]
 [ 80559.3  63790.4  87058.8  75562.9  47162.4      0.   18105.8]
 [ 96219.7  83739.4 109406.6  79776.   46454.5  18105.8      0. ]]
```

Using this two matrices you can check the average speed (km/h):
```python 
print("Speed matrix (km/h): \n\t{}".format(distances/(durations+np.finfo(np.float32).eps)*((60*60)/1000)))
``` 
```bash
Speed matrix (km/h):
	[[ 0.         29.08369623 27.46254634 35.5782578  39.60783598 40.58085654
  36.70645072]
 [29.08369623  0.         29.38040817 40.7860504  46.47672657 49.86668519
  45.19019859]
 [27.46254634 29.38040817  0.         37.34000699 37.7502424  37.91237228
  35.68723346]
 [35.5782578  40.7860504  37.34000699  0.         38.100083   46.84528883
  40.86874544]
 [39.60783598 46.47672657 37.7502424  38.100083    0.         39.35769164
  33.94306852]
 [40.58085654 49.86668519 37.91237228 46.84528883 39.35769164  0.
  39.23216185]
 [36.70645072 45.19019859 35.68723346 40.86874544 33.94306852 39.23216185
   0.        ]]
```

## For the curious - the two tour functions
```python
# This function is called when n is odd
def eulerian(n):
    middle = (n-1)//2
    path_shape = [ u for i in range(middle) for u in (i,n-2-i) ]
    hamiltonian_paths = []

    # Increment the path shape to "rotate" the hamiltonian path (see stackexchange post)
    for i in range(middle):
        hamiltonian_paths += [ (path_shape[p]+i)%(n-1) for p in range(len(path_shape)) ]
        hamiltonian_paths += [n-1] # Everything is rotated, this node is here to make a junction from one hamiltonian path to the next

    # Close the tour
    hamiltonian_paths += [hamiltonian_paths[0]]
    return hamiltonian_paths
```
```python
# This function is called when n is even (more or less the same code)
def almost_eulerian(n):
    path_shape = [ u for i in range(n//2) for u in (i,n-1-i) ]
    hamiltonian_paths = []
    for i in range(n//2):
        path = [ (path_shape[p]+i)%n for p in range(len(path_shape)) ]
        hamiltonian_paths += path
    hamiltonian_paths += [hamiltonian_paths[0]]
```

**Comment by danpat** [comment] 2018-04-04 23:11
@cglacet This is an open-source project - pull requests are always welcome, and if you have the time and inclination to contribute to the implementation of this feature, feel free.

There is very little (i.e. no) change to the actual graph traversal side here, rather, the implementation problem is more around data packing and cache invalidation.

Work is happening over in https://github.com/Project-OSRM/osrm-backend/pull/4876, and https://github.com/Project-OSRM/osrm-backend/pull/4990

**Comment by TheMarex** [comment] 2018-05-14 15:35
This is now possible by passing `&annotations=duration,distance` to the `table` service. The computation will be much slower for coordinate pairs that are far apart, which could be improved with https://github.com/Project-OSRM/osrm-backend/pull/4989. Thanks @ghoshkaj @chaupow @oxidase for working so hard on this. :-)

**Closed by TheMarex** 2018-05-14 15:35 UTC
Labels: Feature Request

**Comment by LeoPovoa** [comment] 2018-05-30 21:48
Hi Folks, 

I test this example:

http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=distance

and got this erro:

{"code":"Error","message":"Unrecognized parameter 'annotations'"}

**Comment by russelltrafford** [comment] 2018-09-26 21:49
Any updates on this one? I get the same error as @LeoPovoa

**Comment by xydinesh** [comment] 2018-09-27 04:30
@LeoPovoa @russelltrafford annotations enabled/added in 5.18.0, please check version of the OSRM you are using. Most likely you are using a version older than 5.18.0

https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md

**Comment by danpat** [comment] 2018-09-27 15:11
@xydinesh No, the problem is that the OSRM demoserver hasn't exposed those new options yet.  It's on my todo list, but I simply haven't got around to it yet.

**Comment by isaac0821** [comment] 2019-04-10 03:28
> Hi Folks,
> 
> I test this example:
> 
> http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=distance
> 
> and got this erro:
> 
> {"code":"Error","message":"Unrecognized parameter 'annotations'"}

Any updates? ... I still get the same error.

**Comment by danpat** [comment] 2019-04-10 03:49
No updates - I don't see myself having a chance to get this upgrade done any time in the near future.  If you need the distance annotation urgently, you should consider running your own server.
