### ISSUE TITLE
Add POST request handler to table service

### ISSUE THREAD

**Issue by thebitbrine** [Project-OSRM/osrm-backend#5915] opened 2020-12-15 12:24 UTC
I'm working in an environment that requires getting huge distance matrixes from the table service.
The problem arises when we try to get the distance matrix of more than 750 nodes.
Adding 750 lat/lons into the URL makes it too big and we can't use standard libraries to fulfill our needs.
Currently, instead of making a typical GET request, we open a connection to the HTTP endpoint of the table service via TCP socket, and then we manually build our GET request. ([Reference](https://stackoverflow.com/questions/2109695/how-do-i-create-an-http-request-manually-in-net))

_**Feature request:**_
Add POST request handler to the table service as an accompaniment to GET request handler.

**Comment by TimMcCauley** [comment] 2020-12-15 12:29
@thebitbrine have a look at https://github.com/door2door-io/osrm-express-server-demo

**Comment by jcoupey** [comment] 2020-12-15 13:02
Closing as duplicate of #5794 (see also closed issue linked there for pointers on possible workarounds).

**Closed by jcoupey** 2020-12-15 13:02 UTC
