### ISSUE TITLE
Route calculation is dependant on route changes in unrelated area

### ISSUE THREAD

**Issue by MaartenDeen** [Project-OSRM/osrm-backend#1429] opened 2015-04-03 09:51 UTC
I apologise for the maybe cryptic subject. I am noticing a change in the route calculation in unrelated areas when you change the parameters of the route in other areas.
Consider these two routes (screenshots are also attached): 
1) http://www.osrm.at/bDs
2) http://www.osrm.at/bDt

1) is the route that osrm calculates without intermediate points and takes a shortest path in the village Lierop. For 2) I added an intermediate point in an area that is not related to the route in the village (it is not on a track that should be affected by the new point) and the new route calculates a different route in the village Lierop which is about 500 meter longer.
Looking at the speed information from the point of change, 1) is about 340 meters @ 30 km/h, 2) is about 145 m @ 50 km/h and 680 m @ 30 km/h. This can never be a faster route.

Why does the route calculation change when I put an intermediate point in a non-related area?

![route1](https://cloud.githubusercontent.com/assets/1825970/6980781/a6eafec6-d9f7-11e4-99e9-9ebcfb5a8947.png)
![route2](https://cloud.githubusercontent.com/assets/1825970/6980783/a8bf92de-d9f7-11e4-8b21-5b24d4362636.png)

**Comment by danpat** [comment] 2015-04-14 00:25
Possibly related test case.  Here, the intermediate marker is moved around a corner that is on the path in both cases.  In the second case, the routing seems reasonable, in the first case, the routing does a complete lap of the block to arrive at the point.

![screen shot 2015-04-13 at 5 20 57 pm](https://cloud.githubusercontent.com/assets/1892250/7128039/920217b2-e201-11e4-8a42-6b57cf556a84.png)

![screen shot 2015-04-13 at 5 22 03 pm](https://cloud.githubusercontent.com/assets/1892250/7128043/ab23317c-e201-11e4-9194-453b61a704da.png)

**Comment by woodbri** [comment] 2015-04-14 00:33
Please supply links from the [Generate Link] link so we can have a link example of these last two. Thanks.

**Comment by danpat** [comment] 2015-04-14 00:37
Here you go:

http://osrm.at/bOG
http://osrm.at/bOF

**Comment by danpat** [comment] 2015-04-14 18:02
Here's a minimal case from the original report.  By moving the intermediate marker slightly, the route changes in unexpected ways.

I loaded a 10x10km OSM extract for this region of the Netherlands into a local OSRM install, and I can't reproduce the problem based on HEAD from master.  If I place markers in the same spots, the routing does *not* jump around like it does on http://map.project-osrm.org/.

http://osrm.at/bPo
![screen shot 2015-04-14 at 10 55 13 am](https://cloud.githubusercontent.com/assets/1892250/7143508/e464ef14-e294-11e4-828c-680bf905b50d.png)


http://osrm.at/bPp
![screen shot 2015-04-14 at 10 53 33 am](https://cloud.githubusercontent.com/assets/1892250/7143503/e0484232-e294-11e4-9ca8-33603939e912.png)

**Comment by danpat** [comment] 2015-04-14 19:29
While I can't reproduce it in master, it is in develop as of  61dca4a35e4d5667c991e2d0060a442593cc1c9d

**Comment by danpat** [comment] 2015-04-14 21:05
Looks like this behaviour appeared in 11c671354be8c791ef107e6ce6c4a38435417edb

**Comment by danpat** [comment] 2015-04-14 23:30
In addition, reversing the route often does not produce the same outcome, even when there are no one-way streets involved.  Examples demonstrate this behaviour.

**Comment by TheMarex** [comment] 2015-05-17 15:13
Seems related to https://github.com/Project-OSRM/osrm-backend/issues/1474 Can also reproduce this with develop.

**Comment by TheMarex** [comment] 2015-05-17 21:02
@danpat just double checked: Reverting that commit fixes this problem. Awesome work tracking that down! Going to cross verify with the other issues that have cropped up.

**Comment by emiltin** [comment] 2015-05-17 21:09
fix/looping contains a failing cucumber test. it's a small extract of a location in copenhagen. to run:
cuke -p all features/testbot/bugs.feature:8

there are two wrong cases:

http://map.project-osrm.org/?hl=en&loc=55.664913,12.601698&loc=55.665016,12.602199&loc=55.665302,12.603515&z=18&center=55.664711,12.602324&alt=0&df=0&re=0&ly=-1171809665

http://map.project-osrm.org/?hl=en&loc=55.664913,12.601698&loc=55.664948,12.601887&loc=55.665302,12.603515&z=18&center=55.664711,12.602324&alt=0&df=0&re=0&ly=-1171809665

**Comment by TheMarex** [comment] 2015-05-17 21:37
Just reverted 11c6713 on `develop` tomorrow we will see if that fixes the problems that have cropped up recently. Still this code has bugs that need to be fixed.

**Comment by woodbri** [comment] 2015-05-17 22:22
I just built and tested develop and it fixed this case:
http://map.project-osrm.org/?hl=en&loc=-34.6688,-56.20764&loc=-34.86639,-56.20818&loc=-34.86563,-56.20894
![issue1429-bad](https://cloud.githubusercontent.com/assets/805250/7672451/978da888-fcc1-11e4-9be6-db3f3c2529db.png)

**Comment by woodbri** [comment] 2015-05-18 15:51
My example above is working correctly now on map.project-osrm.org.

**Comment by TheMarex** [comment] 2015-05-30 16:42
This was fixed by https://github.com/Project-OSRM/osrm-backend/pull/1503

**Closed by TheMarex** 2015-05-30 16:42 UTC
Labels: Bug Report
