### ISSUE TITLE
Truck routes and weight limitations

### ISSUE THREAD

**Issue by Rougree** [Project-OSRM/osrm-backend#6522] opened 2023-01-25 13:45 UTC
Hi guys,

I'm testing with OSRM and routes for trucks. I'm testing for height restrictions, truck restrictions and weight restrictions/limitations. Height and truck restrictions work properly with my setup (see osrm version, profile.lua and other lua files below), but weight restrictions do not work. Do I miss someting in the files why it does not avoid weight restrictions.  See below more explanation. The  lib lua files are from truck-soft profile (if I'm right). 

**lib .lua files**
[lib.zip](https://github.com/Project-OSRM/osrm-backend/files/10500194/lib.zip)

1. Height restrictions:
This works fine. See the image, at the yellow circle is the height of the tunnel smaller than the height of the vehicle. So OSRM avoid this road. Great! Tested it for more place and it works!
![image](https://user-images.githubusercontent.com/52921963/214569939-01434b2c-f894-4cbd-a276-91f09b281e0d.png)

2. Truck restrictions:
This works fine. The board is a restriction for trucks.
![image](https://user-images.githubusercontent.com/52921963/214569110-1b9b0b5d-6a06-4d9a-8828-58cf1bd8933a.png)

 See the image, the yellow circle road is restricted for trucks en OSRM avoid this road.
![image](https://user-images.githubusercontent.com/52921963/214569654-395dfffd-baf4-45e1-9642-c958808e6156.png)

3. Weight limitations: 
Unfortunately this does not work for weight restrictions. This road have a limitation of 7.500KG.
![image](https://user-images.githubusercontent.com/52921963/214570430-aa00dbe8-4176-4054-af04-dc5186fb8d1a.png)
 However with the profile I use (see below) it should avoid this road. 
![image](https://user-images.githubusercontent.com/52921963/214571217-c7d0232b-35d3-4813-a27e-fa71b92af6de.png)

Tested it for multiple road with weight limitations. But for some reason weight limitations does not work with OSRM, while height en truckrestrictions do. 

Below you find my:
1. osrm version, docker etc. 
2. profile.lua (truck.lua) and 
3. lib: (other lua files)

```
docker run -t -v %cd%/data_truck:/data_truck -v %cd%/profiles:/profiles ghcr.io/project-osrm/osrm-backend:v5.27.1 osrm-extract -p /profiles/truck/truck.lua /data_truck/nl-be.pbf
docker run -t -v %cd%/data_truck:/data_truck ghcr.io/project-osrm/osrm-backend:v5.27.1 osrm-partition /data_truck/nl-be.osrm
docker run -t -v %cd%/data_truck:/data_truck ghcr.io/project-osrm/osrm-backend:v5.27.1 osrm-customize /data_truck/nl-be.osrm

```
`docker run --rm -t -i -p 5000:5000 -v %cd%/data_truck:/data_truck ghcr.io/project-osrm/osrm-backend:v5.27.1 osrm-routed --max-table-size=10000 --max-viaroute-size=20000 --max-trip-size=3000 --algorithm mld /data_truck/nl-be.osrm
`

**This is the truck.lua:**

```
-- Car profile

api_version = 4

Set = require('lib/set')
Sequence = require('lib/sequence')
Handlers = require("lib/way_handlers")
Relations = require("lib/relations")
find_access_tag = require("lib/access").find_access_tag
limit = require("lib/maxspeed").limit
Utils = require("lib/utils")
Measure = require("lib/measure")

function setup()
  return {
    properties = {
      max_speed_for_map_matching      = 150/3.6, -- 150kmph -> m/s
      -- For routing based on duration, but weighted for preferring certain roads
      weight_name                     = 'routability',
      -- For shortest duration without penalties for accessibility
      -- weight_name                     = 'duration',
      -- For shortest distance without penalties for accessibility
      -- weight_name                     = 'distance',
      process_call_tagless_node      = false,
      u_turn_penalty                 = 30,
      continue_straight_at_waypoint  = true,
      use_turn_restrictions          = true,
      left_hand_driving              = false,
      traffic_light_penalty          = 2,
    },

    default_mode              = mode.driving,
    default_speed             = 10,
    oneway_handling           = true,
    side_road_multiplier      = 0.8,
    turn_penalty              = 25,
    speed_reduction           = 0.8,
    turn_bias                 = 1.075,
    cardinal_directions       = false,

    -- Size of the vehicle, to be limited by physical restriction of the way
    vehicle_height = 3.5, -- in meters
    vehicle_width = 2.55, -- in meters

    -- Size of the vehicle, to be limited mostly by legal restriction of the way
    vehicle_length = 9.0, -- in meters, 4.8m is the length of large or familly car
    vehicle_weight = 30000, -- in kilograms

    -- a list of suffixes to suppress in name change instructions. The suffixes also include common substrings of each other
    suffix_list = {
      'N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW', 'North', 'South', 'West', 'East', 'Nor', 'Sou', 'We', 'Ea'
    },

    barrier_whitelist = Set {
      'cattle_grid',
      'border_control',
      'toll_booth',
      'sally_port',
      'gate',
      'lift_gate',
      'no',
      'entrance',
      'height_restrictor'
    },

    access_tag_whitelist = Set {
      'yes',
      'motorcar',
      'motor_vehicle',
      'vehicle',
      'permissive',
      'designated',
      'hov'
    },

    access_tag_blacklist = Set {
      'no',
      'agricultural',
      'forestry',
      'emergency',
      'psv',
      'customers',
      'private',
      'delivery',
      'destination'
    },

    -- tags disallow access to in combination with highway=service
    service_access_tag_blacklist = Set {
        'private'
    },

    restricted_access_tag_list = Set {
      'private',
      'delivery',
      'destination',
      'customers',
    },

    access_tags_hierarchy = Sequence {
      'motorcar',
      'motor_vehicle',
      'vehicle',
      'access'
    },

    service_tag_forbidden = Set {
      'emergency_access'
    },

    restrictions = Sequence {
      'motorcar',
      'motor_vehicle',
      'vehicle'
    },

    classes = Sequence {
        'toll', 'motorway', 'ferry', 'restricted', 'tunnel'
    },

    -- classes to support for exclude flags
    excludable = Sequence {
        Set {'toll'},
        Set {'motorway'},
        Set {'ferry'}
    },

    avoid = Set {
      'area',
      -- 'toll',    -- uncomment this to avoid tolls
      'reversible',
      'impassable',
      'hov_lanes',
      'steps',
      'construction',
      'proposed'
    },

    speeds = Sequence {
      highway = {
        motorway        = 90,
        motorway_link   = 45,
        trunk           = 85,
        trunk_link      = 40,
        primary         = 65,
        primary_link    = 30,
        secondary       = 55,
        secondary_link  = 25,
        tertiary        = 40,
        tertiary_link   = 20,
        unclassified    = 25,
        residential     = 25,
        living_street   = 10,
        service         = 15
      }
    },

    highway_penalties = {
      motorway        = 1,
      motorway_link   = 1,
      trunk           = 1,
      trunk_link      = 1,
      primary         = 1,
      primary_link    = 1,
      secondary       = 1,
      secondary_link  = 1,
      tertiary        = 0.9,
      tertiary_link   = 0.9,
      unclassified    = 0.8,
      residential     = 0.7,
      living_street   = 0.3,
      service         = 0.2,
      track           = 0.1
    },

    service_penalties = {
      alley             = 0.5,
      parking           = 0.5,
      parking_aisle     = 0.5,
      driveway          = 0.5,
      ["drive-through"] = 0.5,
      ["drive-thru"] = 0.5
    },

    restricted_highway_whitelist = Set {
      'motorway',
      'motorway_link',
      'trunk',
      'trunk_link',
      'primary',
      'primary_link',
      'secondary',
      'secondary_link',
      'tertiary',
      'tertiary_link',
      'residential',
      'living_street',
      'unclassified',
      'service'
    },

    construction_whitelist = Set {
      'no',
      'widening',
      'minor',
    },

    route_speeds = {
      ferry = 5,
      shuttle_train = 10
    },

    bridge_speeds = {
      movable = 5
    },

    -- surface/trackype/smoothness
    -- values were estimated from looking at the photos at the relevant wiki pages

    -- max speed for surfaces
    surface_speeds = {
      asphalt = nil,    -- nil mean no limit. removing the line has the same effect
      concrete = nil,
      ["concrete:plates"] = nil,
      ["concrete:lanes"] = nil,
      paved = nil,

      cement = 80,
      compacted = 80,
      fine_gravel = 80,

      paving_stones = 60,
      metal = 60,
      bricks = 60,

      grass = 40,
      wood = 40,
      sett = 40,
      grass_paver = 40,
      gravel = 40,
      unpaved = 40,
      ground = 40,
      dirt = 40,
      pebblestone = 40,
      tartan = 40,

      cobblestone = 30,
      clay = 30,

      earth = 20,
      stone = 20,
      rocky = 20,
      sand = 20,

      mud = 10
    },

    -- max speed for tracktypes
    tracktype_speeds = {
      grade1 =  60,
      grade2 =  40,
      grade3 =  30,
      grade4 =  25,
      grade5 =  20
    },

    -- max speed for smoothnesses
    smoothness_speeds = {
      intermediate    =  80,
      bad             =  40,
      very_bad        =  20,
      horrible        =  10,
      very_horrible   =  5,
      impassable      =  0
    },

    -- http://wiki.openstreetmap.org/wiki/Speed_limits
    maxspeed_table_default = {
      urban = 50,
      rural = 90,
      trunk = 110,
      motorway = 130
    },

    -- List only exceptions
    maxspeed_table = {
      ["at:rural"] = 100,
      ["at:trunk"] = 100,
      ["be:motorway"] = 120,
      ["be-vlg:rural"] = 70,
      ["by:urban"] = 60,
      ["by:motorway"] = 110,
      ["ch:rural"] = 80,
      ["ch:trunk"] = 100,
      ["ch:motorway"] = 120,
      ["cz:trunk"] = 0,
      ["cz:motorway"] = 0,
      ["de:living_street"] = 7,
      ["de:rural"] = 100,
      ["de:motorway"] = 0,
      ["dk:rural"] = 80,
      ["fr:rural"] = 80,
      ["gb:nsl_single"] = (60*1609)/1000,
      ["gb:nsl_dual"] = (70*1609)/1000,
      ["gb:motorway"] = (70*1609)/1000,
      ["nl:rural"] = 80,
      ["nl:trunk"] = 100,
      ['no:rural'] = 80,
      ['no:motorway'] = 110,
      ['pl:rural'] = 100,
      ['pl:trunk'] = 120,
      ['pl:motorway'] = 140,
      ["ro:trunk"] = 100,
      ["ru:living_street"] = 20,
      ["ru:urban"] = 60,
      ["ru:motorway"] = 110,
      ["uk:nsl_single"] = (60*1609)/1000,
      ["uk:nsl_dual"] = (70*1609)/1000,
      ["uk:motorway"] = (70*1609)/1000,
      ['za:urban'] = 60,
      ['za:rural'] = 100,
      ["none"] = 140
    },

    relation_types = Sequence {
      "route"
    },

    -- classify highway tags when necessary for turn weights
    highway_turn_classification = {
    },

    -- classify access tags when necessary for turn weights
    access_turn_classification = {
    }
  }
end

function process_node(profile, node, result, relations)
  -- parse access and barrier tags
  local access = find_access_tag(node, profile.access_tags_hierarchy)
  if access then
    if profile.access_tag_blacklist[access] and not profile.restricted_access_tag_list[access] then
      result.barrier = true
    end
  else
    local barrier = node:get_value_by_key("barrier")
    if barrier then
      --  check height restriction barriers
      local restricted_by_height = false
      if barrier == 'height_restrictor' then
         local maxheight = Measure.get_max_height(node:get_value_by_key("maxheight"), node)
         restricted_by_height = maxheight and maxheight < profile.vehicle_height
      end

      --  make an exception for rising bollard barriers
      local bollard = node:get_value_by_key("bollard")
      local rising_bollard = bollard and "rising" == bollard

      if not profile.barrier_whitelist[barrier] and not rising_bollard or restricted_by_height then
        result.barrier = true
      end
    end
  end

  -- check if node is a traffic light
  local tag = node:get_value_by_key("highway")
  if "traffic_signals" == tag then
    result.traffic_lights = true
  end
end

function process_way(profile, way, result, relations)
  -- the intial filtering of ways based on presence of tags
  -- affects processing times significantly, because all ways
  -- have to be checked.
  -- to increase performance, prefetching and intial tag check
  -- is done in directly instead of via a handler.

  -- in general we should  try to abort as soon as
  -- possible if the way is not routable, to avoid doing
  -- unnecessary work. this implies we should check things that
  -- commonly forbids access early, and handle edge cases later.

  -- data table for storing intermediate values during processing
  local data = {
    -- prefetch tags
    highway = way:get_value_by_key('highway'),
    bridge = way:get_value_by_key('bridge'),
    route = way:get_value_by_key('route')
  }

  -- perform an quick initial check and abort if the way is
  -- obviously not routable.
  -- highway or route tags must be in data table, bridge is optional
  if (not data.highway or data.highway == '') and
  (not data.route or data.route == '')
  then
    return
  end

  handlers = Sequence {
    -- set the default mode for this profile. if can be changed later
    -- in case it turns we're e.g. on a ferry
    WayHandlers.default_mode,

    -- check various tags that could indicate that the way is not
    -- routable. this includes things like status=impassable,
    -- toll=yes and oneway=reversible
    WayHandlers.blocked_ways,
    WayHandlers.avoid_ways,
    WayHandlers.handle_height,
    WayHandlers.handle_width,
    WayHandlers.handle_length,
    WayHandlers.handle_weight,

    -- determine access status by checking our hierarchy of
    -- access tags, e.g: motorcar, motor_vehicle, vehicle
    WayHandlers.access,

    -- check whether forward/backward directions are routable
    WayHandlers.oneway,

    -- check a road's destination
    WayHandlers.destinations,

    -- check whether we're using a special transport mode
    WayHandlers.ferries,
    WayHandlers.movables,

    -- handle service road restrictions
    WayHandlers.service,

    -- handle hov
    WayHandlers.hov,

    -- compute speed taking into account way type, maxspeed tags, etc.
    WayHandlers.speed,
    WayHandlers.surface,
    WayHandlers.maxspeed,
    WayHandlers.penalties,

    -- set penalty to try to follow legal access restriction
    WayHandlers.handle_weight,
    WayHandlers.handle_length,
    WayHandlers.handle_hgv_access,

    -- compute class labels
    WayHandlers.classes,

    -- handle turn lanes and road classification, used for guidance
    WayHandlers.turn_lanes,
    WayHandlers.classification,

    -- handle various other flags
    WayHandlers.roundabouts,
    WayHandlers.startpoint,
    WayHandlers.driving_side,

    -- set name, ref and pronunciation
    WayHandlers.names,

    -- set weight properties of the way
    WayHandlers.weights,

    -- set classification of ways relevant for turns
    WayHandlers.way_classification_for_turn
  }

  WayHandlers.run(profile, way, result, data, handlers, relations)

  if profile.cardinal_directions then
      Relations.process_way_refs(way, relations, result)
  end
end

function process_turn(profile, turn)
  -- Use a sigmoid function to return a penalty that maxes out at turn_penalty
  -- over the space of 0-180 degrees.  Values here were chosen by fitting
  -- the function to some turn penalty samples from real driving.
  local turn_penalty = profile.turn_penalty
  local turn_bias = turn.is_left_hand_driving and 1. / profile.turn_bias or profile.turn_bias

  if turn.has_traffic_light then
      turn.duration = profile.properties.traffic_light_penalty
  end

  if turn.number_of_roads > 2 or turn.source_mode ~= turn.target_mode or turn.is_u_turn then
    if turn.angle >= 0 then
      turn.duration = turn.duration + turn_penalty / (1 + math.exp( -((13 / turn_bias) *  turn.angle/180 - 6.5*turn_bias)))
    else
      turn.duration = turn.duration + turn_penalty / (1 + math.exp( -((13 * turn_bias) * -turn.angle/180 - 6.5/turn_bias)))
    end

    if turn.is_u_turn then
      turn.duration = turn.duration + profile.properties.u_turn_penalty
    end
  end

  -- for distance based routing we don't want to have penalties based on turn angle
  if profile.properties.weight_name == 'distance' then
     turn.weight = 0
  else
     turn.weight = turn.duration
  end

  if profile.properties.weight_name == 'routability' then
      -- penalize turns from non-local access only segments onto local access only tags
      if not turn.source_restricted and turn.target_restricted then
          turn.weight = constants.max_turn_weight
      end
  end
end

return {
  setup = setup,
  process_way = process_way,
  process_node = process_node,
  process_turn = process_turn
}

**Comment by jcoupey** [comment] 2023-01-25 14:29
The weight restriction can only happen within OSRM if it is able to assert that a restriction should apply. Are you sure the 7.5 ton limitation shown in your photo is actually reflected in the OSM data for that road portion?

**Comment by jcoupey** [comment] 2023-01-25 14:32
The problem is simply that [this way](https://www.openstreetmap.org/way/194017999) has no `maxweight` tag.

**Comment by Rougree** [comment] 2023-01-25 14:40
And do you know better data, where OSRM can work with, and have for example this `maxweight` tag? @jcoupey

**Comment by jcoupey** [comment] 2023-01-25 14:56
Yes, I'd expect respective coverage for `maxweight` and `maxheigth` tags to vary depending areas.

> And do you know better data, where OSRM can work with

That would be the Geofabrik OSM extract from tomorrow, including the `maxweight` tags you (and other contributors) added today.

**Comment by Rougree** [comment] 2023-01-25 19:02
Ok, Thanks for the quick response! I have a few questions left:
1. So, if I download the new OSM data and I'm using the profile.lua en lib with lua files I shared above OSRM should avoid this road? 
2. I found more roads where isn't a `maxweight` tag. Where can I indicate more roads with a missing `maxweight` tag?
3. Is it possible that I can change the data by myself?

**Comment by nilsnolde** [comment] 2023-01-25 21:16
> And do you know better data, where OSRM can work with, and have for example this maxweight tag?

Sure, TomTom (& to a lesser degree HERE) have pretty decent coverage for these attributes. There's reputable companies (e.g. us;)) converting those datasets to OSM so OSRM (and any other software consuming OSM routing data) can use it out-of-the-box. 

> Is it possible that I can change the data by myself?

Crowd-sourcing is kind of the point of OSM;) If you want to change it only for your use case but not contribute it back to the global OSM DB: be very careful about the ODBL license: https://www.openstreetmap.org/copyright.

**Comment by jcoupey** [comment] 2023-01-26 08:00
> Is it possible that I can change the data by myself?

OSM being a collaborative mapping effort means you can just create an account and start adding valuable information. You'll benefit from it as soon as it makes its way to the OSM extract you feed OSRM. The good part is that others will also benefit from your contributions, just as you get to use for free a worldwide database of road description contributed by others.

**Comment by Rougree** [comment] 2023-01-26 11:50
> > And do you know better data, where OSRM can work with, and have for example this maxweight tag?
> 
> Sure, TomTom (& to a lesser degree HERE) have pretty decent coverage for these attributes (and tons of other routing/navigation-related ones). There's reputable companies (e.g. us;)) converting those datasets to OSM so OSRM (and any other software consuming OSM "formatted" routing data) can use it out-of-the-box.
> 
Yeah, that is clear, I investigated the pricing model from for example tomtom. But this is really expense. See below the pricing:
![image](https://user-images.githubusercontent.com/52921963/214827603-e7d61ea3-8865-4a02-9c5d-ed9fe0aa1d02.png)

So, if I request a matrix from 500 by 500 daily, TomTom indicates that it is 500x5=2500 requests. That wil cost 10 EUR a day (4 EUR per 1000 requests) per request. 

@nilsnolde

**Comment by Rougree** [comment] 2023-01-26 11:51
> > Is it possible that I can change the data by myself?
> 
> OSM being a collaborative mapping effort means you can just create an account and start adding valuable information. You'll benefit from it as soon as it makes its way to the OSM extract you feed OSRM. The good part is that others will also benefit from your contributions, just as you get to use for free a worldwide database of road description contributed by others.

It would be nice that I would be a contributor. Where can I create an account?

**Comment by nilsnolde** [comment] 2023-01-26 12:57
> I investigated the pricing model from for example tomtom. But this is really expense.

I wasn't talking about using TomTom's API, that again puts you out of control about the routing and pretty much no one can really tell what exactly is happening on the routing level. I meant purchasing TomTom network data (which can be surprisingly cheap) and use it with OSRM/Valhalla/whatever. Read more here: https://github.com/gis-ops/prop2osm.

As much as I love OSM, it's just not sufficient for some more special routing applications like truck routing which depends on detailed and consistent attribution. And for serious/liable applications it'll never be. In terms of routing it's mostly more than good enough for car routing, and surely world-best for pedestrian/hiking & biking.

> Where can I create an account?

https://openstreetmap.org. Please research yourself a bit, this is kinda going very off-topic.

**Comment by Ramy-GreenRoutes** [comment] 2023-03-09 14:26
> The weight restriction can only happen within OSRM if it is able to assert that a restriction should apply based on the road network description. Are you sure the 7.5 ton limitation shown in your photo is actually reflected in the OSM data for that road portion?

@jcoupey Is it true that this way still doesn't have a weight tag? Today I downloaded the updated nl.osm.pbf en be.osm.pbf from geofabrik and unfortunately I still have the same problem as above.

**Comment by Rougree** [comment] 2023-03-09 14:28
> The problem is simply that [this way](https://www.openstreetmap.org/way/194017999) has no `maxweight` tag.

@jcoupey Is it true that this way still doesn't have a weight tag? Today I downloaded the updated nl.osm.pbf en be.osm.pbf from geofabrik and unfortunately I still have the same problem as above.

**Comment by jcoupey** [comment] 2023-03-10 11:58
> Is it true that this way still doesn't have a weight tag?

Just clicking on the link will show you that this way has been last edited 10 months ago and which tags it has.

Closing here as this is data-related and there is nothing actionable on the OSRM side.

**Closed by jcoupey** 2023-03-10 11:58 UTC
Labels: question, OSM Data

**Comment by Rougree** [comment] 2023-03-10 12:06
> > Is it true that this way still doesn't have a weight tag?
> 
> Just clicking on the link will show you that this way has been last edited 10 months ago and which tags it has.
> 
> Closing here as this is data-related and there is nothing actionable on the OSRM side.

That's weird, I expected after your comment that this road will be updated. However, is there smart way to find a road in OSM with a `weight tag`. I want to test osrm with weight tags.

**Comment by jcoupey** [comment] 2023-03-10 12:26
> I expected after your comment that this road will be updated.

This does not happen magically. Go ahead: create an OSM account and do it.

> is there smart way to find a road in OSM with a weight tag

You may want to checkout the Overpass tool https://overpass-turbo.eu/
