### ISSUE TITLE
Destination along zero speed segment results in NoRouteError

### ISSUE THREAD

**Issue by datwelk** [Project-OSRM/osrm-backend#5957] opened 2021-02-08 16:25 UTC
When I set the speed of a segment to 0 through the `--segment-speed-file` option supplied to `osrm-customize`, obviously the segment becomes not routable. But when the destination is along such as segment, instead of finding the nearest 'routable' path to that segment, the engine returns a No Route Error.

Is there a parameter I could supply to change this behaviour? Or could someone point me at file(s) where I could make this desired change? Thanks in advance.

Changing speed to a low value of e.g. 1 is not desirable since:
-  that will impact the ETA calculation;
-  the segment is not routable, so in any case the route shouldn't access the segment.

**Comment by danpat** [comment] 2021-02-08 16:45
This is basically a duplicate of this old known issue that we never fixed: https://github.com/Project-OSRM/osrm-backend/issues/4335

**Comment by datwelk** [comment] 2021-02-09 20:40
@danpat thanks, you're right that's the same issue. In addition to that thread, could you think of other ways to work around the issue?

**Comment by danpat** [comment] 2021-02-09 21:32
No workaround that I can think of - we need logic in the code to handle this case properly.

**Comment by SiarheiFedartsou** [comment] 2024-07-08 19:18
Stale.

**Closed by SiarheiFedartsou** 2024-07-08 19:18 UTC
